[project]
name = "ripper"
version = "0.1.0"
description = ""
authors = [{ name = "sixo", email = "michael.bowen@full360.com" }]
requires-python = "~=3.9"
dependencies = [
    "boto3==1.19.6",
    "vertica-python>=1.0.3,<2",
    "pytz==2021.3",
    "torch==1.10.0",
    "pandas==1.3.4",
    "Pillow==8.4.0",
    "torchvision==0.11.1",
    "regex==2021.11.10",
]

<<<<<<< HEAD
[tool.poetry.dependencies]
python = "^3.9"
boto3 = "1.19.6"
vertica-python = "^1.1.1"
pytz = "2021.3"
torch = "1.10.0"
pandas = "1.3.4"
Pillow = "8.4.0"
torchvision = "0.11.1"
regex = "2021.11.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
=======
[dependency-groups]
dev = ["pytest~=5.2"]
>>>>>>> main

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
