

CREATE  VIEW veeva.v_dedup_ids_call AS
 SELECT vc.id AS call_id,
        vc.account_vod__c AS veeva_account_id,
        vc.call_type_vod__c AS call_type,
        va.recordtypeid,
        vu.employeenumber AS rep_id,
        CASE WHEN (vc.created_by_timezone_tva__c IS NOT NULL) THEN "timezone"(vc.created_by_timezone_tva__c, vc.call_datetime_vod__c) WHEN (tz.zip IS NOT NULL) THEN "timezone"(tz.timezone_name, vc.call_datetime_vod__c) ELSE "timezone"(vu.timezonesidkey, vc.call_datetime_vod__c) END AS call_datetime,
        vc.how_executed_tva__c AS how_executed,
        CASE WHEN (vc.how_executed_tva__c = 'Engage Meeting'::varchar(14)) THEN 1 WHEN (vc.how_executed_tva__c = 'Face to Face'::varchar(12)) THEN 2 WHEN (vc.how_executed_tva__c = 'Phone – with Brand website'::varchar(28)) THEN 3 WHEN (vc.how_executed_tva__c = 'Phone'::varchar(5)) THEN 4 WHEN (vc.how_executed_tva__c = 'Phone - HCP'::varchar(11)) THEN 6 WHEN (vc.how_executed_tva__c = 'Phone - Staff'::varchar(13)) THEN 7 WHEN (vc.how_executed_tva__c = 'Approved Email'::varchar(14)) THEN 8 ELSE 100 END AS he_id
 FROM veeva.v_account va, (((veeva.call vc JOIN ( SELECT v_veeva_user.id,
        v_veeva_user.username,
        v_veeva_user.lastname,
        v_veeva_user.firstname,
        v_veeva_user.name,
        v_veeva_user.companyname,
        v_veeva_user.division,
        v_veeva_user.department,
        v_veeva_user.title,
        v_veeva_user.street,
        v_veeva_user.city,
        v_veeva_user.state,
        v_veeva_user.postalcode,
        v_veeva_user.country,
        v_veeva_user.latitude,
        v_veeva_user.longitude,
        v_veeva_user.email,
        v_veeva_user.emailpreferencesautobcc,
        v_veeva_user.emailpreferencesautobccstayint,
        v_veeva_user.emailpreferencesstayintouchrem,
        v_veeva_user.senderemail,
        v_veeva_user.sendername,
        v_veeva_user.signature,
        v_veeva_user.stayintouchsubject,
        v_veeva_user.stayintouchsignature,
        v_veeva_user.stayintouchnote,
        v_veeva_user.phone,
        v_veeva_user.fax,
        v_veeva_user.mobilephone,
        v_veeva_user.alias,
        v_veeva_user.communitynickname,
        v_veeva_user.isactive,
        v_veeva_user.timezonesidkey,
        v_veeva_user.userroleid,
        v_veeva_user.localesidkey,
        v_veeva_user.receivesinfoemails,
        v_veeva_user.receivesadmininfoemails,
        v_veeva_user.emailencodingkey,
        v_veeva_user.usertype,
        v_veeva_user.languagelocalekey,
        v_veeva_user.employeenumber,
        v_veeva_user.delegatedapproverid,
        v_veeva_user.managerid,
        v_veeva_user.lastlogindate,
        v_veeva_user.createddate,
        v_veeva_user.createdbyid,
        v_veeva_user.lastmodifieddate,
        v_veeva_user.lastmodifiedbyid,
        v_veeva_user.systemmodstamp,
        v_veeva_user.offlinetrialexpirationdate,
        v_veeva_user.offlinepdatrialexpirationdate,
        v_veeva_user.userpermissionsmarketinguser,
        v_veeva_user.userpermissionsofflineuser,
        v_veeva_user.userpermissionswirelessuser,
        v_veeva_user.userpermissionsavantgouser,
        v_veeva_user.userpermscallcenterautologin,
        v_veeva_user.userpermissionsmobileuser,
        v_veeva_user.userpermissionssfcontentuser,
        v_veeva_user.userpermissionsinteractionuser,
        v_veeva_user.userpermschatteranswersuser,
        v_veeva_user.forecastenabled,
        v_veeva_user.userprefsactivityreminderspopu,
        v_veeva_user.userprefseventreminderscheckbo,
        v_veeva_user.userprefstaskreminderscheckbox,
        v_veeva_user.userprefsremindersoundoff,
        v_veeva_user.userprefshidecsngetchattermobi,
        v_veeva_user.userprefshidecsndesktoptask,
        v_veeva_user.userpreferencesoptoutoftouch,
        v_veeva_user.userprefsshowtitletoexternalus,
        v_veeva_user.userprefsshowmanagertoexternal,
        v_veeva_user.userprefsshowemailtoexternalus,
        v_veeva_user.userprefsshowworkphonetoextern,
        v_veeva_user.userprefsshowmobilephonetoexte,
        v_veeva_user.userprefsshowfaxtoexternaluser,
        v_veeva_user.userprefsshowstreetaddresstoex,
        v_veeva_user.userprefsshowcitytoexternaluse,
        v_veeva_user.userprefsshowstatetoexternalus,
        v_veeva_user.userprefsshowpostalcodetoexter,
        v_veeva_user.userprefsshowcountrytoexternal,
        v_veeva_user.userprefsshowprofilepictoguest,
        v_veeva_user.userprefsshowtitletoguestusers,
        v_veeva_user.userprefsshowcitytoguestusers,
        v_veeva_user.userprefsshowstatetoguestusers,
        v_veeva_user.userprefsshowpostalcodetoguest,
        v_veeva_user.userprefsshowcountrytoguestuse,
        v_veeva_user.contactid,
        v_veeva_user.accountid,
        v_veeva_user.callcenterid,
        v_veeva_user.extension,
        v_veeva_user.federationidentifier,
        v_veeva_user.lastvieweddate,
        v_veeva_user.lastreferenceddate,
        v_veeva_user.last_mobile_connect_vod__c,
        v_veeva_user.last_tablet_connect_vod__c,
        v_veeva_user.last_mobile_connect_version,
        v_veeva_user.last_tablet_connect_version,
        v_veeva_user.last_mobile_sync_vod__c,
        v_veeva_user.last_tablet_sync_vod__c,
        v_veeva_user.raiselogginglevel_vod__c,
        v_veeva_user.senddetailedlog_vod__c,
        v_veeva_user.last_blackberry_connect_vod__c,
        v_veeva_user.last_blackberry_connect_versio,
        v_veeva_user.last_blackberry_sync_vod__c,
        v_veeva_user.force_full_refresh_vod__c,
        v_veeva_user.override_systemmodstamp_timest,
        v_veeva_user.facetime_email_vod__c,
        v_veeva_user.facetime_phone_vod__c,
        v_veeva_user.product_expertise_vod__c,
        v_veeva_user.available_vod__c,
        v_veeva_user.available_last_update_vod__c,
        v_veeva_user.last_ipad_connect_version,
        v_veeva_user.last_ipad_connect_vod__c,
        v_veeva_user.last_ipad_sync_vod__c,
        v_veeva_user.inventory_order_allocation_gro,
        v_veeva_user.concur_user_id_vod__c,
        v_veeva_user.external_id_tva__c,
        v_veeva_user.last_ipad_ios_version_vod__c,
        v_veeva_user.veeva_id__c,
        v_veeva_user.login_id_tva__c,
        v_veeva_user.primary_territory_vod__c,
        v_veeva_user.analytics_admin_vod__c,
        v_veeva_user.content_admin_vod__c,
        v_veeva_user.upload_vtrans_vod__c,
        v_veeva_user.can_sample_tva__c,
        v_veeva_user.do_not_modify_tva__c,
        v_veeva_user.profile_name_vod__c,
        v_veeva_user.file_id,
        v_veeva_user.record_id
 FROM veeva.v_veeva_user
 WHERE (length(v_veeva_user.lastname) <= 50)) vu ON ((vc.ownerid = vu.id))) LEFT  JOIN reference.zipcode_timezone tz ON ((vc.zip_vod__c = tz.zip))) LEFT  JOIN reference.how_executed he ON ((vc.how_executed_tva__c = he.how_executed)))
 WHERE ((va.id = vc.account_vod__c) AND (vc.id IN ( SELECT v_ids_call.id
 FROM veeva.v_ids_call)))
 GROUP BY vc.id,
          vc.account_vod__c,
          vc.call_type_vod__c,
          va.recordtypeid,
          vu.employeenumber,
          CASE WHEN (vc.created_by_timezone_tva__c IS NOT NULL) THEN "timezone"(vc.created_by_timezone_tva__c, vc.call_datetime_vod__c) WHEN (tz.zip IS NOT NULL) THEN "timezone"(tz.timezone_name, vc.call_datetime_vod__c) ELSE "timezone"(vu.timezonesidkey, vc.call_datetime_vod__c) END,
          vc.how_executed_tva__c,
          CASE WHEN (vc.how_executed_tva__c = 'Engage Meeting'::varchar(14)) THEN 1 WHEN (vc.how_executed_tva__c = 'Face to Face'::varchar(12)) THEN 2 WHEN (vc.how_executed_tva__c = 'Phone – with Brand website'::varchar(28)) THEN 3 WHEN (vc.how_executed_tva__c = 'Phone'::varchar(5)) THEN 4 WHEN (vc.how_executed_tva__c = 'Phone - HCP'::varchar(11)) THEN 6 WHEN (vc.how_executed_tva__c = 'Phone - Staff'::varchar(13)) THEN 7 WHEN (vc.how_executed_tva__c = 'Approved Email'::varchar(14)) THEN 8 ELSE 100 END;