
COPY /*12*/ sandbox.IMS ID ISSUE_AUSTEDO_10262020 FROM VERTICA teva.sandbox.IMS ID ISSUE_AUSTEDO_10262020;
COPY /*12*/ sandbox.SYNEOS TERRs MISSING IMS IDs FROM VERTICA teva.sandbox.SYNEOS TERRs MISSING IMS IDs;
COPY /*17*/ sandbox.reporting_markets FROM VERTICA teva.sandbox.reporting_markets;
COPY /*21*/ sandbox.IQVIA OPTUM OUTLETS11032020 FROM VERTICA teva.sandbox.IQVIA OPTUM OUTLETS11032020;
COPY /*54*/ sandbox.SYNEOS MISSING IMSIDs FROM VERTICA teva.sandbox.SYNEOS MISSING IMSIDs;
COPY /*116*/ sandbox.TN Mising HCPS for TN IC FROM VERTICA teva.sandbox.TN Mising HCPS for TN IC;
COPY /*146*/ sandbox.MA Missing STATE FROM VERTICA teva.sandbox.MA Missing STATE;
COPY /*274*/ sandbox.IMS ID ISSUES_AJOVY10262020 FROM VERTICA teva.sandbox.IMS ID ISSUES_AJOVY10262020;
COPY /*327*/ sandbox.sales_force_headcounts FROM VERTICA teva.sandbox.sales_force_headcounts;
COPY /*600*/ sandbox.SYNEOS TARGET FILE FROM VERTICA teva.sandbox.SYNEOS TARGET FILE;
COPY /*1033*/ sandbox.KNIPPER QVARs IDs1033 FROM VERTICA teva.sandbox.KNIPPER QVARs IDs1033;
COPY /*3780*/ sandbox.J_CHUNG_HCP DEA-2 FROM VERTICA teva.sandbox.J_CHUNG_HCP DEA-2;
COPY /*5284*/ sandbox.Returns_IQVIA  FROM VERTICA teva.sandbox.Returns_IQVIA ;
COPY /*9623*/ sandbox.par_rnf_ho FROM VERTICA teva.sandbox.par_rnf_ho;
COPY /*9823*/ sandbox.MediCal HCPs FROM VERTICA teva.sandbox.MediCal HCPs;
COPY /*17504*/ sandbox.QNASL_MRKT IMSID_ALL FROM VERTICA teva.sandbox.QNASL_MRKT IMSID_ALL;
COPY /*29171*/ sandbox.digital-affinity FROM VERTICA teva.sandbox.digital-affinity;
COPY /*33549*/ sandbox.ts_monthly_new_prescriber FROM VERTICA teva.sandbox.ts_monthly_new_prescriber;
COPY /*72083*/ sandbox.access_master_bridge_cdw_v1 FROM VERTICA teva.sandbox.access_master_bridge_cdw_v1;
COPY /*109503*/ sandbox.amb4_cdw_v1 FROM VERTICA teva.sandbox.amb4_cdw_v1;
COPY /*109503*/ sandbox.pivot_plan_prod_master_cdw_v1 FROM VERTICA teva.sandbox.pivot_plan_prod_master_cdw_v1;
COPY /*129180*/ sandbox.tp_anti_psych_weekly_new_prescriber FROM VERTICA teva.sandbox.tp_anti_psych_weekly_new_prescriber;
COPY /*208955*/ sandbox.comparison_ftf_health_plan_fid_cdw_v1 FROM VERTICA teva.sandbox.comparison_ftf_health_plan_fid_cdw_v1;
COPY /*210632*/ sandbox.ts_monthly_geography_summary FROM VERTICA teva.sandbox.ts_monthly_geography_summary;
COPY /*224953*/ sandbox.ts_weekly_new_prescriber FROM VERTICA teva.sandbox.ts_weekly_new_prescriber;
COPY /*238694*/ sandbox.ts_weekly_geography_summary FROM VERTICA teva.sandbox.ts_weekly_geography_summary;
COPY /*718730*/ sandbox.par_rnf_test FROM VERTICA teva.sandbox.par_rnf_test;
COPY /*842564*/ sandbox.ftf_iqvia_xref_cdw_v1 FROM VERTICA teva.sandbox.ftf_iqvia_xref_cdw_v1;
COPY /*842564*/ sandbox.ftf_iqvia_xref_v2_cdw_v1 FROM VERTICA teva.sandbox.ftf_iqvia_xref_v2_cdw_v1;
COPY /*1064328*/ sandbox.iqvia_plan_code_ftf_hp_id_cdw_v1 FROM VERTICA teva.sandbox.iqvia_plan_code_ftf_hp_id_cdw_v1;
COPY /*1205801*/ sandbox.tmp_monthly_hcp_trend_v2 FROM VERTICA teva.sandbox.tmp_monthly_hcp_trend_v2;
COPY /*1205801*/ sandbox.tmp_monthly_hcp_trend FROM VERTICA teva.sandbox.tmp_monthly_hcp_trend;
COPY /*1621070*/ sandbox.comparison_iqvia_fid_plans_cdw_v1 FROM VERTICA teva.sandbox.comparison_iqvia_fid_plans_cdw_v1;
COPY /*2365738*/ sandbox.ts_monthly_prescriber_sales FROM VERTICA teva.sandbox.ts_monthly_prescriber_sales;
COPY /*2528723*/ sandbox.tmp_monthly_hcp_activity FROM VERTICA teva.sandbox.tmp_monthly_hcp_activity;
COPY /*3631665*/ sandbox.tmp_weekly_hcp_trend FROM VERTICA teva.sandbox.tmp_weekly_hcp_trend;
COPY /*11318542*/ sandbox.tmp_weekly_hcp_activity FROM VERTICA teva.sandbox.tmp_weekly_hcp_activity;
COPY /*16540635*/ sandbox.LAI_monthly_prescriber_summary FROM VERTICA teva.sandbox.LAI_monthly_prescriber_summary;
COPY /*17152403*/ sandbox.ts_weekly_payer_prescriber_summary FROM VERTICA teva.sandbox.ts_weekly_payer_prescriber_summary;
COPY /*19183631*/ sandbox.ts_monthly_prescriber_summary FROM VERTICA teva.sandbox.ts_monthly_prescriber_summary;
COPY /*21610517*/ sandbox.ts_weekly_prescriber_sales FROM VERTICA teva.sandbox.ts_weekly_prescriber_sales;
COPY /*27114785*/ sandbox.ts_weekly_prescriber_summary FROM VERTICA teva.sandbox.ts_weekly_prescriber_summary;
COPY /*29030573*/ sandbox.ts_monthly_payer_prescriber_summary FROM VERTICA teva.sandbox.ts_monthly_payer_prescriber_summary;
COPY /*30236265*/ sandbox.ts_weekly_prescriber_sales_summary FROM VERTICA teva.sandbox.ts_weekly_prescriber_sales_summary;
COPY /*46596793*/ sandbox.tn_pre_calls_anti_psych FROM VERTICA teva.sandbox.tn_pre_calls_anti_psych;
COPY /*73527439*/ sandbox.ts_monthly_prescriber_sales_summary FROM VERTICA teva.sandbox.ts_monthly_prescriber_sales_summary;
COPY /*103051682*/ sandbox.tp_anti_psych_weekly_prescriber_sales FROM VERTICA teva.sandbox.tp_anti_psych_weekly_prescriber_sales;
COPY /*362669225*/ sandbox.tp_anti_psych_weekly_prescriber_sales_summary FROM VERTICA teva.sandbox.tp_anti_psych_weekly_prescriber_sales_summary;
COPY /*457378347*/ sandbox.tp_anti_psych_weekly_payer_prescriber_summary FROM VERTICA teva.sandbox.tp_anti_psych_weekly_payer_prescriber_summary;
COPY /*1439587855*/ sandbox.prescriber_rx_adhoc_06282021 FROM VERTICA teva.sandbox.prescriber_rx_adhoc_06282021;
COPY /*2406871391*/ sandbox.presr_rx_for_June_ic_07192021 FROM VERTICA teva.sandbox.presr_rx_for_June_ic_07192021;
COPY /*3097581722*/ sandbox.scd_prescriber_combined_demographics FROM VERTICA teva.sandbox.scd_prescriber_combined_demographics;
COPY /*3277054295*/ sandbox.ic_rx FROM VERTICA teva.sandbox.ic_rx;
DISCONNECT teva;