GRANT USAGE ON RESOURCE POOL "small_pool" to dbadmin with GRANT OPTION;
grant usage on RESOURCE POOL "small_pool" to system_monitor;
grant usage on RESOURCE POOL "small_pool" to AWANG02;
grant usage on RESOURCE POOL "small_pool" to BEinersen;
grant usage on RESOURCE POOL "small_pool" to CDW_EXTRACT;
grant usage on RESOURCE POOL "small_pool" to CDW_User;
grant usage on RESOURCE POOL "small_pool" to MCM_Tableau;
grant usage on RESOURCE POOL "small_pool" to ProductAdminUser;
grant usage on RESOURCE POOL "small_pool" to SalesOps;
grant usage on RESOURCE POOL "small_pool" to abrennan;
grant usage on RESOURCE POOL "small_pool" to adong01;
grant usage on RESOURCE POOL "small_pool" to alarkins;
grant usage on RESOURCE POOL "small_pool" to aswaminath;
grant usage on RESOURCE POOL "small_pool" to boberkro;
grant usage on RESOURCE POOL "small_pool" to ccompton;
grant usage on RESOURCE POOL "small_pool" to cmchenry;
grant usage on RESOURCE POOL "small_pool" to cstoeben;
grant usage on RESOURCE POOL "small_pool" to dallen04;
grant usage on RESOURCE POOL "small_pool" to dconklin;
grant usage on RESOURCE POOL "small_pool" to egunders;
grant usage on RESOURCE POOL "small_pool" to integration_user;
grant usage on RESOURCE POOL "small_pool" to jonahuy;
grant usage on RESOURCE POOL "small_pool" to jsmith11;
grant usage on RESOURCE POOL "small_pool" to jsteadman;
grant usage on RESOURCE POOL "small_pool" to kavyag;
grant usage on RESOURCE POOL "small_pool" to kgantenapa01;
grant usage on RESOURCE POOL "small_pool" to ksinclai;
grant usage on RESOURCE POOL "small_pool" to mbhawsar;
grant usage on RESOURCE POOL "small_pool" to psingh22;
grant usage on RESOURCE POOL "small_pool" to pwilson;
grant usage on RESOURCE POOL "small_pool" to rbansal01;
grant usage on RESOURCE POOL "small_pool" to rrajendr;
grant usage on RESOURCE POOL "small_pool" to tmcdowel;
grant usage on RESOURCE POOL "small_pool" to twhalen;
grant usage on RESOURCE POOL "small_pool" to CDW_Reporting;
grant usage on RESOURCE POOL "small_pool" to FieldOps;
grant usage on RESOURCE POOL "small_pool" to Kscarani;
grant usage on RESOURCE POOL "small_pool" to MDM_ETL;
grant usage on RESOURCE POOL "small_pool" to MKHAN14;
grant usage on RESOURCE POOL "small_pool" to ONCADJ;
grant usage on RESOURCE POOL "small_pool" to VRao;
grant usage on RESOURCE POOL "small_pool" to aalvarez;
grant usage on RESOURCE POOL "small_pool" to agokhman;
grant usage on RESOURCE POOL "small_pool" to akramer;
grant usage on RESOURCE POOL "small_pool" to bfages;
grant usage on RESOURCE POOL "small_pool" to bkoziol;
grant usage on RESOURCE POOL "small_pool" to cdigiacomo;
grant usage on RESOURCE POOL "small_pool" to chriskim;
grant usage on RESOURCE POOL "small_pool" to cwilliam05;
grant usage on RESOURCE POOL "small_pool" to dwhite03;
grant usage on RESOURCE POOL "small_pool" to ehalabe;
grant usage on RESOURCE POOL "small_pool" to ejiang;
grant usage on RESOURCE POOL "small_pool" to ekane;
grant usage on RESOURCE POOL "small_pool" to jrizzo;
grant usage on RESOURCE POOL "small_pool" to jstruthe;
grant usage on RESOURCE POOL "small_pool" to kerker;
grant usage on RESOURCE POOL "small_pool" to m_habeeb;
grant usage on RESOURCE POOL "small_pool" to mfletcher01;
grant usage on RESOURCE POOL "small_pool" to mlundt;
grant usage on RESOURCE POOL "small_pool" to mramsuesmi;
grant usage on RESOURCE POOL "small_pool" to nreigel02;
grant usage on RESOURCE POOL "small_pool" to ppatel40;
grant usage on RESOURCE POOL "small_pool" to prathaps;
grant usage on RESOURCE POOL "small_pool" to qa_user;
grant usage on RESOURCE POOL "small_pool" to rgopaluni01;
grant usage on RESOURCE POOL "small_pool" to rkrutsic_nl;
grant usage on RESOURCE POOL "small_pool" to rmotley;
grant usage on RESOURCE POOL "small_pool" to "rohit.amarnath";
grant usage on RESOURCE POOL "small_pool" to smukku;
grant usage on RESOURCE POOL "small_pool" to snandan;
grant usage on RESOURCE POOL "small_pool" to sqlpad;
grant usage on RESOURCE POOL "small_pool" to syengalwar01;
grant usage on RESOURCE POOL "small_pool" to tkeys;
grant usage on RESOURCE POOL "small_pool" to tryan01;
grant usage on RESOURCE POOL "small_pool" to yagarwal;
grant usage on RESOURCE POOL "small_pool" to yzhao03;
grant usage on RESOURCE POOL "small_pool" to CDW_Admin;
grant usage on RESOURCE POOL "small_pool" to aschmidt;
grant usage on RESOURCE POOL "small_pool" to asudhaka;
grant usage on RESOURCE POOL "small_pool" to cchalla;
grant usage on RESOURCE POOL "small_pool" to cdw_rpa;
grant usage on RESOURCE POOL "small_pool" to cmeyer;
grant usage on RESOURCE POOL "small_pool" to gmartin;
grant usage on RESOURCE POOL "small_pool" to gmwhite;
grant usage on RESOURCE POOL "small_pool" to harli;
grant usage on RESOURCE POOL "small_pool" to hdyer;
grant usage on RESOURCE POOL "small_pool" to hmohamma;
grant usage on RESOURCE POOL "small_pool" to jbutler01;
grant usage on RESOURCE POOL "small_pool" to kgantenapa;
grant usage on RESOURCE POOL "small_pool" to mcapehar;
grant usage on RESOURCE POOL "small_pool" to moshaughnessy;
grant usage on RESOURCE POOL "small_pool" to mvvergar;
grant usage on RESOURCE POOL "small_pool" to rashmiraj;
grant usage on RESOURCE POOL "small_pool" to rkrutsic;
grant usage on RESOURCE POOL "small_pool" to rweinsch;
grant usage on RESOURCE POOL "small_pool" to smcnulty02;
grant usage on RESOURCE POOL "small_pool" to ssurana;
grant usage on RESOURCE POOL "small_pool" to sthomas1;
grant usage on RESOURCE POOL "small_pool" to tokeefe;
grant usage on RESOURCE POOL "small_pool" to twoltkam;
grant usage on RESOURCE POOL "small_pool" to CDWAdmin;
grant usage on RESOURCE POOL "small_pool" to Databurst_Updt;
grant usage on RESOURCE POOL "small_pool" to HPSDevOpsUser;
grant usage on RESOURCE POOL "small_pool" to HPSDevOpsViewer;
grant usage on RESOURCE POOL "small_pool" to kbixler;
grant usage on RESOURCE POOL "small_pool" to nreigel;
grant usage on RESOURCE POOL "small_pool" to OraSuperUser;
grant usage on RESOURCE POOL "small_pool" to ITAdhoc;
grant usage on RESOURCE POOL "small_pool" to Marketacc;
grant usage on RESOURCE POOL "small_pool" to PKONIARIS;
grant usage on RESOURCE POOL "small_pool" to akashyap;
grant usage on RESOURCE POOL "small_pool" to cmason01;
grant usage on RESOURCE POOL "small_pool" to dluscomb;
grant usage on RESOURCE POOL "small_pool" to dpence;
grant usage on RESOURCE POOL "small_pool" to eaquino;
grant usage on RESOURCE POOL "small_pool" to ecs;
grant usage on RESOURCE POOL "small_pool" to gattili02;
grant usage on RESOURCE POOL "small_pool" to gobrien01;
grant usage on RESOURCE POOL "small_pool" to jchung;
grant usage on RESOURCE POOL "small_pool" to jmayhew;
grant usage on RESOURCE POOL "small_pool" to jmorrow;
grant usage on RESOURCE POOL "small_pool" to jpeng01;
grant usage on RESOURCE POOL "small_pool" to ksubramani03;
grant usage on RESOURCE POOL "small_pool" to lshelton;
grant usage on RESOURCE POOL "small_pool" to mophif;
grant usage on RESOURCE POOL "small_pool" to nshanfelt;
grant usage on RESOURCE POOL "small_pool" to nwright02;
grant usage on RESOURCE POOL "small_pool" to pmanto;
grant usage on RESOURCE POOL "small_pool" to spatkar;
grant usage on RESOURCE POOL "small_pool" to sramamur;
grant usage on RESOURCE POOL "small_pool" to tmoore02;
alter user AWANG02  RESOURCE POOL "small_pool";
alter user BEinersen  RESOURCE POOL "small_pool";
alter user CDW_User  RESOURCE POOL "small_pool";
alter user MCM_Tableau  RESOURCE POOL "small_pool";
alter user ProductAdminUser  RESOURCE POOL "small_pool";
alter user SalesOps  RESOURCE POOL "small_pool";
alter user abrennan  RESOURCE POOL "small_pool";
alter user adong01  RESOURCE POOL "small_pool";
alter user alarkins  RESOURCE POOL "small_pool";
alter user aswaminath  RESOURCE POOL "small_pool";
alter user boberkro  RESOURCE POOL "small_pool";
alter user ccompton  RESOURCE POOL "small_pool";
alter user cmchenry  RESOURCE POOL "small_pool";
alter user cstoeben  RESOURCE POOL "small_pool";
alter user dallen04  RESOURCE POOL "small_pool";
alter user dconklin  RESOURCE POOL "small_pool";
alter user egunders  RESOURCE POOL "small_pool";
alter user integration_user  RESOURCE POOL "small_pool";
alter user jonahuy  RESOURCE POOL "small_pool";
alter user jsmith11  RESOURCE POOL "small_pool";
alter user jsteadman  RESOURCE POOL "small_pool";
alter user kavyag  RESOURCE POOL "small_pool";
alter user kgantenapa01  RESOURCE POOL "small_pool";
alter user ksinclai  RESOURCE POOL "small_pool";
alter user mbhawsar  RESOURCE POOL "small_pool";
alter user psingh22  RESOURCE POOL "small_pool";
alter user pwilson  RESOURCE POOL "small_pool";
alter user rbansal01  RESOURCE POOL "small_pool";
alter user rrajendr  RESOURCE POOL "small_pool";
alter user tmcdowel  RESOURCE POOL "small_pool";
alter user twhalen  RESOURCE POOL "small_pool";
alter user FieldOps  RESOURCE POOL "small_pool";
alter user Kscarani  RESOURCE POOL "small_pool";
alter user MDM_ETL  RESOURCE POOL "small_pool";
alter user MKHAN14  RESOURCE POOL "small_pool";
alter user ONCADJ  RESOURCE POOL "small_pool";
alter user VRao  RESOURCE POOL "small_pool";
alter user aalvarez  RESOURCE POOL "small_pool";
alter user agokhman  RESOURCE POOL "small_pool";
alter user akramer  RESOURCE POOL "small_pool";
alter user bfages  RESOURCE POOL "small_pool";
alter user bkoziol  RESOURCE POOL "small_pool";
alter user cdigiacomo  RESOURCE POOL "small_pool";
alter user chriskim  RESOURCE POOL "small_pool";
alter user cwilliam05  RESOURCE POOL "small_pool";
alter user dwhite03  RESOURCE POOL "small_pool";
alter user ehalabe  RESOURCE POOL "small_pool";
alter user ejiang  RESOURCE POOL "small_pool";
alter user ekane  RESOURCE POOL "small_pool";
alter user jrizzo  RESOURCE POOL "small_pool";
alter user jstruthe  RESOURCE POOL "small_pool";
alter user kerker  RESOURCE POOL "small_pool";
alter user m_habeeb  RESOURCE POOL "small_pool";
alter user mfletcher01  RESOURCE POOL "small_pool";
alter user mlundt  RESOURCE POOL "small_pool";
alter user mramsuesmi  RESOURCE POOL "small_pool";
alter user nreigel02  RESOURCE POOL "small_pool";
alter user ppatel40  RESOURCE POOL "small_pool";
alter user prathaps  RESOURCE POOL "small_pool";
alter user qa_user  RESOURCE POOL "small_pool";
alter user rgopaluni01  RESOURCE POOL "small_pool";
alter user rkrutsic_nl  RESOURCE POOL "small_pool";
alter user rmotley  RESOURCE POOL "small_pool";
alter user "rohit.amarnath"  RESOURCE POOL "small_pool";
alter user smukku  RESOURCE POOL "small_pool";
alter user snandan  RESOURCE POOL "small_pool";
alter user sqlpad  RESOURCE POOL "small_pool";
alter user syengalwar01  RESOURCE POOL "small_pool";
alter user tkeys  RESOURCE POOL "small_pool";
alter user tryan01  RESOURCE POOL "small_pool";
alter user yagarwal  RESOURCE POOL "small_pool";
alter user yzhao03  RESOURCE POOL "small_pool";
alter user aschmidt  RESOURCE POOL "small_pool";
alter user asudhaka  RESOURCE POOL "small_pool";
alter user cchalla  RESOURCE POOL "small_pool";
alter user cdw_rpa  RESOURCE POOL "small_pool";
alter user cmeyer  RESOURCE POOL "small_pool";
alter user gmartin  RESOURCE POOL "small_pool";
alter user gmwhite  RESOURCE POOL "small_pool";
alter user harli  RESOURCE POOL "small_pool";
alter user hdyer  RESOURCE POOL "small_pool";
alter user hmohamma  RESOURCE POOL "small_pool";
alter user jbutler01  RESOURCE POOL "small_pool";
alter user kgantenapa  RESOURCE POOL "small_pool";
alter user mcapehar  RESOURCE POOL "small_pool";
alter user moshaughnessy  RESOURCE POOL "small_pool";
alter user mvvergar  RESOURCE POOL "small_pool";
alter user rashmiraj  RESOURCE POOL "small_pool";
alter user rkrutsic  RESOURCE POOL "small_pool";
alter user rweinsch  RESOURCE POOL "small_pool";
alter user smcnulty02  RESOURCE POOL "small_pool";
alter user ssurana  RESOURCE POOL "small_pool";
alter user sthomas1  RESOURCE POOL "small_pool";
alter user tokeefe  RESOURCE POOL "small_pool";
alter user twoltkam  RESOURCE POOL "small_pool";
alter user CDWAdmin  RESOURCE POOL "small_pool";
alter user HPSDevOpsUser  RESOURCE POOL "small_pool";
alter user HPSDevOpsViewer  RESOURCE POOL "small_pool";
alter user kbixler  RESOURCE POOL "small_pool";
alter user nreigel  RESOURCE POOL "small_pool";
alter user OraSuperUser  RESOURCE POOL "small_pool";
alter user ITAdhoc  RESOURCE POOL "small_pool";
alter user Marketacc  RESOURCE POOL "small_pool";
alter user PKONIARIS  RESOURCE POOL "small_pool";
alter user akashyap  RESOURCE POOL "small_pool";
alter user cmason01  RESOURCE POOL "small_pool";
alter user dluscomb  RESOURCE POOL "small_pool";
alter user dpence  RESOURCE POOL "small_pool";
alter user eaquino  RESOURCE POOL "small_pool";
alter user gattili02  RESOURCE POOL "small_pool";
alter user gobrien01  RESOURCE POOL "small_pool";
alter user jchung  RESOURCE POOL "small_pool";
alter user jmayhew  RESOURCE POOL "small_pool";
alter user jmorrow  RESOURCE POOL "small_pool";
alter user jpeng01  RESOURCE POOL "small_pool";
alter user ksubramani03  RESOURCE POOL "small_pool";
alter user lshelton  RESOURCE POOL "small_pool";
alter user mophif  RESOURCE POOL "small_pool";
alter user nshanfelt  RESOURCE POOL "small_pool";
alter user nwright02  RESOURCE POOL "small_pool";
alter user pmanto  RESOURCE POOL "small_pool";
alter user spatkar  RESOURCE POOL "small_pool";
alter user sramamur  RESOURCE POOL "small_pool";
alter user tmoore02  RESOURCE POOL "small_pool";