
GRANT SELECT ON SEQUENCE reference.ONC_SALES_ADJUST_SEQ TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON SEQUENCE product.BASKET_ID_SEQ_test TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON SEQUENCE reference.unreported_sales_seq TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON SEQUENCE tableau.fingerprint_dim_seq TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON ingestion_reference.EXT_AHM_EVENT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_EVENT_ATTENDEE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_EVENT_COUNT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_ORGANIZATION TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_SPEAKER_TRAINING TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_TOPIC_PRODUCT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ANDA_SALES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ANTIMIGRAINE_DDD_QUANTITY_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ASI_VOUCHER_DETAIL_WKLY_MK TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CAREMARK_RX2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CLM_PRESENTATION_SLIDE_VC TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CLM_PRESENTATION_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CLOZAPINE_UNIT_AP TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CONNECTIVERX_COUPON TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CONNECTIVERX_COUPON_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CUSTOMER_FLAGS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DDD_445_CALENDAR TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DIPLOMAT_ENROLLMENT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DIPLOMAT_RX TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FACTORY_SALES_852 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_HEALTH_PLANS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_RESTRICTIONS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_TIERS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_GOOGLE_ANALYTICS_360 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_AFFILIATION_TYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_BUSINESS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_BUSINESS_DETAIL_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_CLASS_OF_TRADE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_CLINICAL_CODE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_CONTACT_AFFILTN_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_IDENTIFIER_TYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_INDENTIFIER_CAT_TYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_PROFESSIONAL_TITLE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_PROF_DETAIL_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_I3_RX TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IDS_CALL2_DETAIL_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IDS_CALL2_KEY_MESSAGE_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_COPAY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_DDD_CHANGE_LOG TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_FACT_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_MPD TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_PRODUCT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_REJECT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_MHJ_QTY_W_ADHOC TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_OCHL_W TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_PBM_XREF TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_PDRP TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_PLAN_XREF TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_SD809_TRANSACTION TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_INNOVID_DELIVERY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_MM_RAM_TO_STATE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_ACCOUNT_TARGETS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_DMD_MONTHLY_DEMO_DOL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_DMD_MONTHLY_DOLLARS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_DMD_WEEKLY_DEMO TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_SALES_QUOTAS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_OPTUMRX_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_PCS_DDD_NONRETAIL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_PCS_DDD_RETAIL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_PROGNOS_CINQAIR_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_PROGNOS_SYNDICATED_TRIGGER_REPORT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_REFERENCE_INCLUDE_867_COT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_REMS_FACILITY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_REMS_PRESCRIBER TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TB_CB_ACCOUNTS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TB_CB_TRANSACTIONS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TB_DS_ACCOUNTS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TB_DS_TRANSACTIONS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TEVA_AHM_UNNAMEDPARTICIPANT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TOUCHPOINT_CALL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TOUCHPOINT_PRESENTATION TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_AFFILIATION_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_CALL2_KEY_MESSAGE_VOD TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_CALL_CLICKSTREAM_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_RECORDTYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_REMOTE_MEETING_ATTENDEE_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_SURVEY_QUESTION_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_TERRITORY2MODEL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_TERRITORY2TYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_USERROLE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_USERTERRITORY2ASSOCIATION TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_WHOLESALE_867 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZS_CALL_PLAN_TN TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZS_CALL_PLAN_TS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZS_TEVA_PAYER_MASTER_DETALS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_ADDRESS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_ADDRESS_LINK TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_ALTERNATE_ID TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_HCP TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_HCP_TEVA_FLAG TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_LICENSE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_MERGES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_REGULATION TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_SAMPLE_ELIGIBILITY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_SOURCE_DETAILS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ONC_SALES_ADJUSTMENT_LOAD TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_CALC_PBM_KEY_PBM_MAPPING_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_COPAY_TIER_DERIVATION_CONFIG_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_COVERAGE_CATEGORY_DERIVATION_CONFIG TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_HAS_PA_MAPPING_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_MEDICAL_REC_RESTRICTION_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_OVERRIDE_BRIDGE_FTF_PLAN_TYPES_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_PA_RESTRICTION_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_PRES_PA_RESTRICTION_DESCRIPTION_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_RESTRICTION_CATEGORY_DERIVATION_CONFIG_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_UNSPECIFIED_REC_RESTRICTION_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.XPD_ADD_ON_DETAILS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhj_cnt_w TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhj_cnt_w_adhoc TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhj_control_m TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhj_qty_m_adhoc TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhk_cnt_w TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhk_qty_m TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_vv_approved_document__c TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_vv_objectterritory2assignmentruleitem TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXTERNAL_TABLE_CLEANUP TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ACTIVITY_LINE_ITEM TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AGGREGATED_ACTIVITY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_EVENT_HOST TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_EVENT_PRODUCT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_SPEAKER_CONTRACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_SPEAKER_LICENSE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ANTIMIGRAINE_DDD_DOLLARS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ANTIMIGRAINE_DDD_QUANTITY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ASI_COPAY_DETAIL_WKLY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ASI_COPAY_DETAIL_WKLY_MCK TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ASI_COPAY_DETAIL_WKLY_PSKW TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ASI_COPAY_VOUCHER_DETAIL_WKLY_PSKW TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ASI_VOUCHER_DETAIL_WKLY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AXTRIA_AXTRIASALESIQTM_EMPLOYEE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AXTRIA_AXTRIASALESIQTM_EMPLOYEE_v2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AXTRIA_EMPLOYEE_ASSIGNMENT_STATUS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_BING_ADS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CC_TITRATION_DOSAGE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CMOP_RX_DATA_TEVA TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CMOP_RX_DATA_TEVA_HIST TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DA_DIGITAL_SPEND_DATA TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DA_PRINT_SPEND_DATA TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DDD_DOD_SALES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DDD_QUANTITY_M_ADHOC TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_F60Q TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_DRUGS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_FORMULARIES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_IMS_BRIDGE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_PBMS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_RESTRICTIONS_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_TEVA_WK_BRIDGE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_ACO_DETAIL_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_ACO_ORG_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_ACO_TYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_BED_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_BED_TYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_BUSINESS_DETAIL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_CLINICAL_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_CLINICAL_FACT_NATION TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_CLINICAL_FACT_STATE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_COT_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_DDD_XFER TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_FINANCIAL_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_INDENTIFIER_TERM_TYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_PROFESSIONAL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_PROFESSIONAL_DETAIL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_PROF_SPECIALTY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_PROF_SPEC_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_RELATIONSHIP_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IDS_CALL2_SAMPLE_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_GEOGRAPHY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_GEOGRAPHY_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_REJECT_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FR61 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_NTIS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_OMNICARE_SALES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_DDD_MONTHLY_RETAIL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_DDD_WEEKLY_RETAIL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_DMD_WEEKLY_SALES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_PRIME_RX TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_PROGNOS_CINQAIR TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_REFERENCE_INCLUDE_DDD_SUBCAT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_RELIANCE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_REMS_PHARMACY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_SIEBEL_PRSN_ACCTS_TO_VEEVA TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TEVA_AHM_EXPENSE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TEVA_AHM_INTERACTIONS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TIME_OFF_TERRITORY_KC TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TRIALCARD_COUPON TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_BIOLOGICS_MISSING_INFO TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_ICS_ACCOUNT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_ICS_ASI TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_ADDRESS_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_CALL_GOAL_TVA__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_DECILES_TVA__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_EMAIL_ACTIVITY_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_GROUP TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_KEY_MESSAGE_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_OBJECTTERRITORY2ASSOCIATION TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_QUESTION_RESPONSE_VOD TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_SUGGESTION_FEEDBACK_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_SUGGESTION_TAG_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_SUGGESTION_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_SURVEY_TARGET_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_SURVEY_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_SYNC_TRACKING_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_TERRITORY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_TERRITORY2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_USER TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_USERTERRITORY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_WHOLESALE_867_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_YAHOO_GEMINI TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZIP_TO_TERR TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_ALTERNATE_NAME TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_COMMUNICATION TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_HCO_TEVA_FLAG TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_PROFESSIONAL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_RAW_NPI TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_SPECIALTY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_CALCULATED_PBM_CONFIG_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_DRUG_ASSIGNMENTS_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_FTF_OVERRIDE_PROVIDER_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_FTF_PBM_FUNCTIONS_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_HAS_ST_MAPPING_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_IQVIA_PAYTYPEINDEX_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_KEY_CONTROLLER_LIST_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_MODEL_PAYTYPE_MAP_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_OVERRIDE_FID_IQVIA_KEY_CONTROLLER_LIST_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_PAT_PA_RESTRICTION_DESCRIPTION_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_STEP_RESTRICTION_DESCRIPTION_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_STEP_RESTRICTION_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.XPD_CORE_METRICS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.XPD_SWITCH_DETAILS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_drm45_w TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhj_cnt_m TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhj_control_w TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhj_qty_w TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_vv_objectterritory2assignmentrule TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_vv_rep_roster_vod__c TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ACTIVITY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_EVENT_EXPENSE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_EVENT_SPEAKER TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AHM_SPEAKER_PROFILE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ANTIMIGRAINE_DDD_DOLLARS_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ASI_COPAY_DETAIL_WKLY_CGD TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ASI_COPAY_REDEMPTIONS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ASI_REDEMPTIONS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AXTRIA_EMPLOYEE_ASSIGNMENT_STATUS_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_AXTRIA_TERRITORY_HIERARCHY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_CMOP_RX_DATA_TEVA_ADD TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DA_BROADCAST_DATA TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DDD_DOD_QTY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DDD_DOLLARS_M_ADHOC TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DX_CLAIMS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_DYNAMIC_SEGMENT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_ACCOUNTS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_CONTROL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_COPAYS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_DRUG_CLASS_THRPTC_AREA TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_FTF_HEALTH_PLAN_GEOGRAPHY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_ACO_DETAIL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_ACO_PROFESSIONAL_RSTR TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_BED_CLUSTER_TYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_IDENTIFIER_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_PROVIDER_AFFILTN_FACT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_HCOS_RELATIONSHIP_TYPE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_I3_BY_STRENGTH_RX TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_I3_TYSABRI_RX TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IDS_CALL2_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_DEA TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_PLAN TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_PLAN_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_PRODUCT_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_FIA_PROVIDER_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_OCHL_M TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_IMS_PLAN_XREF_ACCELERATED TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_INNOVID_VIEWABILITY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_INTEGRAL_AD_SCIENCE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_KEY_MESSAGE_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_KNIPPER_SAMPLES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_CALL_DETAIL_GOALS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_DMD_MONTHLY_DEMO_QTY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_DMD_MONTHLY_QUANTITY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ONC_MANUAL_FCRS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_OPTUMRX TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_PSKW_GRANIX_COUPON_SAVINGS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_PSRF_UTIL_RPT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_PSR_REPORT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_REFERENCE_COPAY_VOUCHER_PROGRAM TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_REMS_DISTRIBUTOR TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_SIEBEL_BUS_ACCTS_TO_VEEVA TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_SPECIALTY_PHARMACY_CM_LKUP TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_SPECIALTY_PHARMACY_LOOKUPS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TEVA_AHM_PARTICIPANT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TIME_OFF_TERRITORY_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_ANDA_SALES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_BIOLOGICS_DISPENSE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_BIOLOGICS_HUB TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_BIOLOGICS_REFERRAL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_BIOLOGICS_SALES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_HD_SMITH_SALES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_TW_ICS_SALES TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_ACCOUNT TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_ACCOUNTSHARE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_ACCT_MERGE_HISTORY_VOD TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_ASSESSMENT__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_CALL2_DETAIL_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_CALL2_SAMPLE_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_CALL2_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_CALL2_VOD__HISTORY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_MEDICAL_EVENT_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_MEDICAL_INQUIRY_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_PRODUCT_METRICS_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_PRODUCT_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_REMOTE_MEETING_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_RULETERRITORY2ASSOCIATION TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_SENT_EMAIL_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_TERRITORY2MODELHISTORY TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_VV_TSF_VOD__C TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZIP_TO_TERR_V2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZS_CALL_PLAN_TC TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZS_CALL_PLAN_TP TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZS_CALL_PLAN_TR TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZS_CALL_PLAN_TW TO CDW_Admin;
GRANT SELECT ON ingestion_reference.EXT_ZS_TEVA_PAYER_WRKBK TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_DEA_ADDRESS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_EMAIL_PREFERENCE TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_HCO TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_IMS_FLAG TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_MARKETING_CHANNEL TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_RAW_DEA TO CDW_Admin;
GRANT SELECT ON ingestion_reference.MDM_RELATIONSHIP TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_BOTOX_STEP_RESTRICTION_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_COVERAGE_CAT_DESCRIPTION_MAPPING_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_DELETE_BRIDGE_FTF_PLAN_TYPES_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_FORMULARY_DERIVATION_CONFIG_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_FTF_OVERRIDE_PLAN_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_FTF_PAYTYPE_PAYTYPEINDEX_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_FTF_PLANS_PAYTYPEINDEX_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_IQVIA_PAYER_PAYTYPE_OVERRIDE_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_IQVIA_PLANS_DISCARD_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_PATIENT_PA_RESTRICTION_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_PROVIDER_OVERRIDE_DEFAULT_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_RESTRICTION_CAT_DESCRIPTION_MAPPING_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.PS_TIER_CAT_DESCRIPTION_MAPPING_V01 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.XPD_DEMOGRAPHICS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.XPD_RESTART_DIFF_DETAILS TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_drm45_m TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhj_cnt_m_adhoc TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhj_qty_m TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhk_cnt_m TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_ims_mhk_qty_w TO CDW_Admin;
GRANT SELECT ON ingestion_reference.ext_knipper_samples_v2 TO CDW_Admin;
GRANT SELECT ON ingestion_reference.tmp2 TO CDW_Admin;
GRANT INSERT ON reporting.nh_anti_psych_weekly_prescriber_sales_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_anti_psych_weekly_prescriber_sales_summary TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_anti_psych_weekly_prescriber_sales TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_anti_psych_weekly_prescriber_sales TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_anti_psych_weekly_new_prescriber TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_anti_psych_weekly_new_prescriber TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_anti_psych_weekly_new_prescriber TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_anti_psych_weekly_new_prescriber TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_anti_psych_weekly_new_prescriber TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_anti_psych_weekly_new_prescriber TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_anti_psych_weekly_new_prescriber TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_anti_psych_weekly_new_prescriber TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_anti_psych_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_anti_psych_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_anti_psych_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_anti_psych_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_anti_psych_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_anti_psych_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_anti_psych_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_anti_psych_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_monthly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_monthly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_anti_psych_weekly_prescriber_sales TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_anti_psych_weekly_prescriber_sales TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_anti_psych_weekly_prescriber_sales TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_anti_psych_weekly_prescriber_sales TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_anti_psych_weekly_prescriber_sales TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_anti_psych_weekly_prescriber_sales TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_monthly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_monthly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_anti_psych_weekly_prescriber_sales_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_anti_psych_weekly_prescriber_sales_summary TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_anti_psych_weekly_prescriber_sales_summary TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_anti_psych_weekly_prescriber_sales_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_anti_psych_weekly_prescriber_sales_summary TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_anti_psych_weekly_prescriber_sales_summary TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_monthly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_monthly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_monthly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_monthly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_monthly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_monthly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_monthly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_monthly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_pre_call_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_pre_call_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_monthly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_monthly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_monthly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_monthly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_monthly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_monthly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_monthly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_monthly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_monthly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_monthly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_monthly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_monthly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_pre_calls_anti_psych TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_pre_calls_anti_psych TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_pre_call_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_pre_call_summary TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_pre_call_summary TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_pre_call_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_pre_call_summary TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_pre_call_summary TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_pre_calls_anti_psych TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_pre_calls_anti_psych TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_pre_calls_anti_psych TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_pre_calls_anti_psych TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_pre_calls_anti_psych TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_pre_calls_anti_psych TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_weekly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_weekly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_weekly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_weekly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_weekly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_weekly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_weekly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_weekly_geography_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_weekly_payer_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT INSERT ON reporting.nh_weekly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON reporting.nh_weekly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT UPDATE ON reporting.nh_weekly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DELETE ON reporting.nh_weekly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT ALTER ON reporting.nh_weekly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT REFERENCES ON reporting.nh_weekly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT DROP ON reporting.nh_weekly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT TRUNCATE ON reporting.nh_weekly_prescriber_summary TO CDW_Admin WITH GRANT OPTION;
GRANT SELECT ON metadata.outbound_table_counts TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_infl_summary TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_infl_summary TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_infl_summary TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_infl_summary TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_infl_summary TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_key_controlling_account_summary TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_key_controlling_account_summary TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_key_controlling_account_summary TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_key_controlling_account_summary TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_key_controlling_account_summary TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_key_pbm_summary TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_key_pbm_summary TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_key_pbm_summary TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_key_pbm_summary TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_key_pbm_summary TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ftf_hp_id_key_controlling_plan_account TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ftf_hp_id_key_controlling_plan_account TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ftf_hp_id_key_controlling_plan_account TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ftf_hp_id_key_controlling_plan_account TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ftf_hp_id_key_controlling_plan_account TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_iqvia_plan_code_ftf_hp_id TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_iqvia_plan_code_ftf_hp_id TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_iqvia_plan_code_ftf_hp_id TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_iqvia_plan_code_ftf_hp_id TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_iqvia_plan_code_ftf_hp_id TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_key_pbm_product_coverage_category_commercial TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_key_pbm_product_coverage_category_commercial TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_key_pbm_product_coverage_category_commercial TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_key_pbm_product_coverage_category_commercial TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_key_pbm_product_coverage_category_commercial TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_pay_type_product_copay_tier TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_pay_type_product_copay_tier TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_pay_type_product_copay_tier TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_pay_type_product_copay_tier TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_pay_type_product_copay_tier TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_pay_type_product_patient_pa TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_pay_type_product_patient_pa TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_pay_type_product_patient_pa TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_pay_type_product_patient_pa TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_pay_type_product_patient_pa TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_pay_type_product_step_edit_type TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_pay_type_product_step_edit_type TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_pay_type_product_step_edit_type TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_pay_type_product_step_edit_type TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_pay_type_product_step_edit_type TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_payer_spine25_plan_teva_brands TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_payer_spine25_plan_teva_brands TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_payer_spine25_plan_teva_brands TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_payer_spine25_plan_teva_brands TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_payer_spine25_plan_teva_brands TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_IMS_DDD_CHANGE_LOG TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_IMS_MHK_CNT_M TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_IMS_MHK_QTY_M TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_IMS_MHK_QTY_W TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_SIEBEL_BUS_ACCTS_TO_VEEVA TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_VV_CALL2_VOD__C_test TO CDW_Admin;
GRANT SELECT ON metadata.datamart_table_counts TO CDW_Admin;
GRANT SELECT ON metadata.raw_view_counts_by_file_id TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_cm_state_lives_formular_status TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_cm_state_lives_formular_status TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_cm_state_lives_formular_status TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_cm_state_lives_formular_status TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_cm_state_lives_formular_status TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ftf_hp_id_key_pbm TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ftf_hp_id_key_pbm TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ftf_hp_id_key_pbm TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ftf_hp_id_key_pbm TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ftf_hp_id_key_pbm TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_payer_spine25_detailed_teva_brands TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_payer_spine25_detailed_teva_brands TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_payer_spine25_detailed_teva_brands TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_payer_spine25_detailed_teva_brands TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_payer_spine25_detailed_teva_brands TO CDW_Admin;
GRANT SELECT ON sfa_history.v_siebel_samples_prof TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXTERNAL_TABLE_CLEANUP TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_CAREMARK_RX2 TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_SIEBEL_PRSN_ACCTS_TO_VEEVA TO CDW_Admin;
GRANT SELECT ON teva_ingestion.MS_WKLY_RX_QTY TO CDW_Admin;
GRANT SELECT ON metadata.reference_table_counts TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_all_changes TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_all_changes TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_all_changes TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_all_changes TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_all_changes TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_health_plan_detail TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_health_plan_detail TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_health_plan_detail TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_health_plan_detail TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_health_plan_detail TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_claims_proc_summary TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_claims_proc_summary TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_claims_proc_summary TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_claims_proc_summary TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_claims_proc_summary TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_mgt_summary TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_mgt_summary TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_mgt_summary TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_mgt_summary TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_ftf_pbm_formulary_mgt_summary TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_pbm_summary TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_pbm_summary TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_pbm_summary TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_pbm_summary TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_pbm_summary TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_player_summary TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_player_summary TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_player_summary TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_player_summary TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ajovy_migraine_market_iqvia_player_summary TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_ftf_plan_master_file TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_ftf_plan_master_file TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_ftf_plan_master_file TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_ftf_plan_master_file TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_ftf_plan_master_file TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_commercial TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_commercial TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_commercial TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_commercial TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_key_controlling_account_product_coverage_category_commercial TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_key_pbm_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_key_pbm_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_key_pbm_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_key_pbm_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_key_pbm_product_coverage_category_allpaytypes TO CDW_Admin;
GRANT INSERT ON payerspine.vw_final_extract_pay_type_product_coverage_category TO CDW_Admin;
GRANT UPDATE ON payerspine.vw_final_extract_pay_type_product_coverage_category TO CDW_Admin;
GRANT DELETE ON payerspine.vw_final_extract_pay_type_product_coverage_category TO CDW_Admin;
GRANT REFERENCES ON payerspine.vw_final_extract_pay_type_product_coverage_category TO CDW_Admin;
GRANT TRUNCATE ON payerspine.vw_final_extract_pay_type_product_coverage_category TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_CMOP_RX_DATA_TEVA_HIST TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_IMS_DEA TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_IMS_MHK_CNT_W TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_IMS_PDRP TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_NTIS TO CDW_Admin;
GRANT SELECT ON teva_ingestion.EXT_TW_ICS_ASI TO CDW_Admin;
GRANT SELECT ON teva_ingestion.MS_MTHLY_RX_CNT TO CDW_Admin;
GRANT SELECT ON teva_ingestion.MS_MTHLY_RX_QTY TO CDW_Admin;
GRANT SELECT ON teva_ingestion.MS_WKLY_RX_CNT TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_file_id OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_pre_calls_anti_psych OWNER TO CDW_Admin;
ALTER TABLE reporting.austedo_leadership_dashboard OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_outlet_subcat OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_remain_subcat OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_onc_demo_sales_adjusts OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_onc_demo_allocated OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_onc_demo_parents_no_outlet OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_onc_demo_parents OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_onc_ddd_retail OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_onc_demo_prescribers OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_onc_demo_facilities OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_onc_demo_outlets OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_tvcmid_ddd_md OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_tvcmid_ddd OWNER TO CDW_Admin;
ALTER TABLE sandbox.tmp_region_area_c_new OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_rx_decile_d OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_rx_decile_c OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_rx_decile_b OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_rx_decile_a OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_dollars OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_ddd OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_445 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_445_2 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_445_1 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_demo_rank2 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_demo_rank1 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_call_detail_cd OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_merge OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_oncology_adjusted_sales OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_product_model_all OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_tvcmid_combine_final OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_tvcmid_combine OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_ddd_md_qty OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_ddd_qty OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_dup_outlet OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_dup_tvcmid OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_teva OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_i3_by_strength OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_globals OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_anti_psych_weekly_payer_prescriber_summary OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_anti_psych_weekly_prescriber_sales_summary OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_anti_psych_weekly_prescriber_sales OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_anti_psych_weekly_new_prescriber OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_weekly_geography_summary OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_weekly_payer_prescriber_summary OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_weekly_prescriber_summary OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_pre_call_summary OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_monthly_geography_summary OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_monthly_payer_prescriber_summary OWNER TO CDW_Admin;
ALTER TABLE reporting.nh_monthly_prescriber_summary OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_region_area_c OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_digital_edetail2 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_digital_1 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_call_key_message OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_call_detail_dsa OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_digital_final OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_digital_3 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_TR OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_region_area_cs3 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_region_area_cs2 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_region_area_cs OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_sample_s OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_call_s OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_sfa_survey2 OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_sfa_survey OWNER TO CDW_Admin;
ALTER TABLE sandbox.tmp_call_hist_c_new OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_product_model OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_ddd_md OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_445_md OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_445_2_md OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_445_1_md OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_file_id_ddd_md OWNER TO CDW_Admin;
ALTER TABLE sandbox.tmp_file_id_ddd_md OWNER TO CDW_Admin;
ALTER TABLE sandbox.tmp_lat_lon_sfa OWNER TO CDW_Admin;
ALTER TABLE sandbox.tmp_demo_rank2 OWNER TO CDW_Admin;
ALTER TABLE sandbox.tmp_demo_rank1 OWNER TO CDW_Admin;
ALTER TABLE datamart.tmp_onc_demo_sales_alloc_adjusts OWNER TO CDW_Admin;
ALTER TABLE datamart.tmp_globals OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_file_id_purge OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_rx_decile OWNER TO CDW_Admin;
ALTER TABLE WSMP_ADMIN_ORA.tmp_global_date OWNER TO CDW_Admin;
ALTER VIEW reporting.fcr_summary OWNER TO CDW_Admin;
ALTER VIEW WSMP_ADMIN_ORA.Syneos_Cinqair_dddmd OWNER TO CDW_Admin;
ALTER VIEW outbound.concur_hcp_delta OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_xpd_switch_details OWNER TO CDW_Admin;
ALTER VIEW sandbox.ics_mop OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_access_monitor_calls_by_specialty_respiratory OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_access_monitor_calls_by_specialty_oncology OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_access_monitor_call_data_respiratory OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_access_monitor_call_data_oncology OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_access_monitor_call_data_cns OWNER TO CDW_Admin;
ALTER VIEW sfa_history.v_siebel_samples_prof OWNER TO CDW_Admin;
ALTER VIEW metadata.datamart_table_counts OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_access_monitor_detailed_data_respiratory OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_access_monitor_detailed_data_oncology OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_access_monitor_detailed_data_cns OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_access_monitor_calls_by_specialty_cns OWNER TO CDW_Admin;
ALTER VIEW sandbox.ad_hoc_ad OWNER TO CDW_Admin;
ALTER VIEW sandbox.knipper_supplemental_test OWNER TO CDW_Admin;
ALTER VIEW sandbox.create_paragard_anda_sales OWNER TO CDW_Admin;
ALTER VIEW metadata.cleansed_table_counts_by_file_id OWNER TO CDW_Admin;
ALTER VIEW metadata.raw_view_counts_by_file_id OWNER TO CDW_Admin;
ALTER VIEW metadata.reference_table_counts OWNER TO CDW_Admin;
ALTER VIEW outbound.asrs_count OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_xpd_core_metrics OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_xpd_demographics OWNER TO CDW_Admin;
ALTER VIEW sandbox.asi_market_access_w_test OWNER TO CDW_Admin;
ALTER VIEW outbound.zs_calls_by_specialty OWNER TO CDW_Admin;
ALTER VIEW outbound.ftf_ims_monthly_market_obm OWNER TO CDW_Admin;
ALTER VIEW metadata.outbound_table_counts OWNER TO CDW_Admin;