
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.IMS ID ISSUE_AUSTEDO_10262020), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'IMS ID ISSUE_AUSTEDO_10262020';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.MA Missing STATE), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'MA Missing STATE';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.SYNEOS TARGET FILE), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'SYNEOS TARGET FILE';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.J_CHUNG_HCP DEA-2), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'J_CHUNG_HCP DEA-2';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.tmp_hcp_details), audit_init_epoch = 62405579, audit_init_ts = '2022-05-03 23:45:23.144406' where table_schema = 'sandbox' and table_name = 'tmp_hcp_details';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.IMS ID ISSUES_AJOVY10262020), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'IMS ID ISSUES_AJOVY10262020';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.KNIPPER QVARs IDs1033), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'KNIPPER QVARs IDs1033';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.Returns_IQVIA ), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'Returns_IQVIA ';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.MediCal HCPs), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'MediCal HCPs';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.QNASL_MRKT IMSID_ALL), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'QNASL_MRKT IMSID_ALL';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.SYNEOS TERRs MISSING IMS IDs), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'SYNEOS TERRs MISSING IMS IDs';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.SYNEOS MISSING IMSIDs), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'SYNEOS MISSING IMSIDs';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.digital-affinity), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'digital-affinity';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.tmp_hcp_activity_rx), audit_init_epoch = 62607468, audit_init_ts = '2022-05-03 23:53:22.466482' where table_schema = 'sandbox' and table_name = 'tmp_hcp_activity_rx';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.tmp_hcp_dimentions), audit_init_epoch = 62604476, audit_init_ts = '2022-05-03 23:53:22.025189' where table_schema = 'sandbox' and table_name = 'tmp_hcp_dimentions';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.IQVIA OPTUM OUTLETS11032020), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'IQVIA OPTUM OUTLETS11032020';
update migration.audit set export_ts = sysdate(), export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.TN Mising HCPS for TN IC), audit_init_epoch = None, audit_init_ts = 'None' where table_schema = 'sandbox' and table_name = 'TN Mising HCPS for TN IC';