
COPY /*11360068829*/ teva_ingestion.EXT_INTEGRAL_AD_SCIENCE_src FROM VERTICA teva.teva_ingestion.EXT_INTEGRAL_AD_SCIENCE_src;
COPY /*24622163005*/ teva_ingestion.EXT_IMS_FIA_FACT_V2_src FROM VERTICA teva.teva_ingestion.EXT_IMS_FIA_FACT_V2_src;
DISCONNECT teva;