
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.IMS ID ISSUES_AJOVY10262020) where table_schema = 'sandbox' and table_name = 'IMS ID ISSUES_AJOVY10262020';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.KNIPPER QVARs IDs1033) where table_schema = 'sandbox' and table_name = 'KNIPPER QVARs IDs1033';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.Returns_IQVIA ) where table_schema = 'sandbox' and table_name = 'Returns_IQVIA ';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.MediCal HCPs) where table_schema = 'sandbox' and table_name = 'MediCal HCPs';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.QNASL_MRKT IMSID_ALL) where table_schema = 'sandbox' and table_name = 'QNASL_MRKT IMSID_ALL';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.SYNEOS TERRs MISSING IMS IDs) where table_schema = 'sandbox' and table_name = 'SYNEOS TERRs MISSING IMS IDs';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.SYNEOS MISSING IMSIDs) where table_schema = 'sandbox' and table_name = 'SYNEOS MISSING IMSIDs';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.digital-affinity) where table_schema = 'sandbox' and table_name = 'digital-affinity';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.IQVIA OPTUM OUTLETS11032020) where table_schema = 'sandbox' and table_name = 'IQVIA OPTUM OUTLETS11032020';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.TN Mising HCPS for TN IC) where table_schema = 'sandbox' and table_name = 'TN Mising HCPS for TN IC';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.IMS ID ISSUE_AUSTEDO_10262020) where table_schema = 'sandbox' and table_name = 'IMS ID ISSUE_AUSTEDO_10262020';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.MA Missing STATE) where table_schema = 'sandbox' and table_name = 'MA Missing STATE';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.SYNEOS TARGET FILE) where table_schema = 'sandbox' and table_name = 'SYNEOS TARGET FILE';
update migration.audit set export_ts = sysdate(), export_success = true, export_type = 'V2V', tgt_row_count = (select count(*) from sandbox.J_CHUNG_HCP DEA-2) where table_schema = 'sandbox' and table_name = 'J_CHUNG_HCP DEA-2';