
COPY /*8*/ CUSTOMER_ORA.VENDOR FROM VERTICA teva.CUSTOMER_ORA.VENDOR;
COPY /*38*/ CUSTOMER_ORA.MARKET FROM VERTICA teva.CUSTOMER_ORA.MARKET;
COPY /*158*/ CUSTOMER_ORA.PRODUCT_NDC FROM VERTICA teva.CUSTOMER_ORA.PRODUCT_NDC;
COPY /*658*/ CUSTOMER_ORA.PRODUCT_PRICE FROM VERTICA teva.CUSTOMER_ORA.PRODUCT_PRICE;
COPY /*1258*/ CUSTOMER_ORA.MARKET_PRODUCT FROM VERTICA teva.CUSTOMER_ORA.MARKET_PRODUCT;
COPY /*1392*/ CUSTOMER_ORA.PRODUCT FROM VERTICA teva.CUSTOMER_ORA.PRODUCT;