CONNECT TO VERTICA teva USER dbadmin PASSWORD '360teva360' ON '10.5.10.15' , 5433;
COPY mdm.hcp_teva_flag FROM VERTICA teva.mdm.hcp_teva_flag;
COPY mdm.hco_teva_flag FROM VERTICA teva.mdm.hco_teva_flag;
COPY mdm.alternate_name FROM VERTICA teva.mdm.alternate_name;
COPY mdm.hco FROM VERTICA teva.mdm.hco;
COPY mdm.source_details FROM VERTICA teva.mdm.source_details;
COPY mdm.raw_dea FROM VERTICA teva.mdm.raw_dea;
COPY mdm.raw_npi FROM VERTICA teva.mdm.raw_npi;
COPY mdm.dea_address FROM VERTICA teva.mdm.dea_address;
COPY mdm.professional FROM VERTICA teva.mdm.professional;
COPY mdm.hcp FROM VERTICA teva.mdm.hcp;
COPY mdm.regulation FROM VERTICA teva.mdm.regulation;
COPY mdm.merges FROM VERTICA teva.mdm.merges;
COPY mdm.specialty FROM VERTICA teva.mdm.specialty;
COPY mdm.sample_eligibility FROM VERTICA teva.mdm.sample_eligibility;
COPY mdm.ims_flag FROM VERTICA teva.mdm.ims_flag;
COPY mdm.license FROM VERTICA teva.mdm.license;
COPY mdm.communication FROM VERTICA teva.mdm.communication;
COPY mdm.address_link FROM VERTICA teva.mdm.address_link;
COPY mdm.relationship FROM VERTICA teva.mdm.relationship;
COPY mdm.address FROM VERTICA teva.mdm.address;
COPY mdm.alternate_id FROM VERTICA teva.mdm.alternate_id;
DISCONNECT teva;
