CREATE RESOURCE POOL diuser_pool MEMORYSIZE '0%' MAXMEMORYSIZE '50%' EXECUTIONPARALLELISM AUTO PRIORITY 0 RUNTIMEPRIORITY MEDIUM RUNTIMEPRIORITYTHRESHOLD 2 QUEUETIMEOUT '00:05' PLANNEDCONCURRENCY AUTO CPUAFFINITYMODE ANY;
CREATE RESOURCE POOL tevauser_pool MEMORYSIZE '0%' MAXMEMORYSIZE '75%' EXECUTIONPARALLELISM AUTO PRIORITY 0 RUNTIMEPRIORITY MEDIUM RUNTIMEPRIORITYTHRESHOLD 2 QUEUETIMEOUT '00:05' PLANNEDCONCURRENCY AUTO CPUAFFINITYMODE ANY;
CREATE RESOURCE POOL small_pool MEMORYSIZE '4G' MAXMEMORYSIZE '50%' EXECUTIONPARALLELISM AUTO PRIORITY 0 RUNTIMEPRIORITY MEDIUM RUNTIMEPRIORITYTHRESHOLD 2 PLANNEDCONCURRENCY 1 CPUAFFINITYMODE ANY;
CREATE RESOURCE POOL large_pool MEMORYSIZE '8G' MAXMEMORYSIZE '50%' EXECUTIONPARALLELISM AUTO PRIORITY 0 RUNTIMEPRIORITY MEDIUM RUNTIMEPRIORITYTHRESHOLD 2 PLANNEDCONCURRENCY 1 CPUAFFINITYMODE ANY;
ALTER RESOURCE pool small_pool CASCADE TO large_pool; 
