-- metadata schmea stuff + extras

GRANT TRUNCATE ON metadata.validation_rules_mapping TO Databurst_Updt;
GRANT REFERENCES ON metadata.validation_rules_mapping TO Databurst_Updt;
GRANT DELETE ON metadata.validation_rules_mapping TO Databurst_Updt;
GRANT UPDATE ON metadata.validation_rules_mapping TO Databurst_Updt;
GRANT SELECT ON metadata.validation_rules_mapping TO Databurst_Updt;
GRANT INSERT ON metadata.validation_rules_mapping TO Databurst_Updt;
GRANT TRUNCATE ON metadata.validation_data_type_reference TO Databurst_Updt;
GRANT REFERENCES ON metadata.validation_data_type_reference TO Databurst_Updt;
GRANT DELETE ON metadata.validation_data_type_reference TO Databurst_Updt;
GRANT UPDATE ON metadata.validation_data_type_reference TO Databurst_Updt;
GRANT SELECT ON metadata.validation_data_type_reference TO Databurst_Updt;
GRANT INSERT ON metadata.validation_data_type_reference TO Databurst_Updt;
GRANT TRUNCATE ON metadata.valid_values TO Databurst_Updt;
GRANT REFERENCES ON metadata.valid_values TO Databurst_Updt;
GRANT DELETE ON metadata.valid_values TO Databurst_Updt;
GRANT UPDATE ON metadata.valid_values TO Databurst_Updt;
GRANT SELECT ON metadata.valid_values TO Databurst_Updt;
GRANT INSERT ON metadata.valid_values TO Databurst_Updt;
GRANT TRUNCATE ON metadata.log_files_purged TO Databurst_Updt;
GRANT REFERENCES ON metadata.log_files_purged TO Databurst_Updt;
GRANT DELETE ON metadata.log_files_purged TO Databurst_Updt;
GRANT UPDATE ON metadata.log_files_purged TO Databurst_Updt;
GRANT SELECT ON metadata.log_files_purged TO Databurst_Updt;
GRANT INSERT ON metadata.log_files_purged TO Databurst_Updt;
GRANT TRUNCATE ON metadata.integration_mapping TO Databurst_Updt;
GRANT REFERENCES ON metadata.integration_mapping TO Databurst_Updt;
GRANT DELETE ON metadata.integration_mapping TO Databurst_Updt;
GRANT UPDATE ON metadata.integration_mapping TO Databurst_Updt;
GRANT SELECT ON metadata.integration_mapping TO Databurst_Updt;
GRANT INSERT ON metadata.integration_mapping TO Databurst_Updt;
GRANT TRUNCATE ON metadata.file_status_reference TO Databurst_Updt;
GRANT REFERENCES ON metadata.file_status_reference TO Databurst_Updt;
GRANT DELETE ON metadata.file_status_reference TO Databurst_Updt;
GRANT UPDATE ON metadata.file_status_reference TO Databurst_Updt;
GRANT SELECT ON metadata.file_status_reference TO Databurst_Updt;
GRANT INSERT ON metadata.file_status_reference TO Databurst_Updt;
GRANT TRUNCATE ON metadata.data_file_metadata_bkp TO Databurst_Updt;
GRANT REFERENCES ON metadata.data_file_metadata_bkp TO Databurst_Updt;
GRANT DELETE ON metadata.data_file_metadata_bkp TO Databurst_Updt;
GRANT UPDATE ON metadata.data_file_metadata_bkp TO Databurst_Updt;
GRANT SELECT ON metadata.data_file_metadata_bkp TO Databurst_Updt;
GRANT INSERT ON metadata.data_file_metadata_bkp TO Databurst_Updt;
GRANT TRUNCATE ON metadata.workflow_steps TO Databurst_Updt;
GRANT REFERENCES ON metadata.workflow_steps TO Databurst_Updt;
GRANT DELETE ON metadata.workflow_steps TO Databurst_Updt;
GRANT UPDATE ON metadata.workflow_steps TO Databurst_Updt;
GRANT SELECT ON metadata.workflow_steps TO Databurst_Updt;
GRANT INSERT ON metadata.workflow_steps TO Databurst_Updt;
GRANT UPDATE ON metadata.log_job_events TO Databurst_Updt;
GRANT SELECT ON metadata.log_job_events TO Databurst_Updt;
GRANT INSERT ON metadata.log_job_events TO Databurst_Updt;
GRANT TRUNCATE ON metadata.log_data_validation_errors TO Databurst_Updt;
GRANT REFERENCES ON metadata.log_data_validation_errors TO Databurst_Updt;
GRANT DELETE ON metadata.log_data_validation_errors TO Databurst_Updt;
GRANT UPDATE ON metadata.log_data_validation_errors TO Databurst_Updt;
GRANT SELECT ON metadata.log_data_validation_errors TO Databurst_Updt;
GRANT INSERT ON metadata.log_data_validation_errors TO Databurst_Updt;
GRANT TRUNCATE ON metadata.event_type_reference TO Databurst_Updt;
GRANT REFERENCES ON metadata.event_type_reference TO Databurst_Updt;
GRANT DELETE ON metadata.event_type_reference TO Databurst_Updt;
GRANT UPDATE ON metadata.event_type_reference TO Databurst_Updt;
GRANT SELECT ON metadata.event_type_reference TO Databurst_Updt;
GRANT INSERT ON metadata.event_type_reference TO Databurst_Updt;
GRANT TRUNCATE ON metadata.data_file_metadata TO Databurst_Updt;
GRANT REFERENCES ON metadata.data_file_metadata TO Databurst_Updt;
GRANT DELETE ON metadata.data_file_metadata TO Databurst_Updt;
GRANT UPDATE ON metadata.data_file_metadata TO Databurst_Updt;
GRANT SELECT ON metadata.data_file_metadata TO Databurst_Updt;
GRANT INSERT ON metadata.data_file_metadata TO Databurst_Updt;
GRANT TRUNCATE ON metadata.data_feed_version_metadata TO Databurst_Updt;
GRANT REFERENCES ON metadata.data_feed_version_metadata TO Databurst_Updt;
GRANT DELETE ON metadata.data_feed_version_metadata TO Databurst_Updt;
GRANT UPDATE ON metadata.data_feed_version_metadata TO Databurst_Updt;
GRANT SELECT ON metadata.data_feed_version_metadata TO Databurst_Updt;
GRANT INSERT ON metadata.data_feed_version_metadata TO Databurst_Updt;
GRANT TRUNCATE ON metadata.data_feed_metadata TO Databurst_Updt;
GRANT REFERENCES ON metadata.data_feed_metadata TO Databurst_Updt;
GRANT DELETE ON metadata.data_feed_metadata TO Databurst_Updt;
GRANT UPDATE ON metadata.data_feed_metadata TO Databurst_Updt;
GRANT SELECT ON metadata.data_feed_metadata TO Databurst_Updt;
GRANT INSERT ON metadata.data_feed_metadata TO Databurst_Updt;
ALTER TABLE metadata.tmp_DSC_debug OWNER TO Databurst_Updt;
ALTER TABLE sandbox.data_feed_metadata_bkp OWNER TO Databurst_Updt;
GRANT TRUNCATE ON metadata.tmp_DSC_debug TO Databurst_Updt WITH GRANT OPTION;
GRANT REFERENCES ON metadata.tmp_DSC_debug TO Databurst_Updt WITH GRANT OPTION;
GRANT DELETE ON metadata.tmp_DSC_debug TO Databurst_Updt WITH GRANT OPTION;
GRANT UPDATE ON metadata.tmp_DSC_debug TO Databurst_Updt WITH GRANT OPTION;
GRANT SELECT ON metadata.tmp_DSC_debug TO Databurst_Updt WITH GRANT OPTION;
GRANT INSERT ON metadata.tmp_DSC_debug TO Databurst_Updt WITH GRANT OPTION;
GRANT DELETE ON metadata.python_lock TO Databurst_Updt;
GRANT UPDATE ON metadata.python_lock TO Databurst_Updt;
GRANT SELECT ON metadata.python_lock TO Databurst_Updt;
GRANT INSERT ON metadata.python_lock TO Databurst_Updt;
GRANT TRUNCATE ON metadata.misc_settings_reference TO Databurst_Updt;
GRANT REFERENCES ON metadata.misc_settings_reference TO Databurst_Updt;
GRANT DELETE ON metadata.misc_settings_reference TO Databurst_Updt;
GRANT UPDATE ON metadata.misc_settings_reference TO Databurst_Updt;
GRANT SELECT ON metadata.misc_settings_reference TO Databurst_Updt;
GRANT INSERT ON metadata.misc_settings_reference TO Databurst_Updt;
GRANT TRUNCATE ON metadata.log_configuration_validation_errors TO Databurst_Updt;
GRANT REFERENCES ON metadata.log_configuration_validation_errors TO Databurst_Updt;
GRANT DELETE ON metadata.log_configuration_validation_errors TO Databurst_Updt;
GRANT UPDATE ON metadata.log_configuration_validation_errors TO Databurst_Updt;
GRANT SELECT ON metadata.log_configuration_validation_errors TO Databurst_Updt;
GRANT INSERT ON metadata.log_configuration_validation_errors TO Databurst_Updt;
GRANT TRUNCATE ON metadata.fileclass_feedid_ver_xref TO Databurst_Updt;
GRANT REFERENCES ON metadata.fileclass_feedid_ver_xref TO Databurst_Updt;
GRANT DELETE ON metadata.fileclass_feedid_ver_xref TO Databurst_Updt;
GRANT UPDATE ON metadata.fileclass_feedid_ver_xref TO Databurst_Updt;
GRANT SELECT ON metadata.fileclass_feedid_ver_xref TO Databurst_Updt;
GRANT INSERT ON metadata.fileclass_feedid_ver_xref TO Databurst_Updt;
GRANT TRUNCATE ON metadata.error_code_reference TO Databurst_Updt;
GRANT REFERENCES ON metadata.error_code_reference TO Databurst_Updt;
GRANT DELETE ON metadata.error_code_reference TO Databurst_Updt;
GRANT UPDATE ON metadata.error_code_reference TO Databurst_Updt;
GRANT SELECT ON metadata.error_code_reference TO Databurst_Updt;
GRANT INSERT ON metadata.error_code_reference TO Databurst_Updt;
GRANT TRUNCATE ON metadata.data_file_metadata_prepurge TO Databurst_Updt;
GRANT REFERENCES ON metadata.data_file_metadata_prepurge TO Databurst_Updt;
GRANT DELETE ON metadata.data_file_metadata_prepurge TO Databurst_Updt;
GRANT UPDATE ON metadata.data_file_metadata_prepurge TO Databurst_Updt;
GRANT SELECT ON metadata.data_file_metadata_prepurge TO Databurst_Updt;
GRANT INSERT ON metadata.data_file_metadata_prepurge TO Databurst_Updt;
GRANT TRUNCATE ON metadata.data_file_metadata_postpurge TO Databurst_Updt;
GRANT REFERENCES ON metadata.data_file_metadata_postpurge TO Databurst_Updt;
GRANT DELETE ON metadata.data_file_metadata_postpurge TO Databurst_Updt;
GRANT UPDATE ON metadata.data_file_metadata_postpurge TO Databurst_Updt;
GRANT SELECT ON metadata.data_file_metadata_postpurge TO Databurst_Updt;
GRANT INSERT ON metadata.data_file_metadata_postpurge TO Databurst_Updt;
GRANT TRUNCATE ON metadata.data_feed_version_validation_rules TO Databurst_Updt;
GRANT REFERENCES ON metadata.data_feed_version_validation_rules TO Databurst_Updt;
GRANT DELETE ON metadata.data_feed_version_validation_rules TO Databurst_Updt;
GRANT UPDATE ON metadata.data_feed_version_validation_rules TO Databurst_Updt;
GRANT SELECT ON metadata.data_feed_version_validation_rules TO Databurst_Updt;
GRANT INSERT ON metadata.data_feed_version_validation_rules TO Databurst_Updt;

-- additional
grant all on cleansed.ims_mhj_qty_w to Databurst_Updt;
grant all on customer_master.tvcmid_xref to Databurst_Updt;
grant all on datamart.oncology_invoice_adjustments to Databurst_Updt;
grant all on datamart.prescriber_rx to Databurst_Updt;
grant all on datamart.specialty_pharmacy_shipment  to Databurst_Updt;
grant all on datamart.tvcmid_xref to Databurst_Updt;
grant all on integration.copay_detail_weekly to Databurst_Updt;
grant all on integration.prescriber_rx to Databurst_Updt;
grant all on mdm.address to Databurst_Updt;
grant all on metadata.id_lookup to Databurst_Updt;
grant all on metadata.log_job_events to Databurst_Updt;
grant all on metadata.workflow_command to Databurst_Updt;
grant all on metadata.workflow_process  to Databurst_Updt;
grant all on product.basket to Databurst_Updt;
grant all on product.source_product to Databurst_Updt;
grant all on sandbox.qc_table_stats to Databurst_Updt;
grant all on sequence metadata.job_id_sequence to Databurst_Updt;
grant all on sequence product.basket_id_seq to Databurst_Updt;
grant all on teva_ingestion.ims_mhj_qty_w to Databurst_Updt;
grant all on veeva.dsa_slide to Databurst_Updt;
grant all on veeva.ids_call_detail to Databurst_Updt;
grant all on veeva.v_product to Databurst_Updt;
grant usage on schema mdm to Databurst_Updt;


grant all on integration.copay_redemptions to Databurst_Updt;
grant all on reporting.product_item to Databurst_Updt;
grant all on reporting.sp_pre_call_summary to Databurst_Updt;
grant all on datamart.roster to Databurst_Updt;
grant all on integration.copay_redemptions to Databurst_Updt;
grant all on reporting.product_item to Databurst_Updt;
grant all on reporting.sp_pre_call_summary to Databurst_Updt;
grant all on veeva.v_key_message to Databurst_Updt;
grant all on sequence product.basket_id_seq to Databurst_Updt;
grant all on veeva.v_account to Databurst_Updt;
grant all on integration.specialty_pharmacy_shipment to Databurst_Updt;
grant all on reporting.rs_monthly_payer_geography_summary to Databurst_Updt;


grant all on reporting.rs_monthly_payer_geography_summary to Databurst_Updt;
grant all on datamart.customer_address to Databurst_Updt;
grant all on product.basket_item to Databurst_Updt;
grant all on reporting.product  to Databurst_Updt;
grant all on sequence product.basket_id_seq to Databurst_Updt;
grant all on datamart.specialty_pharmacy_shipment  to Databurst_Updt;
grant all on metadata.data_file_metadata  to Databurst_Updt;
grant all on reporting.sp_pre_call_summary  to Databurst_Updt;
grant all on reporting.sp_pre_call_summary_submarket  to Databurst_Updt;
grant all on reporting.sp_weekly_payer_prescriber_summary   to Databurst_Updt;
grant all on datamart.alternate_call_plans  to Databurst_Updt;
grant all on integration.call_plan  to Databurst_Updt;
grant all on reference.call_plan_active_dates  to Databurst_Updt;
grant all on datamart.current_alignment  to Databurst_Updt;
grant all on veeva.call  to Databurst_Updt;
grant all on datamart.oncology_invoice_adjustments  to Databurst_Updt;
grant all on integration.onc_sales_adjustment_load  to Databurst_Updt;
grant all on datamart.sfa_demographics  to Databurst_Updt;
grant all on integration.ddd_md  to Databurst_Updt;

--- 2022-05-18

grant all on datamart.customer_address_link to Databurst_Updt;
grant all on veeva.v_approved_document to Databurst_Updt;
grant all on sandbox.scd_roster to Databurst_Updt;
grant all on veeva.v_key_message to Databurst_Updt;
grant all on datamart.roster to Databurst_Updt;
grant all on veeva.v_ids_call to Databurst_Updt;
grant all on reference.oncology_account_id_ims_xref to Databurst_Updt;

grant all on integration.ddd  to Databurst_Updt;
grant all on reporting.roster  to Databurst_Updt;
grant all on veeva.call_sample to Databurst_Updt;
grant all on integration.ddd_md_demographics to Databurst_Updt;
grant all on integration.oncology_call_detail_goals to Databurst_Updt;
grant all on reporting.sp_monthly_payer_prescriber_summary to Databurst_Updt;
grant all on datamart.customer_hcp_demographics to Databurst_Updt;
grant all on reference.reporting_markets to Databurst_Updt;
grant all on datamart.customer_hco_demographics to Databurst_Updt;

---

grant all on reporting.sales_force_product to Databurst_Updt;
grant all on reporting.rs_pre_call_summary to Databurst_Updt;
grant all on datamart.event to Databurst_Updt;
grant all on datamart.call_plan to Databurst_Updt;
grant all on reference.designations  to Databurst_Updt;
grant all on reporting.sales_force_product to Databurst_Updt;
grant all on reference.reporting_market_sales_force to Databurst_Updt;
grant all on product.normalization_factor to Databurst_Updt;
grant all on reporting.payer_mapping to Databurst_Updt;
grant all on reporting.rs_pre_call_summary to Databurst_Updt;


datamart.customer_level_flags
sandbox.scd_sales_geography
 
 truncate table metadata.python_lock;

