CONNECT TO VERTICA teva USER dbadmin PASSWORD '360teva360' ON '10.5.10.15' , 5433;
COPY /*568*/ customer_master.teva_flag FROM VERTICA teva.customer_master.teva_flag;
COPY /*1168677*/ customer_master.customer_flags FROM VERTICA teva.customer_master.customer_flags;
COPY /*1915784*/ customer_master.hco_demo FROM VERTICA teva.customer_master.hco_demo;
COPY /*3213358*/ customer_master.raw_dea FROM VERTICA teva.customer_master.raw_dea;
COPY /*6094136*/ customer_master.hcp_demo FROM VERTICA teva.customer_master.hcp_demo;
COPY /*6431624*/ customer_master.hcp_detail FROM VERTICA teva.customer_master.hcp_detail;
COPY /*6687206*/ customer_master.tvcmid_merges FROM VERTICA teva.customer_master.tvcmid_merges;
COPY /*9307914*/ customer_master.sample_eligibility FROM VERTICA teva.customer_master.sample_eligibility;
COPY /*12202072*/ customer_master.ims_flag FROM VERTICA teva.customer_master.ims_flag;
COPY /*39399218*/ customer_master.alternate_identifier FROM VERTICA teva.customer_master.alternate_identifier;
COPY /*40608094*/ customer_master.tvcmid_xref FROM VERTICA teva.customer_master.tvcmid_xref;
DISCONNECT teva;
