CREATE AUTHENTICATION v_dbadmin_hash METHOD 'HASH' HOST '0.0.0.0/0';
CREATE AUTHENTICATION v_ldap_teva METHOD 'LDAP' HOST '0.0.0.0/0';
CREATE AUTHENTICATION v_ldap_f360 METHOD 'LDAP' HOST '0.0.0.0/0';
CREATE AUTHENTICATION v_ldap_teva_corp_domain METHOD 'LDAP' HOST '0.0.0.0/0';
CREATE AUTHENTICATION v_dbadmin_trust METHOD 'TRUST' LOCAL;
ALTER AUTHENTICATION v_dbadmin_hash PRIORITY 10000;
ALTER AUTHENTICATION v_ldap_teva PRIORITY 0;
ALTER AUTHENTICATION v_ldap_f360 PRIORITY 0;
ALTER AUTHENTICATION v_ldap_teva_corp_domain PRIORITY 0;
ALTER AUTHENTICATION v_dbadmin_trust PRIORITY 10000;
ALTER AUTHENTICATION v_dbadmin_hash ENABLE;
ALTER AUTHENTICATION v_ldap_teva ENABLE;
ALTER AUTHENTICATION v_ldap_f360 ENABLE;
ALTER AUTHENTICATION v_ldap_teva_corp_domain ENABLE;
ALTER AUTHENTICATION v_dbadmin_trust ENABLE;
ALTER AUTHENTICATION v_ldap_teva SET host = 'ldaps://ldap.teva.gsm:3269/search';
ALTER AUTHENTICATION v_ldap_teva SET basedn = 'dc=NA,dc=Teva,dc=Corp';
ALTER AUTHENTICATION v_ldap_teva SET binddn = 'cn=Admldap Vertica02,ou=TECH,ou=NOW,dc=NA,dc=Teva,dc=Corp';
ALTER AUTHENTICATION v_ldap_teva SET bind_password = '93,#[\~&p42T4gG@';
ALTER AUTHENTICATION v_ldap_teva SET search_attribute = 'sAMAccountName';
ALTER AUTHENTICATION v_ldap_teva SET tls_reqcert = 'never';
ALTER AUTHENTICATION v_ldap_f360 SET host = 'ldaps://ldap.dir.full360.com';
ALTER AUTHENTICATION v_ldap_f360 SET basedn = 'dc=dir,dc=full360,dc=com';
ALTER AUTHENTICATION v_ldap_f360 SET binddn = 'CN=BindReadOnly,CN=Users,DC=dir,DC=full360,DC=com';
ALTER AUTHENTICATION v_ldap_f360 SET bind_password = 'np6WPoe5v9tgTbQGS3D53q1W6GITij';
ALTER AUTHENTICATION v_ldap_f360 SET search_attribute = 'sAMAccountName';
ALTER AUTHENTICATION v_ldap_f360 SET tls_reqcert = 'never';
ALTER AUTHENTICATION v_ldap_teva_corp_domain SET host = 'ldaps://ldap.teva.gsm:3269/search';
ALTER AUTHENTICATION v_ldap_teva_corp_domain SET basedn = 'dc=Teva,dc=Corp';
ALTER AUTHENTICATION v_ldap_teva_corp_domain SET binddn = 'cn=Admldap Vertica02,ou=TECH,ou=NOW,dc=NA,dc=Teva,dc=Corp';
ALTER AUTHENTICATION v_ldap_teva_corp_domain SET bind_password = '93,#[\~&p42T4gG@';
ALTER AUTHENTICATION v_ldap_teva_corp_domain SET search_attribute = 'sAMAccountName';
ALTER AUTHENTICATION v_ldap_teva_corp_domain SET tls_reqcert = 'never';
GRANT AUTHENTICATION v_ldap_teva TO jstruthe;
GRANT AUTHENTICATION v_ldap_teva TO mlundt;
GRANT AUTHENTICATION v_ldap_teva TO ehalabe;
GRANT AUTHENTICATION v_ldap_teva TO BEinersen;
GRANT AUTHENTICATION v_ldap_teva TO jchung;
GRANT AUTHENTICATION v_dbadmin_hash TO bfages;
GRANT AUTHENTICATION v_dbadmin_hash TO ppatel40;
GRANT AUTHENTICATION v_dbadmin_hash TO snandan;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO yzhao03;
GRANT AUTHENTICATION v_dbadmin_hash TO cdw_rpa;
GRANT AUTHENTICATION v_dbadmin_hash TO sqlpad;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO psingh22;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_TevaDataSuperUser;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_HPSDevOpsUser;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_DataIntegration;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_CDWAdmin;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_DataburstUpdateUser;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_ONCADJ_ADMIN;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_TableauUser;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_TevaITUser;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_InboundETLUser;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_ProductAdmin;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_TevaMDMUser;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_TevaBusinessUser;
GRANT AUTHENTICATION v_dbadmin_hash TO impersonation_ITDevOpsUser;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO spatkar;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO csebor;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO vswamy01;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO aalvarez;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO aswaminath;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO syengalwar01;
GRANT AUTHENTICATION v_dbadmin_hash TO ecs;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO tmitrev;
GRANT AUTHENTICATION v_dbadmin_hash TO denodo_cdw_user;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO smidwinter;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO mbhawsar;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO rmewada;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO rghosh02;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO mgupta11;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO jnellore;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO rmedina09;
GRANT AUTHENTICATION v_dbadmin_hash TO dbadmin;
GRANT AUTHENTICATION v_ldap_teva TO public;
GRANT AUTHENTICATION v_dbadmin_hash TO teva_user;
GRANT AUTHENTICATION v_dbadmin_hash TO moshaughnessy;
GRANT AUTHENTICATION v_dbadmin_hash TO pseudosuperuser;
GRANT AUTHENTICATION v_ldap_teva TO teva_user;
GRANT AUTHENTICATION v_dbadmin_hash TO qa_user;
GRANT AUTHENTICATION v_ldap_teva TO mramsuesmi;
GRANT AUTHENTICATION v_dbadmin_hash TO gobrien01;
GRANT AUTHENTICATION v_ldap_teva TO dwhite03;
GRANT AUTHENTICATION v_dbadmin_hash TO MCM_Tableau;
GRANT AUTHENTICATION v_ldap_teva TO nwright02;
GRANT AUTHENTICATION v_ldap_teva TO ksinclai;
GRANT AUTHENTICATION v_dbadmin_hash TO CDW_EXTRACT;
GRANT AUTHENTICATION v_dbadmin_hash TO rashmiraj;
GRANT AUTHENTICATION v_dbadmin_hash TO rkrutsic_nl;
GRANT AUTHENTICATION v_dbadmin_hash TO SalesOps;
GRANT AUTHENTICATION v_dbadmin_hash TO tableau_user;
GRANT AUTHENTICATION v_ldap_teva TO gattili02;
GRANT AUTHENTICATION v_dbadmin_hash TO ITAdhoc;
GRANT AUTHENTICATION v_dbadmin_hash TO Marketacc;
GRANT AUTHENTICATION v_dbadmin_hash TO FieldOps;
GRANT AUTHENTICATION v_ldap_teva TO aschmidt;
GRANT AUTHENTICATION v_ldap_teva TO cmeyer;
GRANT AUTHENTICATION v_ldap_teva TO pwilson;
GRANT AUTHENTICATION v_ldap_teva TO gmartin;
GRANT AUTHENTICATION v_ldap_teva TO nreigel02;
GRANT AUTHENTICATION v_ldap_teva TO cdigiacomo;
GRANT AUTHENTICATION v_ldap_teva TO tokeefe;
GRANT AUTHENTICATION v_ldap_teva TO AWANG02;
GRANT AUTHENTICATION v_ldap_teva TO asudhaka;
GRANT AUTHENTICATION v_ldap_teva TO dconklin;
GRANT AUTHENTICATION v_ldap_f360 TO rohit.amarnath;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO kgantenapa01;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO dpence;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO rgopaluni01;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO yagarwal;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO akashyap;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO rbansal01;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO kdutta04;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO ubhaskaran;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO wroszkowsk;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO jtucker01;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO vrao;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO tjoshi01;
GRANT AUTHENTICATION v_dbadmin_trust TO dbadmin;
GRANT AUTHENTICATION v_dbadmin_hash TO di_user;
GRANT AUTHENTICATION v_dbadmin_hash TO CDW_User;
GRANT AUTHENTICATION v_ldap_teva TO abrennan;
GRANT AUTHENTICATION v_ldap_teva TO adong01;
GRANT AUTHENTICATION v_ldap_teva TO agokhman;
GRANT AUTHENTICATION v_ldap_teva TO cmchenry;
GRANT AUTHENTICATION v_ldap_teva TO cstoeben;
GRANT AUTHENTICATION v_ldap_teva TO cwilliam05;
GRANT AUTHENTICATION v_ldap_teva TO dluscomb;
GRANT AUTHENTICATION v_ldap_teva TO eaquino;
GRANT AUTHENTICATION v_ldap_teva TO ejiang;
GRANT AUTHENTICATION v_ldap_teva TO ekane;
GRANT AUTHENTICATION v_ldap_teva TO gmwhite;
GRANT AUTHENTICATION v_ldap_teva TO hmohamma;
GRANT AUTHENTICATION v_ldap_teva TO jmorrow;
GRANT AUTHENTICATION v_ldap_teva TO jpeng01;
GRANT AUTHENTICATION v_ldap_teva TO jrizzo;
GRANT AUTHENTICATION v_ldap_teva TO kbixler;
GRANT AUTHENTICATION v_ldap_teva TO Kscarani;
GRANT AUTHENTICATION v_ldap_teva TO nreigel;
GRANT AUTHENTICATION v_ldap_teva TO nshanfelt;
GRANT AUTHENTICATION v_ldap_teva TO pmanto;
GRANT AUTHENTICATION v_ldap_teva TO rkrutsic;
GRANT AUTHENTICATION v_ldap_teva TO rmotley;
GRANT AUTHENTICATION v_ldap_teva TO rrajendr;
GRANT AUTHENTICATION v_ldap_teva TO rweinsch;
GRANT AUTHENTICATION v_ldap_teva TO smcnulty02;
GRANT AUTHENTICATION v_ldap_teva TO sthomas1;
GRANT AUTHENTICATION v_ldap_teva TO tmoore02;
GRANT AUTHENTICATION v_ldap_teva TO tryan01;
GRANT AUTHENTICATION v_dbadmin_hash TO CDW_Reporting;
GRANT AUTHENTICATION v_dbadmin_hash TO Databurst_Updt;
GRANT AUTHENTICATION v_dbadmin_hash TO CDW_Admin;
GRANT AUTHENTICATION v_dbadmin_hash TO MDM_ETL;
GRANT AUTHENTICATION v_ldap_teva TO harli;
GRANT AUTHENTICATION v_dbadmin_hash TO prathaps;
GRANT AUTHENTICATION v_ldap_teva TO smukku;
GRANT AUTHENTICATION v_ldap_teva TO jsteadman;
GRANT AUTHENTICATION v_ldap_teva TO lshelton;
GRANT AUTHENTICATION v_ldap_teva TO jmayhew;
GRANT AUTHENTICATION v_ldap_teva TO kerker;
GRANT AUTHENTICATION v_ldap_teva TO tkeys;
GRANT AUTHENTICATION v_ldap_teva TO cmason01;
GRANT AUTHENTICATION v_ldap_teva TO alarkins;
GRANT AUTHENTICATION v_ldap_teva TO dallen04;
GRANT AUTHENTICATION v_ldap_teva TO twhalen;
GRANT AUTHENTICATION v_ldap_teva TO mcapehar;
GRANT AUTHENTICATION v_ldap_teva TO boberkro;
GRANT AUTHENTICATION v_ldap_teva TO mfletcher01;
GRANT AUTHENTICATION v_ldap_teva TO jbutler01;
GRANT AUTHENTICATION v_ldap_teva TO bkoziol;
GRANT AUTHENTICATION v_ldap_teva TO twoltkam;
GRANT AUTHENTICATION v_ldap_teva TO egunders;
GRANT AUTHENTICATION v_ldap_teva TO akramer;
GRANT AUTHENTICATION v_dbadmin_hash TO m_habeeb;
GRANT AUTHENTICATION v_ldap_teva TO MKHAN14;
GRANT AUTHENTICATION v_dbadmin_hash TO kavyag;
GRANT AUTHENTICATION v_dbadmin_hash TO integration_user;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO ksubramani03;
GRANT AUTHENTICATION v_ldap_teva_corp_domain TO abhansali;
GRANT AUTHENTICATION v_dbadmin_hash TO ma_tableau_user;
GRANT AUTHENTICATION v_dbadmin_hash TO ONCADJ;
GRANT AUTHENTICATION v_ldap_teva TO jsmith11;
GRANT AUTHENTICATION v_dbadmin_hash TO cchalla;
GRANT AUTHENTICATION v_ldap_teva TO kgantenapa;
GRANT AUTHENTICATION v_ldap_teva TO mvvergar;
GRANT AUTHENTICATION v_dbadmin_hash TO ProductAdminUser;
GRANT AUTHENTICATION v_dbadmin_hash TO hdyer;
GRANT AUTHENTICATION v_dbadmin_hash TO chriskim;
GRANT AUTHENTICATION v_dbadmin_hash TO jonahuy;
GRANT AUTHENTICATION v_dbadmin_hash TO mophif;
GRANT AUTHENTICATION v_ldap_teva TO tmcdowel;
GRANT AUTHENTICATION v_ldap_teva TO ccompton;
GRANT AUTHENTICATION v_ldap_teva TO sramamur;
