delete from migration.audit
 where
table_name in  ('IMS ID ISSUE_AUSTEDO_10262020'
,'MA Missing STATE'
,'SYNEOS TARGET FILE'
,'J_CHUNG_HCP DEA-2'
,'SYNEOS TERRs MISSING IMS IDs'
,'SYNEOS MISSING IMSIDs'
,'digital-affinity'
,'IMS ID ISSUES_AJOVY10262020'
,'KNIPPER QVARs IDs1033'
,'Returns_IQVIA '
,'MediCal HCPs'
,'QNASL_MRKT IMSID_ALL'
,'IQVIA OPTUM OUTLETS11032020'
,'TN Mising HCPS for TN IC');

delete from migration.audit_history
 where
table_name in  ('IMS ID ISSUE_AUSTEDO_10262020'
,'MA Missing STATE'
,'SYNEOS TARGET FILE'
,'J_CHUNG_HCP DEA-2'
,'SYNEOS TERRs MISSING IMS IDs'
,'SYNEOS MISSING IMSIDs'
,'digital-affinity'
,'IMS ID ISSUES_AJOVY10262020'
,'KNIPPER QVARs IDs1033'
,'Returns_IQVIA '
,'MediCal HCPs'
,'QNASL_MRKT IMSID_ALL'
,'IQVIA OPTUM OUTLETS11032020'
,'TN Mising HCPS for TN IC');

delete from migration.source_schemas
 where
table_name in  ('IMS ID ISSUE_AUSTEDO_10262020'
,'MA Missing STATE'
,'SYNEOS TARGET FILE'
,'J_CHUNG_HCP DEA-2'
,'SYNEOS TERRs MISSING IMS IDs'
,'SYNEOS MISSING IMSIDs'
,'digital-affinity'
,'IMS ID ISSUES_AJOVY10262020'
,'KNIPPER QVARs IDs1033'
,'Returns_IQVIA '
,'MediCal HCPs'
,'QNASL_MRKT IMSID_ALL'
,'IQVIA OPTUM OUTLETS11032020'
,'TN Mising HCPS for TN IC');