CONNECT TO VERTICA teva USER dbadmin PASSWORD '360teva360' ON '10.5.10.15' , 5433;
COPY payerspine.mb_test FROM VERTICA teva.payerspine.mb_test;
COPY payerspine.PS_PROVIDER_OVERRIDE_DEFAULT_V01 FROM VERTICA teva.payerspine.PS_PROVIDER_OVERRIDE_DEFAULT_V01;
COPY payerspine.PS_KEY_CONTROLLER_LIST_V01 FROM VERTICA teva.payerspine.PS_KEY_CONTROLLER_LIST_V01;
COPY payerspine.ftf_health_plans_6mofiles FROM VERTICA teva.payerspine.ftf_health_plans_6mofiles;
COPY payerspine.ftf_formularies_6mofiles FROM VERTICA teva.payerspine.ftf_formularies_6mofiles;
COPY payerspine.ftf_pbms_6mofiles FROM VERTICA teva.payerspine.ftf_pbms_6mofiles;
COPY payerspine.mc_wb_new_view_6mofiles FROM VERTICA teva.payerspine.mc_wb_new_view_6mofiles;
COPY payerspine.mc_wb_pbm_plans_6mofiles FROM VERTICA teva.payerspine.mc_wb_pbm_plans_6mofiles;
COPY payerspine.ftf_restrictions_v2_6mofiles FROM VERTICA teva.payerspine.ftf_restrictions_v2_6mofiles;
COPY payerspine.ftf_ims_bridge_6mofiles FROM VERTICA teva.payerspine.ftf_ims_bridge_6mofiles;
COPY payerspine.ftf_health_plan_geography_6mofiles FROM VERTICA teva.payerspine.ftf_health_plan_geography_6mofiles;
DISCONNECT teva;
