CREATE RESOURCE POOL diuser_pool MEMORYSIZE '0%' MAXMEMORYSIZE '50%' EXECUTIONPARALLELISM AUTO PRIORITY 0 RUNTIMEPRIORITY MEDIUM RUNTIMEPRIORITYTHRESHOLD 2 QUEUETIMEOUT '00:05' PLANNEDCONCURRENCY AUTO CPUAFFINITYMODE ANY;
CREATE RESOURCE POOL superset_pool MEMORYSIZE '15G' EXECUTIONPARALLELISM AUTO PRIORITY 0 RUNTIMEPRIORITY MEDIUM RUNTIMEPRIORITYTHRESHOLD 2 QUEUETIMEOUT '00:05' PLANNEDCONCURRENCY AUTO CPUAFFINITYMODE ANY;
CREATE RESOURCE POOL tevauser_pool MEMORYSIZE '0%' MAXMEMORYSIZE '75%' EXECUTIONPARALLELISM AUTO PRIORITY 0 RUNTIMEPRIORITY MEDIUM RUNTIMEPRIORITYTHRESHOLD 2 QUEUETIMEOUT '00:05' PLANNEDCONCURRENCY AUTO CPUAFFINITYMODE ANY;
ALTER RESOURCE POOL recovery MAXCONCURRENCY '5';
ALTER RESOURCE POOL refresh PLANNEDCONCURRENCY 4;
ALTER RESOURCE POOL tm MEMORYSIZE '7G';
