CONNECT TO VERTICA teva USER dbadmin PASSWORD '360teva360' ON '10.5.10.15' , 5433;
COPY /*180*/ sfa_history.s_med_spec FROM VERTICA teva.sfa_history.s_med_spec;
COPY /*416*/ sfa_history.s_prod_int FROM VERTICA teva.sfa_history.s_prod_int;
COPY /*2182*/ sfa_history.s_postn FROM VERTICA teva.sfa_history.s_postn;
COPY /*139498*/ sfa_history.s_org_ext FROM VERTICA teva.sfa_history.s_org_ext;
COPY /*349392*/ sfa_history.s_contact_fnx FROM VERTICA teva.sfa_history.s_contact_fnx;
COPY /*351437*/ sfa_history.s_contact_x FROM VERTICA teva.sfa_history.s_contact_x;
COPY /*352253*/ sfa_history.s_contact FROM VERTICA teva.sfa_history.s_contact;
COPY /*414905*/ sfa_history.s_state_lic_ls FROM VERTICA teva.sfa_history.s_state_lic_ls;
COPY /*481370*/ sfa_history.s_postn_con FROM VERTICA teva.sfa_history.s_postn_con;
COPY /*633664*/ sfa_history.s_addr_per FROM VERTICA teva.sfa_history.s_addr_per;
COPY /*922128*/ sfa_history.s_con_addr FROM VERTICA teva.sfa_history.s_con_addr;
COPY /*1755137*/ sfa_history.s_act_prdint FROM VERTICA teva.sfa_history.s_act_prdint;
COPY /*4454264*/ sfa_history.s_evt_act FROM VERTICA teva.sfa_history.s_evt_act;
COPY /*6919604*/ sfa_history.s_act_prod_appl FROM VERTICA teva.sfa_history.s_act_prod_appl;
DISCONNECT teva;
