CONNECT TO VERTICA teva USER dbadmin PASSWORD '360teva360' ON '10.5.10.15' , 5433;
COPY /*2*/ payerspine.mb_test FROM VERTICA teva.payerspine.mb_test;
COPY /*5084*/ payerspine.PS_PROVIDER_OVERRIDE_DEFAULT_V01 FROM VERTICA teva.payerspine.PS_PROVIDER_OVERRIDE_DEFAULT_V01;
COPY /*10464*/ payerspine.PS_KEY_CONTROLLER_LIST_V01 FROM VERTICA teva.payerspine.PS_KEY_CONTROLLER_LIST_V01;
COPY /*60558*/ payerspine.ftf_health_plans_6mofiles FROM VERTICA teva.payerspine.ftf_health_plans_6mofiles;
COPY /*181676*/ payerspine.ftf_formularies_6mofiles FROM VERTICA teva.payerspine.ftf_formularies_6mofiles;
COPY /*301994*/ payerspine.ftf_pbms_6mofiles FROM VERTICA teva.payerspine.ftf_pbms_6mofiles;
COPY /*555576*/ payerspine.mc_wb_new_view_6mofiles FROM VERTICA teva.payerspine.mc_wb_new_view_6mofiles;
COPY /*556618*/ payerspine.mc_wb_pbm_plans_6mofiles FROM VERTICA teva.payerspine.mc_wb_pbm_plans_6mofiles;
COPY /*1024172*/ payerspine.ftf_restrictions_v2_6mofiles FROM VERTICA teva.payerspine.ftf_restrictions_v2_6mofiles;
COPY /*1353094*/ payerspine.ftf_ims_bridge_6mofiles FROM VERTICA teva.payerspine.ftf_ims_bridge_6mofiles;
COPY /*22921546*/ payerspine.ftf_health_plan_geography_6mofiles FROM VERTICA teva.payerspine.ftf_health_plan_geography_6mofiles;
DISCONNECT teva;
