CREATE SCHEMA sfa_history;


CREATE TABLE sfa_history.STG_CM_ID_XREF
(
    CM_ID int,
    ID_NUM varchar(255),
    ID_TYPE varchar(10),
    VIA varchar(20)
);


CREATE TABLE sfa_history.s_contact_x
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    DCKING_NUM numeric(22,7),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    PAR_ROW_ID varchar(15),
    ATTRIB_08 char(1),
    ATTRIB_09 char(1),
    ATTRIB_10 char(1),
    ATTRIB_11 char(1),
    ATTRIB_12 timestamp,
    ATTRIB_13 timestamp,
    ATTRIB_14 numeric(22,7),
    ATTRIB_15 numeric(22,7),
    ATTRIB_16 numeric(22,7),
    ATTRIB_17 numeric(22,7),
    ATTRIB_18 numeric(22,7),
    ATTRIB_19 numeric(22,7),
    ATTRIB_20 numeric(22,7),
    ATTRIB_21 numeric(22,7),
    ATTRIB_22 numeric(22,7),
    ATTRIB_23 numeric(22,7),
    ATTRIB_24 numeric(22,7),
    ATTRIB_25 numeric(22,7),
    ATTRIB_26 timestamp,
    ATTRIB_27 timestamp,
    ATTRIB_28 timestamp,
    ATTRIB_29 timestamp,
    ATTRIB_30 timestamp,
    ATTRIB_31 timestamp,
    ATTRIB_32 timestamp,
    ATTRIB_33 timestamp,
    ATTRIB_01 varchar(100),
    ATTRIB_02 varchar(100),
    ATTRIB_03 varchar(30),
    ATTRIB_04 varchar(30),
    ATTRIB_05 varchar(30),
    ATTRIB_06 varchar(30),
    ATTRIB_07 varchar(30),
    ATTRIB_34 varchar(50),
    ATTRIB_35 varchar(50),
    ATTRIB_36 varchar(50),
    ATTRIB_37 varchar(50),
    ATTRIB_38 varchar(50),
    ATTRIB_39 varchar(50),
    ATTRIB_40 varchar(50),
    ATTRIB_41 varchar(50),
    ATTRIB_42 varchar(50),
    ATTRIB_43 varchar(50),
    ATTRIB_44 varchar(100),
    ATTRIB_45 varchar(100),
    ATTRIB_46 varchar(100),
    ATTRIB_47 varchar(255),
    ATTRIB_48 varchar(250),
    X_ATTRIB_49 varchar(15),
    X_ATTRIB_50 varchar(15),
    X_ATTRIB_51 varchar(15),
    X_ATTRIB_52 varchar(255),
    X_ATTRIB_53 varchar(255),
    X_ATTRIB_54 varchar(255),
    X_ATTRIB_55 varchar(255),
    X_ATTRIB_56 varchar(100),
    X_ATTRIB_57 varchar(100),
    X_ATTRIB_58 varchar(100),
    X_ATTRIB_59 varchar(50),
    X_ATTRIB_60 varchar(50),
    X_ATTRIB_61 varchar(50),
    X_ATTRIB_62 varchar(50),
    X_ATTRIB_64 timestamp,
    X_ATTRIB_65 timestamp,
    X_ATTRIB_66 timestamp,
    X_ATTRIB_67 timestamp,
    X_ATTRIB_68 numeric(22,7),
    X_ATTRIB_69 char(1),
    X_ATTRIB_70 char(1),
    X_ATTRIB_71 char(1),
    X_ATTRIB_72 varchar(30),
    X_ATTRIB_73 varchar(30),
    ATTRIB_49 varchar(100),
    ATTRIB_50 varchar(100),
    ATTRIB_51 varchar(100),
    ATTRIB_52 varchar(100),
    ATTRIB_53 varchar(100),
    ATTRIB_54 varchar(100),
    ATTRIB_55 varchar(100),
    ATTRIB_56 numeric(22,7),
    ATTRIB_57 numeric(22,7),
    ATTRIB_58 numeric(22,7),
    ATTRIB_59 numeric(22,7),
    ATTRIB_60 numeric(22,7),
    ATTRIB_61 numeric(22,7),
    ATTRIB_62 numeric(22,7),
    ATTRIB_63 numeric(22,7),
    ATTRIB_64 numeric(22,7),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    SUP_PRAC_ADD_ID varchar(50),
    SUP_PRAC_ID varchar(50),
    X_ATTRIB_74 char(1),
    COMPANY_MOBILE varchar(30),
    VM_BOX_NUMBER varchar(10),
    VM_MAIN varchar(30),
    X_ATTRIB_75 numeric(22,7),
    X_ATTRIB_76 numeric(22,7),
    X_ATTRIB_77 numeric(22,7),
    X_ATTRIB_78 numeric(22,7),
    X_ATTRIB_79 numeric(22,7),
    X_ATTRIB_80 varchar(255),
    X_ATTRIB_81 varchar(50),
    X_ATTRIB_82 char(1),
    X_ATTRIB_83 char(1),
    X_ATTRIB_84 timestamp,
    X_ATTRIB_85 timestamp
);


CREATE TABLE sfa_history.s_con_addr
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    ACTIVE_FLG char(1),
    ADDR_PER_ID varchar(15),
    BL_ADDR_FLG char(1),
    FRAUD_FLG char(1),
    MAIN_ADDR_FLG char(1),
    RELATION_TYPE_CD varchar(30),
    SHIP_ADDR_FLG char(1),
    DEA_EXPR_DT timestamp,
    END_DT timestamp,
    FRI_1ST_CLOSE_TM timestamp,
    FRI_1ST_OPEN_TM timestamp,
    FRI_2ND_CLOSE_TM timestamp,
    FRI_2ND_OPEN_TM timestamp,
    MON_1ST_CLOSE_TM timestamp,
    MON_1ST_OPEN_TM timestamp,
    MON_2ND_CLOSE_TM timestamp,
    MON_2ND_OPEN_TM timestamp,
    NUM_MONTHS_AT_ADDR numeric(10,0),
    SAT_1ST_CLOSE_TM timestamp,
    SAT_1ST_OPEN_TM timestamp,
    SAT_2ND_CLOSE_TM timestamp,
    SAT_2ND_OPEN_TM timestamp,
    START_DT timestamp,
    SUN_1ST_CLOSE_TM timestamp,
    SUN_1ST_OPEN_TM timestamp,
    SUN_2ND_CLOSE_TM timestamp,
    SUN_2ND_OPEN_TM timestamp,
    THU_1ST_CLOSE_TM timestamp,
    THU_1ST_OPEN_TM timestamp,
    THU_2ND_CLOSE_TM timestamp,
    THU_2ND_OPEN_TM timestamp,
    TUE_1ST_CLOSE_TM timestamp,
    TUE_1ST_OPEN_TM timestamp,
    TUE_2ND_CLOSE_TM timestamp,
    TUE_2ND_OPEN_TM timestamp,
    WED_1ST_CLOSE_TM timestamp,
    WED_1ST_OPEN_TM timestamp,
    WED_2ND_CLOSE_TM timestamp,
    WED_2ND_OPEN_TM timestamp,
    ACCNT_ID varchar(15),
    ADDR_MAIL_CD varchar(30),
    ADDR_TYPE_CD varchar(30),
    BRICK_ID varchar(15),
    BU_ID varchar(15),
    CONTACT_ID varchar(15),
    DEA_NUM varchar(30),
    DFLT_SHIP_PRIO_CD varchar(30),
    EMAIL_ADDR varchar(50),
    FAX_PH_NUM varchar(40),
    MAIL_TYPE_CD varchar(30),
    OCCUPANCY_CD varchar(30),
    ORG_GROUP_ID varchar(15),
    PH_NUM varchar(40),
    TRNSPRT_ZONE_CD varchar(30),
    X_ATTRIB_01 varchar(15),
    X_ATTRIB_02 varchar(15),
    X_ATTRIB_03 varchar(30),
    X_ATTRIB_04 varchar(50),
    X_ATTRIB_05 varchar(50),
    X_ATTRIB_06 varchar(100),
    X_ATTRIB_07 varchar(255),
    X_OK_TO_SAMPLE char(1),
    ADDRESSEE varchar(100),
    ALIGNMENT_FLG char(1),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    YEARLY_END_DT timestamp,
    YEARLY_START_DT timestamp,
    X_SRC_LAST_UPD timestamp
);


CREATE TABLE sfa_history.s_act_prod_appl
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    ACTIVITY_ID varchar(15),
    APPLCTN_CD varchar(30),
    PRDINT_ID varchar(15),
    PRIORITY_NUM numeric(10,0),
    PR_ISS_ID varchar(15),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    PROD_ALLOC_ID varchar(15),
    X_INTEGRATION_ID varchar(30),
    X_SRC_LAST_UPD timestamp
);


CREATE TABLE sfa_history.s_org_ext
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    DCKING_NUM numeric(22,7),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    PAR_ROW_ID varchar(15),
    ACCNT_FLG char(1),
    ACTIVE_FLG char(1),
    BUYING_GROUP_FLG char(1),
    BU_ID varchar(15),
    CG_DEDN_AUTH_FLG char(1),
    CG_SVP_A_LOCK_FLG char(1),
    CG_SVP_LOCK_FLG char(1),
    CG_SVP_SKIP_FLG char(1),
    CL_SITE_FLG char(1),
    COURT_PAY_FLG char(1),
    DISA_CLEANSE_FLG char(1),
    EVT_LOC_FLG char(1),
    FCST_ORG_FLG char(1),
    FUND_ELIG_FLG char(1),
    GOOD_STANDING_FLG char(1),
    INCL_FLG char(1),
    INT_ORG_FLG char(1),
    NAME varchar(100),
    PLAN_GROUP_FLG char(1),
    PROSPECT_FLG char(1),
    PRTNR_FLG char(1),
    PRTNR_PUBLISH_FLG char(1),
    RPLCD_WTH_CMPT_FLG char(1),
    SKIP_PO_CRDCHK_FLG char(1),
    AGENCY_FLG char(1),
    BRANCH_FLG char(1),
    BRIEFING_LAYOUT varchar(30),
    CLIENT_FLG char(1),
    ENTERPRISE_FLAG char(1),
    FACILITY_FLG char(1),
    INVSTR_FLG char(1),
    LANG_ID varchar(15),
    PR_REP_DNRM_FLG char(1),
    PR_REP_MANL_FLG char(1),
    PR_REP_SYS_FLG char(1),
    ASGN_DT timestamp,
    ASGN_USR_EXCLD_FLG char(1),
    ASSET_AMT numeric(22,7),
    ATM_COUNT numeric(10,0),
    AVAIL_CREDIT_AMT numeric(22,7),
    BILL_PBLSHR_FLG char(1),
    BO_ORDQRY_END_DT timestamp,
    BO_ORDQRY_START_DT timestamp,
    CG_CONS_END_OFFSET numeric(22,7),
    CG_CONS_STRTOFFSET numeric(22,7),
    CG_PRMO_END_OFFSET numeric(22,7),
    CG_SHIP_END_OFFSET numeric(22,7),
    CG_SHIP_STRTOFFSET numeric(22,7),
    CG_SVP_UPPER_LOCK numeric(10,0),
    CHNL_ANNL_SALES numeric(22,7),
    CHNL_QTR_SALES numeric(22,7),
    CHNL_SALES_GROWTH numeric(22,7),
    CLOSE_DT timestamp,
    CMPT_FLG char(1),
    CREDIT_SCORE numeric(22,7),
    CUR_YR_BK numeric(22,7),
    CUR_YR_BL numeric(22,7),
    CUST_END_DT timestamp,
    CUST_SINCE_DT timestamp,
    DEDUP_DATACLNSD_DT timestamp,
    DEDUP_KEY_UPD_DT timestamp,
    DEDUP_LAST_MTCH_DT timestamp,
    DISA_ALL_MAILS_FLG char(1),
    DIVISION_COUNT numeric(22,7),
    EAI_SYNC_DT timestamp,
    EMP_COUNT numeric(22,7),
    EVT_HOTEL_STD_RT numeric(22,7),
    EXCH_DT timestamp,
    FUL_CENTER_FLG char(1),
    GSA_FLG char(1),
    HARD_TO_REACH char(1),
    HIST_SLS_EXCH_DT timestamp,
    HIST_SLS_VOL numeric(22,7),
    HSHLDHD_AGE numeric(22,7),
    HSHLD_INC numeric(22,7),
    HSHLD_KIDAGE numeric(22,7),
    HSHLD_KIDS numeric(22,7),
    HSHLD_SIZE numeric(22,7),
    LAST_CALL_DT timestamp,
    LAST_MGR_REVW_DT timestamp,
    LATITUDE numeric(22,7),
    LONGITUDE numeric(22,7),
    MISC_FLG char(1),
    NUM_HSHLDS numeric(22,7),
    NUM_OF_BEDS numeric(22,7),
    NUM_REGS numeric(22,7),
    PARTNER_FLG char(1),
    PO_CRDCHK_THRSH numeric(22,7),
    PO_CRDCHK_THRSH_DT timestamp,
    PO_PAY_EXCH_DT timestamp,
    PO_PAY_FLG char(1),
    PO_PAY_MAX_AMT numeric(22,7),
    PRI_YR_BK numeric(22,7),
    PRI_YR_BL numeric(22,7),
    PROCED_FLG char(1),
    PRTNRSHP_START_DT timestamp,
    PRTNR_SALES_RANK numeric(22,7),
    PTNTL_SLS_EXCH_DT timestamp,
    PTNTL_SLS_VOL numeric(22,7),
    REFERENCE_CUST_FLG char(1),
    REFERENCE_START_DT timestamp,
    SALES_EMP_CNT numeric(10,0),
    SERVICE_EMP_CNT numeric(10,0),
    SRV_PROVDR_FLG char(1),
    STAT_CHG_DT timestamp,
    STORE_SIZE numeric(22,7),
    SUPPRESS_SHARE_FLG char(1),
    SUPRESS_CALL_FLG char(1),
    TAX_EXEMPT_FLG char(1),
    TRGT_IMPL_DT timestamp,
    VISIT_FREQUENCY numeric(10,0),
    WEEKLY_ACV numeric(22,7),
    ABA_NUMBER varchar(50),
    ACCNT_PR_CMPT_ID varchar(15),
    ACCNT_TYPE_CD varchar(30),
    ADL_STATUS varchar(30),
    ALIAS_NAME varchar(100),
    ALT_EMAIL_ADDR varchar(50),
    ALT_EMAIL_LOC_CD varchar(30),
    ANS_SRVC_PH_NUM varchar(40),
    ASGN_PH_AC varchar(5),
    ASGN_PH_CC varchar(5),
    BASE_CURCY_CD varchar(20),
    BO_CUST_GRP_CD varchar(30),
    BRANCH_TYPE_CD varchar(30),
    CALL_FREQUENCY varchar(30),
    CC_TXNPROC_AC_NUM varchar(30),
    CC_TXNPROC_VNDR_ID varchar(15),
    CG_PRMO_STRT_DAY varchar(15),
    CG_SVP_STATUS varchar(30),
    CHANNEL_TYPE varchar(50),
    CORP_STOCK_SYMBOL varchar(20),
    CREATOR_LOGIN varchar(50),
    CROSS_STREET varchar(40),
    CURR_PRI_LST_ID varchar(15),
    CURR_RATE_LST_ID varchar(15),
    CUR_SRV_ADDR_ID varchar(15),
    CUR_YR_BK_CURCY_CD varchar(20),
    CUR_YR_BL_CURCY_CD varchar(20),
    CUST_STAT_CD varchar(30),
    DEDUP_TOKEN varchar(100),
    DEPT_NUM varchar(30),
    DESC_TEXT varchar(255),
    DFLT_SHIP_PRIO_CD varchar(30),
    DIST_CHANNEL_CD varchar(30),
    DIVISION varchar(25),
    DIVN_CD varchar(30),
    DIVN_TYPE_CD varchar(30),
    DOM_ULT_DUNS_NUM varchar(15),
    DUNS_NUM varchar(15),
    EAI_ERROR_TEXT varchar(2000),
    EAI_EXPRT_STAT_CD varchar(30),
    EMAIL_ADDR varchar(50),
    EMAIL_LOC_CD varchar(30),
    EVT_LOC_CD varchar(30),
    EXEC_SPNSR_PSTN_ID varchar(15),
    EXPERTISE_CD varchar(30),
    FIN_RESP_CON_ID varchar(15),
    FRD_OWNER_EMP_ID varchar(15),
    FRGHT_TERMS_CD varchar(30),
    FRGHT_TERMS_INFO varchar(100),
    GENERAL_LEDGER varchar(50),
    GLBLULT_DUNS_NUM varchar(15),
    GRWTH_STRTGY_DESC varchar(1001),
    HIST_SLS_CURCY_CD varchar(20),
    HSHLDHD_GEN_CD varchar(30),
    HSHLDHD_OCC_CD varchar(30),
    HSHLD_ETHN_CD varchar(30),
    HSHLD_LOC_CD varchar(30),
    IMPL_DESC varchar(1000),
    IMPL_STAGE_CD varchar(30),
    INTEGRATION_ID varchar(30),
    LAST_REVW_MGR_ID varchar(15),
    LEGAL_FORM_CD varchar(30),
    LOC varchar(50),
    LOCATION_LEVEL varchar(30),
    MAIN_EMAIL_ADDR varchar(50),
    MAIN_FAX_PH_NUM varchar(40),
    MAIN_PH_NUM varchar(40),
    MANAGER_NAME varchar(40),
    MARKET_CLASS_CD varchar(30),
    MARKET_TYPE_CD varchar(30),
    MASTER_OU_ID varchar(15),
    NAME_1 varchar(100),
    OU_NUM varchar(30),
    OU_NUM_1 varchar(30),
    OU_TYPE_CD varchar(30),
    PAR_BU_ID varchar(15),
    PAR_DIVN_ID varchar(15),
    PAR_DUNS_NUM varchar(15),
    PAR_OU_ID varchar(15),
    PASSWORD varchar(20),
    PAYMENT_TERM_ID varchar(15),
    PO_PAY_CURCY_CD varchar(20),
    PREF_COMM_METH_CD varchar(30),
    PRIVACY_CD varchar(30),
    PRI_GRP_CD varchar(30),
    PRI_YR_BK_CURCY_CD varchar(20),
    PRI_YR_BL_CURCY_CD varchar(20),
    PROD_DIST_CD varchar(30),
    PRTNR_CERT_CD varchar(30),
    PRTNR_ORG_INT_ID varchar(15),
    PRTNR_TYPE_CD varchar(30),
    PR_ADDR_ID varchar(15),
    PR_ADDR_PER_ID varchar(15),
    PR_AGREE_ID varchar(15),
    PR_BL_ADDR_ID varchar(15),
    PR_BL_OU_ID varchar(15),
    PR_BL_PER_ID varchar(15),
    PR_COMPETITOR_ID varchar(15),
    PR_CON_ID varchar(15),
    PR_CO_MSTR_ID varchar(15),
    PR_CRDT_AREA_ID varchar(15),
    PR_DISCNT_ID varchar(15),
    PR_EAI_SLS_AREA_ID varchar(15),
    PR_EMP_REL_ID varchar(15),
    PR_EMP_TERR_ID varchar(15),
    PR_FULFL_INVLOC_ID varchar(15),
    PR_GEO_ID varchar(15),
    PR_IMPLSVC_VNDR_ID varchar(15),
    PR_INDUST_ID varchar(15),
    PR_LOGO_ID varchar(15),
    PR_MED_PROC_ID varchar(15),
    PR_MGR_POSTN_ID varchar(15),
    PR_MKT_SEG_ID varchar(15),
    PR_ORG_TRGT_MKT_ID varchar(15),
    PR_OU_TYPE_ID varchar(15),
    PR_PAY_OU_ID varchar(15),
    PR_PHONE_ID varchar(15),
    PR_POSTN_ID varchar(15),
    PR_PRFL_ID varchar(15),
    PR_PRI_LST_ID varchar(15),
    PR_PROD_ID varchar(15),
    PR_PROD_LN_ID varchar(15),
    PR_PRTNR_OU_ID varchar(15),
    PR_PRTNR_TIER_ID varchar(15),
    PR_PRTNR_TYPE_ID varchar(15),
    PR_PTSHP_MKTSEG_ID varchar(15),
    PR_REP_ASGN_TYPE varchar(30),
    PR_SECURITY_ID varchar(15),
    PR_SHIP_ADDR_ID varchar(15),
    PR_SHIP_OU_ID varchar(15),
    PR_SHIP_PER_ID varchar(15),
    PR_SITU_ID varchar(15),
    PR_SPECIALTY_ID varchar(15),
    PR_SPEC_ID varchar(15),
    PR_SRV_AGREE_ID varchar(15),
    PR_SVC_POSTN_ID varchar(15),
    PR_SYN_ID varchar(15),
    PR_TERR_ID varchar(15),
    PR_VEHICLE_ID varchar(15),
    PTNTL_SLS_CURCY_CD varchar(20),
    RATING varchar(30),
    REGION varchar(25),
    REGION_ID varchar(15),
    REL_ID varchar(15),
    REL_NAME varchar(100),
    REVENUE_CLASS_CD varchar(30),
    RLZD_ROI_DESC varchar(250),
    ROUTE varchar(30),
    RTE_TO_MKT_DESC varchar(500),
    RULE_ATTRIB1 varchar(50),
    RULE_ATTRIB2 varchar(50),
    SALES_ORG_CD varchar(30),
    SLS_DIST_CD varchar(30),
    STAFF varchar(250),
    STATUS_CD varchar(30),
    STAT_REASON_CD varchar(30),
    SURVEY_TYPE_CD varchar(30),
    SVC_CVRG_STAT_CD varchar(30),
    TAX_EXEMPT_NUM varchar(30),
    TAX_IDEN_NUM varchar(50),
    TAX_LIST_ID varchar(15),
    TICKER_SYM varchar(10),
    TLR_INTG_MSG varchar(250),
    TLR_INTG_RET_CD varchar(30),
    URL varchar(100),
    VAT_REGN_NUM varchar(30),
    VISIT_PERIOD varchar(30),
    AGENCY_INACTIVE_DT timestamp,
    AGENCY_INDICATOR varchar(30),
    AGENCY_NIBRS_IND varchar(30),
    AIA_INTEG_ID varchar(150),
    APPROVAL_STATUS_CD varchar(30),
    CMPNY_NAME varchar(50),
    CONTRACT_VIS_FLG char(1),
    CORE_CITY_CD varchar(30),
    CORP_CMPNY_NAME varchar(50),
    COUNTRY_DIVISION varchar(30),
    COUNTRY_REGION varchar(30),
    COUNTRY_TEMPLATE varchar(15),
    COVERED_BY varchar(15),
    CREDIT_DAYS numeric(10,0),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    DIVN_TERR_HIER_ID varchar(15),
    FBI_FIELD_OFF_ID varchar(15),
    FURI_CMPNY_NAME varchar(50),
    JUDICIAL_DISTRICT varchar(30),
    LOY_PARTNER_CD varchar(30),
    ORI_CD varchar(30),
    ORI_TS timestamp,
    OWNERSHIP_TYPE_CD varchar(30),
    PAY_TYPE_CD varchar(30),
    POPULATION_GRP_CD varchar(30),
    PR_BILL_PRFL_ID varchar(15),
    PR_ORG_PAY_PRFL_ID varchar(15),
    PR_PRTNR_PROG_ID varchar(15),
    PR_TERRITORY_ID varchar(15),
    PREF_CARR_PRIO_CD varchar(30),
    PREF_SHIP_CARR_CD varchar(30),
    STATE_ABBRE_CD varchar(30)
);


CREATE TABLE sfa_history.s_state_lic_ls
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    CONTACT_ID varchar(15),
    STATE_CD varchar(30),
    LICENSE_EXP_DT timestamp,
    LICENSE_NUM varchar(30),
    STATUS_CD varchar(30),
    X_OK_TO_SAMPLE_FLG char(1),
    X_VALIDATION_DT timestamp,
    X_VENDOR_VALIDATION_ID varchar(100),
    CATEGORY_CD varchar(30),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    ISSUING_AUTHORITY varchar(50),
    ONE_SAMPLE_FLG char(1),
    SUB_TYPE_CD varchar(30),
    TYPE_CD varchar(30),
    X_SRC_LAST_UPD timestamp
);


CREATE TABLE sfa_history.s_addr_per
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    DCKING_NUM numeric(22,7),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    ADDR_NAME varchar(500),
    DISA_CLEANSE_FLG char(1),
    NAME_LOCK_FLG char(1),
    PREMISE_FLG char(1),
    ACTIVE_FLG char(1),
    END_DT timestamp,
    INFO_RECORD_DT timestamp,
    LATITUDE numeric(22,7),
    LONGITUDE numeric(22,7),
    START_DT timestamp,
    ADDR varchar(200),
    ADDR_LINE_2 varchar(100),
    ADDR_LINE_3 varchar(100),
    ADDR_MAIL_CD varchar(30),
    ADDR_NUM varchar(30),
    ADDR_SUB_CD varchar(30),
    ADDR_TYPE_CD varchar(30),
    BILLACCT_ID varchar(15),
    CITY varchar(50),
    COMMENTS varchar(255),
    COUNTRY varchar(30),
    COUNTY varchar(50),
    DESCRIPTOR varchar(100),
    DISTRICT varchar(50),
    EMAIL_ADDR varchar(100),
    FAX_PH_NUM varchar(40),
    INTEGRATION2_ID varchar(30),
    INTEGRATION3_ID varchar(30),
    INTEGRATION_ID varchar(30),
    LANDLORD_NAME varchar(100),
    LANDLORD_PH_NUM varchar(40),
    OWNERSHIP_CD varchar(30),
    PER_ID varchar(15),
    PH_NUM varchar(40),
    PROVINCE varchar(50),
    RURAL_ROUTE_NUM varchar(10),
    STATE varchar(10),
    TIME_ZONE_CD varchar(30),
    ZIPCODE varchar(30),
    ADDR_LINE_4 varchar(100),
    ADDR_LINE_5 varchar(100),
    ADDRESSEE varchar(100),
    AIA_INTEG_ID varchar(150),
    ALIGNMENT_FLG char(1),
    ALTITUDE numeric(22,7),
    COUNTRY_REGION varchar(100),
    CROSS_ST varchar(100),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    LOCATION_FLG char(1),
    METRO_AREA varchar(100),
    MISC_ADDR_LINE varchar(100),
    MSA numeric(10,0),
    PAR_ADDR_ID varchar(15),
    UTM_EASTING varchar(30),
    UTM_NORTHING varchar(30),
    WORLD_AREA varchar(100),
    ZIPCODE_EXT varchar(4)
);


CREATE TABLE sfa_history.s_act_prdint
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    ACTIVITY_ID varchar(15),
    OPTIMIZATION_FLG char(1),
    PRDINT_ID varchar(15),
    RELATION_TYPE_CD varchar(30),
    ADJUST_QTY numeric(22,7),
    CURR_AVAIL_QTY numeric(10,0),
    ESTIMATE_DT timestamp,
    EST_SEC_HELD numeric(22,7),
    HLDNG_REPORT_DT timestamp,
    INTRST_PRICE numeric(22,7),
    INTRST_REPORT_DT timestamp,
    PRIORITY numeric(10,0),
    QTY numeric(22,7),
    QTY_CHANGE numeric(22,7),
    QTY_HELD numeric(22,7),
    QTY_INTRST numeric(22,7),
    INTRST_LVL_CD varchar(30),
    INTRST_TYPE_CD varchar(30),
    LOT_ID varchar(15),
    LOT_NUM varchar(30),
    PR_ISS_ID varchar(15),
    PR_ORDER_ITEM_ID varchar(15),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    INTEGRATION_ID varchar(30),
    MAX_ALLOC_QTY numeric(22,7),
    MAX_CALL_QTY numeric(22,7),
    MAX_PRODUCT_QTY numeric(22,7),
    PROD_ALLOC_ID varchar(15),
    SUM_SAMPLE_ALLOC numeric(22,7),
    SUM_SAMPLE_PROD numeric(22,7),
    X_SRC_LAST_UPD timestamp,
    X_REPORTABLE_FLG char(1),
    X_RETAIL_PRICE numeric(22,7)
);


CREATE TABLE sfa_history.s_evt_act
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    DCKING_NUM numeric(22,7),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    ACTIVITY_UID varchar(30),
    PAR_EVT_ID varchar(15),
    APPT_START_DT timestamp,
    APPT_START_TM timestamp,
    TARGET_OU_ID varchar(15),
    TARGET_OU_ADDR_ID varchar(15),
    TARGET_PER_ID varchar(15),
    TARGET_PER_ADDR_ID varchar(15),
    NAME varchar(150),
    ZIPCODE varchar(30),
    EVT_STAT_CD varchar(30),
    SUBTYPE_CD varchar(30),
    TODO_CD varchar(30),
    OWNER_PER_ID varchar(15),
    OWNER_POSTN_ID varchar(15),
    INTEGRATION_ID varchar(30),
    REF_NUM varchar(30),
    COMMENTS varchar(255)
);


CREATE TABLE sfa_history.s_postn
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    PAR_ROW_ID varchar(15),
    BU_ID varchar(15),
    COMPENSATABLE_FLG char(1),
    IN_IC_RETRORUN_FLG char(1),
    NAME varchar(50),
    OU_ID varchar(15),
    BL_RT_AMT numeric(22,7),
    CG_SVP_ALLOC_LVL numeric(10,0),
    CP_PLAN_LVL_NUM numeric(10,0),
    END_DT timestamp,
    OWNER_ALLOC_PCT numeric(22,7),
    START_DT timestamp,
    BL_PROD_ID varchar(15),
    CMPNS_CURCY_CD varchar(20),
    DESC_TEXT varchar(255),
    INTEGRATION_ID varchar(30),
    PAR_POSTN_ID varchar(15),
    POSTN_TYPE_CD varchar(30),
    PR_EMP_ID varchar(15),
    PR_OU_EXT_ID varchar(15),
    PR_POSTN_ADDR_ID varchar(15),
    PR_POSTN_ID varchar(15),
    PR_PROD_ID varchar(15),
    PR_PROD_LN_ID varchar(15),
    PR_TERR_ID varchar(15),
    CRDT_AUTH_AMT numeric(22,7),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    PGROUP_ID varchar(15),
    X_SALES_FORCE varchar(100)
);


CREATE TABLE sfa_history.s_contact
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    DCKING_NUM numeric(22,7),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    PAR_ROW_ID varchar(15),
    ACTIVE_FLG char(1),
    BU_ID varchar(15),
    COURT_PAY_FLG char(1),
    DISA_CLEANSE_FLG char(1),
    DISP_IMG_AUTH_FLG char(1),
    EMAIL_SR_UPD_FLG char(1),
    EMP_FLG char(1),
    FST_NAME varchar(50),
    INVSTGTR_FLG char(1),
    LAST_NAME varchar(50),
    PERSON_UID varchar(100),
    PO_PAY_FLG char(1),
    PRIV_FLG char(1),
    PROSPECT_FLG char(1),
    PTSHP_CONTACT_FLG char(1),
    PTSHP_KEY_CON_FLG char(1),
    SEND_SURVEY_FLG char(1),
    SPEAKER_FLG char(1),
    SUPPRESS_EMAIL_FLG char(1),
    SUPPRESS_FAX_FLG char(1),
    SUSPECT_FLG char(1),
    AGENT_FLG char(1),
    ENTERPRISE_FLAG char(1),
    MEMBER_FLG char(1),
    OK_TO_SAMPLE_FLG char(1),
    PROVIDER_FLG char(1),
    PR_REP_DNRM_FLG char(1),
    PR_REP_MANL_FLG char(1),
    PR_REP_SYS_FLG char(1),
    SEND_FIN_FLG char(1),
    SEND_NEWS_FLG char(1),
    SEND_PROMOTES_FLG char(1),
    SUPPRESS_CALL_FLG char(1),
    SUPPRESS_MAIL_FLG char(1),
    AGE numeric(22,7),
    ANNL_INCM_AMT numeric(22,7),
    ANNL_INCM_EXCH_DT timestamp,
    ASGN_DT timestamp,
    ASGN_EXCLD_FLG2 char(1),
    ASGN_REQUIRED_FLG2 char(1),
    ASGN_USR_EXCLD_FLG char(1),
    BIRTH_DT timestamp,
    CALL_FLG char(1),
    CONSUMER_FLG char(1),
    CON_CREATED_DT timestamp,
    CREDIT_SCORE numeric(22,7),
    CUST_END_DT timestamp,
    CUST_SINCE_DT timestamp,
    DEDUP_DATACLNSD_DT timestamp,
    DEDUP_KEY_UPD_DT timestamp,
    DEDUP_LAST_MTCH_DT timestamp,
    HARD_TO_REACH char(1),
    INVES_START_DT timestamp,
    INV_ORG_ST_DT timestamp,
    LAST_CREDIT_DT timestamp,
    LATITUDE numeric(22,7),
    LONGITUDE numeric(22,7),
    MGMNT_FLG char(1),
    SEMINAR_INVIT_FLG char(1),
    ACTIVE_CTI_CFG_ID varchar(15),
    ACTIVE_TELESET_ID varchar(15),
    ALIAS_NAME varchar(50),
    ALT_EMAIL_ADDR varchar(50),
    ALT_EMAIL_LOC_CD varchar(30),
    ALT_PH_NUM varchar(40),
    ANNL_INCM_CURCY_CD varchar(20),
    AREA_ID varchar(15),
    ASST_PH_NUM varchar(40),
    CALL_FREQUENCY varchar(30),
    CELL_PH_NUM varchar(40),
    COMMENTS varchar(255),
    COMPLEXION_CD varchar(30),
    CON_ASST_NAME varchar(50),
    CON_ASST_PER_ID varchar(15),
    CON_CD varchar(30),
    CON_EXPER_CD varchar(30),
    CON_IMAGE_ID varchar(15),
    CON_INFLUNC_ID varchar(15),
    CON_MANAGER_NAME varchar(50),
    CON_MANAGER_PER_ID varchar(15),
    CREATOR_LOGIN varchar(50),
    CREDIT_AGENCY varchar(30),
    CSN varchar(50),
    CUST_STAT_CD varchar(30),
    CUST_VALUE_CD varchar(30),
    DECISION_TYPE_CD varchar(30),
    DEDUP_TOKEN varchar(100),
    DEGREE varchar(30),
    DFLT_ORDER_PROC_CD varchar(30),
    EMAIL_ADDR varchar(100),
    EMAIL_LOC_CD varchar(30),
    EMPLMNT_STAT_CD varchar(30),
    EMP_ID varchar(15),
    EMP_NUM varchar(30),
    EMP_WORK_LOC_NAME varchar(50),
    EYE_COLOR varchar(30),
    FAX_PH_NUM varchar(40),
    HAIR_COLOR varchar(30),
    HEIGHT varchar(20),
    HOME_PH_NUM varchar(40),
    INDUST_ID varchar(15),
    INTEGRATION_ID varchar(30),
    JOB_TITLE varchar(75),
    LOGIN varchar(50),
    MAIDEN_NAME varchar(50),
    MARITAL_STAT_CD varchar(30),
    MED_SPEC_ID varchar(15),
    MID_NAME varchar(50),
    MOTHER_MAIDEN_NAME varchar(50),
    NATIONALITY varchar(30),
    NEW_USER_RESP_NAME varchar(50),
    NICK_NAME varchar(50),
    OCCUPATION varchar(50),
    OU_ID varchar(15),
    OU_MAIL_STOP varchar(30),
    OWNER_LOGIN varchar(50),
    OWNER_PER_ID varchar(15),
    PAGER_COMPANY_ID varchar(15),
    PAGER_NUM varchar(40),
    PAGER_PH_NUM varchar(40),
    PAGER_PIN varchar(40),
    PAGER_TYPE_CD varchar(30),
    PASSWORD varchar(20),
    PER_TITLE varchar(15),
    PER_TITLE_SUFFIX varchar(15),
    PLACE_OF_BIRTH varchar(100),
    POSTN_CD varchar(30),
    PRACTICE_TYPE varchar(30),
    PREF_COMM_MEDIA_CD varchar(30),
    PREF_COMM_METH_CD varchar(30),
    PREF_LANG_ID varchar(15),
    PREF_SALE_DLR_ID varchar(15),
    PRIVACY_CD varchar(30),
    PR_ACT_ID varchar(15),
    PR_AFFL_ID varchar(15),
    PR_ALT_PH_NUM_ID varchar(15),
    PR_ASSET_ID varchar(15),
    PR_BL_PER_ADDR_ID varchar(15),
    PR_CLIENT_OU_ID varchar(15),
    PR_CON_ADDR_ID varchar(15),
    PR_CST_ACCNT_ID varchar(15),
    PR_CTI_CFG_ID varchar(15),
    PR_DEPT_OU_ID varchar(15),
    PR_DRVR_LICENSE_ID varchar(15),
    PR_EMAIL_ADDR_ID varchar(15),
    PR_FACILITY_ID varchar(15),
    PR_GRP_OU_ID varchar(15),
    PR_HELD_POSTN_ID varchar(15),
    PR_IMAGE_ID varchar(15),
    PR_INDUST_ID varchar(15),
    PR_MKT_SEG_ID varchar(15),
    PR_NOTE_ID varchar(15),
    PR_OPTY_ID varchar(15),
    PR_OU_ADDR_ID varchar(15),
    PR_PER_ADDR_ID varchar(15),
    PR_PER_PAY_PRFL_ID varchar(15),
    PR_PHONE_ID varchar(15),
    PR_POSTN_ID varchar(15),
    PR_PROD_ID varchar(15),
    PR_PROD_LN_ID varchar(15),
    PR_REGION_ID varchar(15),
    PR_RESP_ID varchar(15),
    PR_SECURITY_ID varchar(15),
    PR_SH_PER_ADDR_ID varchar(15),
    PR_SPECIALTY_ID varchar(15),
    PR_STATE_LIC_ID varchar(15),
    PR_SYNC_USER_ID varchar(15),
    PR_TERR_ID varchar(15),
    PR_USERROLE_ID varchar(15),
    RACE varchar(30),
    RATING varchar(30),
    REGION_ID varchar(15),
    REGL_STAT_CD varchar(30),
    ROUTE varchar(30),
    SEX_MF varchar(30),
    SOC_SECURITY_NUM varchar(20),
    SRC_ID varchar(15),
    STATUS_CD varchar(30),
    STAT_REASON_CD varchar(30),
    STOCK_PORTFOLIO varchar(500),
    SUB_SPEC_ID varchar(15),
    SVC_BRANCH_ID varchar(15),
    TIMEZONE_ID varchar(15),
    TMZONE_CD varchar(30),
    WEATHR_LOC_PREF varchar(75),
    WEB_REGION_ID varchar(15),
    WEIGHT varchar(20),
    WORK_PH_NUM varchar(40),
    AIA_INTEG_ID varchar(150),
    APPROVAL_STATUS_CD varchar(30),
    CITIZENSHIP_CD varchar(30),
    CORP_PTRNL_LSTNAME varchar(50),
    COUNTRY_TEMPLATE varchar(15),
    CURR_PRI_LST_ID varchar(15),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    DEATH_DT timestamp,
    EMAIL_STATUS_CD varchar(30),
    ETHNICITY_CD varchar(30),
    FURI_PTRNL_LSTNAME varchar(50),
    HEIGHT_UOM_CD varchar(30),
    LEFT_EYE_CLR_CD varchar(30),
    LST_EMLADR_UPD_TS timestamp,
    MSTR_CASE_ID varchar(15),
    NUM_HARD_BNCE numeric(10,0),
    NUM_SOFT_BNCE numeric(10,0),
    PATERNAL_LAST_NAME varchar(50),
    PR_COMM_LANG_ID varchar(15),
    PREF_LOCALE_ID varchar(15),
    PRESENCE_URI varchar(100),
    RELIABILITY_CD varchar(30),
    RESIDENT_STAT_CD varchar(30),
    RIGHT_EYE_CLR_CD varchar(30),
    SEC_ANSWR varchar(50),
    SEC_QUEST_CD varchar(30),
    SPOUSE_LAST_NAME varchar(50),
    SUSP_WTCH_FLG char(1),
    WEIGHT_UOM_CD varchar(30)
);


CREATE TABLE sfa_history.s_prod_int
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    DCKING_NUM numeric(22,7),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    ACTIVE_FLG char(1),
    ADD_TO_QUOTE_FLG char(1),
    BU_ID varchar(15),
    CG_COMPETITOR_FLG char(1),
    COMMISIONED_FLG char(1),
    COMPENSATABLE_FLG char(1),
    CRT_AST_REC_FLG char(1),
    ENTERPRISE_FLG char(1),
    FEATURED_FLG char(1),
    MODEL_PROD_FLG char(1),
    NAME varchar(100),
    ORDERABLE_FLG char(1),
    POSTN_BL_PROD_FLG char(1),
    SALES_PROD_FLG char(1),
    SALES_SRVC_FLG char(1),
    SERVICE_FLG char(1),
    SERV_INST_FLG char(1),
    SHIP_FLG char(1),
    TARGET_VRSN_FLG char(1),
    TAX_SUBCOMP_FLG char(1),
    TRANSFERABLE_FLG char(1),
    CTRL_SUBS_FLG char(1),
    ACCRUAL_RATE numeric(22,7),
    ALC_BELOW_SFTY_FLG char(1),
    ALOC_ASSETS_FLG char(1),
    APRX_COST_AMT numeric(22,7),
    APX_CST_EXCH_DT timestamp,
    AUTO_ALLOCATE_FLG char(1),
    AUTO_SUBST_FLG char(1),
    AVG_CALL_CST numeric(22,7),
    AVG_CALL_CST_DT timestamp,
    AVG_OP_LIFE numeric(22,7),
    AVG_PROFIT numeric(22,7),
    CAPACITY numeric(22,7),
    CARY_COST numeric(22,7),
    CARY_COST_DT timestamp,
    CASE_CONV_FACTOR numeric(22,7),
    CASE_PACK numeric(22,7),
    CONFIGURATION_FLG char(1),
    CUTOFF_FLG char(1),
    DELIV_INTERVAL numeric(22,7),
    DEST_COST numeric(22,7),
    DISP_CMPNT_FLG char(1),
    DISP_CMPNT_PRI_FLG char(1),
    EFFICIENCY_RATING numeric(22,7),
    EFF_END_DT timestamp,
    EFF_START_DT timestamp,
    EXCH_DT timestamp,
    FRU_FLG char(1),
    GROSS_MGN numeric(22,7),
    INVENTORY_FLG char(1),
    ITEM_SIZE numeric(22,7),
    LOAD_ADDED numeric(22,7),
    LOCK_FLG char(1),
    LOT_ACTIVE_FLG char(1),
    MAX_ORDER_UNITS numeric(22,7),
    MIN_ORDER_UNITS numeric(22,7),
    MODEL_YR numeric(22,7),
    MSRP numeric(22,7),
    MTBF numeric(22,7),
    MTTR numeric(22,7),
    NUM_OCCURRENCE numeric(10,0),
    ORDER_CST numeric(22,7),
    ORDER_CST_DT timestamp,
    PRODUCT_LEVEL numeric(22,7),
    PROD_UPD_DT timestamp,
    REQ_APPL_FLG char(1),
    REQ_REFERRAL_FLG char(1),
    RESERVABLE_FLG char(1),
    RTRN_DEFECTIVE_FLG char(1),
    RXAVPR_EXCH_DT timestamp,
    RX_AVG_PRICE numeric(22,7),
    SERIALIZED_FLG char(1),
    SKIP_FLG char(1),
    TAXABLE_FLG char(1),
    TOOL_FLG char(1),
    UNITS_BCKORD numeric(22,7),
    UNITS_BCKORD_AS_OF timestamp,
    UNITS_INVENT numeric(22,7),
    UNITS_INVENT_AS_OF timestamp,
    UNIT_CONV_FACTOR numeric(22,7),
    ADDL_LEAD_TIME varchar(30),
    ALIAS_NAME varchar(100),
    APX_CST_CURCY_CD varchar(20),
    ASSOC_LEVEL varchar(30),
    ATM_TYPE_CD varchar(30),
    AVGCALLCST_CURCYCD varchar(20),
    BODY_STYLE_CD varchar(30),
    BOOK_APPR_ID varchar(15),
    BUILD varchar(30),
    CARY_COST_CURCY_CD varchar(20),
    CATEGORY_CD varchar(30),
    CFG_MODEL_ID varchar(15),
    CG_PR_CTLG_CAT_ID varchar(15),
    CLASS_PARTNUM_ID varchar(15),
    CONFIG_RULE_FILE varchar(220),
    CRITICAL_CD varchar(30),
    CS_PATH_ID varchar(15),
    CURCY_CD varchar(30),
    DATA_SRC varchar(30),
    DEF_MOD_PROD_ID varchar(15),
    DESC_TEXT varchar(255),
    DETAIL_TYPE_CD varchar(30),
    DFLT_PROCSYS_ID varchar(15),
    DIVN_CD varchar(30),
    DOORS_TYPE_CD varchar(30),
    DOWN_TIME varchar(30),
    DRIVE_TRAIN_CD varchar(30),
    ENGINE_TYPE_CD varchar(30),
    FABRIC_CD varchar(30),
    FUEL_TYPE_CD varchar(30),
    GENDER_CD varchar(30),
    INTEGRATION_ID varchar(30),
    INTL_BLD_LANG_CD varchar(30),
    INVST_CATG_CD varchar(50),
    INVST_OBJ_CD varchar(30),
    LEAD_TM varchar(30),
    LIFE_CYCLE_CD varchar(30),
    MAKE_CD varchar(30),
    MODEL varchar(30),
    MODEL_CD varchar(30),
    MOVEMENT_CLASS varchar(30),
    MTBF_UOM_CD varchar(30),
    MTTR_UOM_CD varchar(30),
    OBJECTIVE_DESC varchar(100),
    ONL_PAGESET_ID varchar(15),
    ORDER_CST_CURCY_CD varchar(20),
    PART_NUM varchar(50),
    PAR_PROD_INT_ID varchar(15),
    PLAN_STATUS varchar(30),
    PM_DEPT_POSTN_ID varchar(15),
    PREAPPR_STATE_ID varchar(15),
    PREF_CARRIER_CD varchar(30),
    PREF_SHIP_METH_CD varchar(30),
    PRICE_TYPE_CD varchar(30),
    PROD_ASSEMBLY_LVL varchar(50),
    PROD_ATTRIB01_CD varchar(30),
    PROD_ATTRIB02_CD varchar(30),
    PROD_ATTRIB03_CD varchar(30),
    PROD_ATTRIB04_CD varchar(30),
    PROD_CATG_CD varchar(30),
    PROD_CD varchar(30),
    PROD_CLS_NUM varchar(50),
    PROD_DIST_CD varchar(30),
    PROD_GLOBAL_UID varchar(50),
    PROD_IMAGE_ID varchar(15),
    PROD_LCYCLE_STATUS varchar(50),
    PROD_OPT1_MIX_ID varchar(15),
    PROD_OPT2_MIX_ID varchar(15),
    PROD_OPTION1_ID varchar(15),
    PROD_OPTION2_ID varchar(15),
    PROD_SUPPLY_CHAIN varchar(50),
    PROD_TYPE_CD varchar(30),
    PROFIT_RANK_CD varchar(30),
    PR_CON_ID varchar(15),
    PR_EQUIV_PROD_ID varchar(15),
    PR_ERNG_ID varchar(15),
    PR_FULFL_INVLOC_ID varchar(15),
    PR_INDUST_ID varchar(15),
    PR_POSTN_ID varchar(15),
    PR_PROD_LN_ID varchar(15),
    PR_SEASON_ID varchar(15),
    PR_TRGT_MKT_SEG_ID varchar(15),
    QUALITY_CD varchar(30),
    REF_NUMBER_1 varchar(30),
    REF_NUMBER_2 varchar(30),
    REF_NUMBER_3 varchar(30),
    REF_NUMBER_4 varchar(30),
    REF_NUMBER_5 varchar(30),
    REGION_ID varchar(15),
    REQ_DATA_ID varchar(15),
    RISK varchar(250),
    RULE_ATTRIB1 varchar(50),
    RULE_ATTRIB2 varchar(50),
    RXAVPR_CURCY_CD varchar(20),
    SCHEDULE_NUM_CD varchar(30),
    SEQ_CD varchar(30),
    SERVICE_TERMS varchar(255),
    SILHOUETTE_CD varchar(30),
    STATUS_CD varchar(30),
    STRATEGY varchar(250),
    STRENGTH varchar(30),
    SUB_TYPE varchar(30),
    SUB_TYPE_CD varchar(30),
    TGT_CUST_TYPE_CD varchar(30),
    TGT_REGION_CD varchar(30),
    THMBNL_IMAGE_ID varchar(15),
    TRANSMISSION_CD varchar(30),
    TRIM_CD varchar(30),
    TYPE varchar(30),
    UOM_CD varchar(30),
    VALTN_SYS_ID varchar(15),
    VALUE_CLASS varchar(30),
    VENDR_OU_ID varchar(15),
    VENDR_PART_NUM varchar(50),
    VERSION varchar(30),
    XA_CLASS_ID varchar(15),
    APPLY_EC_RULE_FLG char(1),
    APPROVAL_FLG char(1),
    ASSET_REF_EXPR varchar(100),
    AUTO_UNGROUP_FLG char(1),
    BAR_CODE_NUM varchar(50),
    BILLABLE_FLG char(1),
    BILLING_TYPE_CD varchar(30),
    CMPND_FLG char(1),
    COMMENTS varchar(250),
    CRT_AGREEMENT_FLG char(1),
    CRT_INST_FLG char(1),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    DESIGN_REG_FLG char(1),
    DPNDNCY_VLDTN_FLG char(1),
    EXP_LEAD_DAYS numeric(10,0),
    GTIN varchar(20),
    INCL_ALL_CRSE_FLG char(1),
    INCL_CRSE_NUM numeric(10,0),
    INCLSV_ELIG_RL_FLG char(1),
    INVNTRY_INTEG_ID varchar(40),
    LEAF_LEVEL_FLG char(1),
    LOY_ACTUAL_DIST numeric(22,7),
    LOY_DIST_UOM varchar(30),
    LOY_EXP_LEAD_TIME numeric(22,7),
    LOY_EXP_UOM varchar(30),
    LOY_EXPR_BASIS_CD varchar(30),
    LOY_FROMAPRT_CD varchar(30),
    LOY_NUM_YEAR numeric(22,7),
    LOY_PERIOD_DUR numeric(22,7),
    LOY_PERIOD_TYPE_CD varchar(30),
    LOY_SEQ_TYPE_CD varchar(30),
    LOY_SERIES_PREFIX varchar(15),
    LOY_SUG_POINTS numeric(22,7),
    LOY_SUG_PRICE numeric(22,7),
    LOY_SUG_PTTYPE_ID varchar(15),
    LOY_SUG_R_POINTS numeric(22,7),
    LOY_SUG_R_PRICE numeric(22,7),
    LOY_SUG_RPTTYPE_ID varchar(15),
    LOY_TOAPRT_CD varchar(30),
    LOY_VCH_EXP_DAY_CD varchar(30),
    LOY_VCH_EXP_MTH_CD varchar(30),
    LOY_VCHREXP_PRDDUR numeric(22,7),
    LOY_VEXP_PERTYP_CD varchar(30),
    NEED_PH_NUM_FLG char(1),
    NET_ELMT_TYPE_CD varchar(30),
    PAYMNT_TYPE_CD varchar(30),
    PERMITTED_TYPE varchar(250),
    PR_SHIP_CARPRIO_ID varchar(15),
    PR_SRC_ID varchar(15),
    PROMO_INSTANCE_CD varchar(30),
    PROMO_TYPE_CD varchar(30),
    REASON_TXT varchar(250),
    REFERENCE_TYPE_CD varchar(30),
    REQD_SERVICE_FLG char(1),
    ROLLUP_LEVEL numeric(10,0),
    ROLLUP_TRGMKT_FLG char(1),
    ROOT_PROD_ID varchar(15),
    SCORE_NUM numeric(22,7),
    SERV_LENGTH_UOM_CD varchar(30),
    SERVICE_LENGTH numeric(10,0),
    SUBSCN_DUR_DAY_NUM numeric(10,0),
    TRGT_MKT_ID varchar(15),
    TWOBARCODES_FLG char(1),
    UNIQUE_ASSET_FLG char(1),
    PRODUCT_ID varchar(25)
);


CREATE TABLE sfa_history.s_postn_con
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    CON_FST_NAME varchar(50),
    CON_ID varchar(15),
    CON_LAST_NAME varchar(50),
    POSTN_ID varchar(15),
    ROW_STATUS varchar(10),
    AGENT_FLG char(1),
    ASGN_DNRM_FLG char(1),
    ASGN_MANL_FLG char(1),
    ASGN_SYS_FLG char(1),
    MEMBER_FLG char(1),
    PRIORITY_FLG char(1),
    PROVIDER_FLG char(1),
    ACTIVE_FLG char(1),
    ASGN_BY_CA_FLG char(1),
    ASGN_BY_PA_FLG char(1),
    LAST_CALL_DT timestamp,
    CON_MID_NAME varchar(50),
    PRACTICE_TYPE varchar(30),
    PROD_ID varchar(15),
    PR_ADDR_ID varchar(15),
    RELATION_CD varchar(30),
    ROUTE varchar(30),
    SPECIALTY varchar(30),
    STATUS varchar(30),
    X_ATTRIB_01 char(1),
    X_ATTRIB_02 char(1),
    X_ATTRIB_03 varchar(50),
    X_ATTRIB_04 varchar(50),
    X_ATTRIB_05 varchar(15),
    X_ATTRIB_06 varchar(15),
    X_ATTRIB_07 timestamp,
    X_ATTRIB_08 timestamp,
    X_ATTRIB_09 varchar(255),
    X_TARGET_FLG char(1),
    ASGN_RULE_GRP_ID varchar(15),
    ASGN_TERR_ID varchar(15),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    DOCK_FLG char(1),
    NEXT_CALL_DT timestamp,
    NEXT_CALL_OBJECTIV varchar(1500),
    X_YEARLY_CALL_GOAL numeric(10,0),
    X_ATTRIB_10 varchar(50),
    X_CALL_PLAN_CD varchar(50),
    X_P3 varchar(50),
    X_PSTN_CON_TYPE varchar(50),
    X_ATTRIB_11 char(1),
    X_ATTRIB_12 char(1),
    X_ATTRIB_13 char(1),
    X_ATTRIB_14 char(1),
    X_ATTRIB_15 char(1),
    X_ATTRIB_16 char(1),
    X_ATTRIB_17 char(1),
    X_ATTRIB_18 char(1),
    X_ATTRIB_19 char(1),
    X_ATTRIB_20 numeric(22,7),
    X_ATTRIB_21 numeric(22,7),
    X_ATTRIB_22 numeric(22,7),
    X_ATTRIB_23 numeric(22,7),
    X_ATTRIB_24 numeric(22,7),
    X_ATTRIB_25 varchar(100),
    X_ATTRIB_26 varchar(100),
    X_ATTRIB_27 varchar(100),
    X_ATTRIB_28 varchar(100),
    X_ATTRIB_29 varchar(100),
    X_ATTRIB_30 varchar(100),
    X_ATTRIB_31 varchar(100),
    X_ATTRIB_32 varchar(100),
    X_ATTRIB_33 varchar(100),
    X_ATTRIB_34 timestamp,
    X_ATTRIB_35 timestamp,
    X_ATTRIB_36 timestamp
);


CREATE TABLE sfa_history.s_contact_fnx
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    PAR_ROW_ID varchar(15),
    ADDR_VERIFY_FLG char(1),
    ATTRNY_FLG char(1),
    CHK_TRUNC_RCV_FLG char(1),
    GRAND_CHILD_FLG char(1),
    HLTHCR_ATTRNY_FLG char(1),
    LIAB_PROVD_FLG char(1),
    OBLG_PAST_DUE_FLG char(1),
    POST_NUPTL_AGR_FLG char(1),
    PRE_NUPTL_AGR_FLG char(1),
    PROSRV_INTRACT_FLG char(1),
    STMT_PREP_PROF_FLG char(1),
    TRUST_EXECUTE_FLG char(1),
    WILL_EXECUTE_FLG char(1),
    WILL_FLG char(1),
    WIRE_ACTIVE_FLG char(1),
    ACCSS_FRD_FILE_FLG char(1),
    AGENT_NUM numeric(10,0),
    AGNT_CONTRACT_DT timestamp,
    AMS_CAPABILITY_LVL numeric(10,0),
    ANNL_INCOME numeric(22,7),
    ANNL_INCOME_DT timestamp,
    ANNL_REVENUE numeric(22,7),
    ARCH_REQST_FLG char(1),
    BK_BNK_FEE_AMT numeric(22,7),
    BK_CLAIM_AMT numeric(22,7),
    BK_CLAIM_DT timestamp,
    BK_DSCLOSR_DT timestamp,
    BK_FILED_DT timestamp,
    BK_GRANT_AMT numeric(22,7),
    BK_HEARING_DT timestamp,
    BK_LGL_FEE_AMT numeric(22,7),
    BK_PETITION_DT timestamp,
    BK_RCVD_AMT numeric(22,7),
    BK_REAFFRM_AMT numeric(22,7),
    BK_REAFFRM_DT timestamp,
    BK_REMAING_AMT numeric(22,7),
    BK_SEC_DEP_AMT numeric(22,7),
    BK_STIPLATN_DT timestamp,
    BL_OUTPYMNT_AMT numeric(22,7),
    BRLOC_ATTRIB03 numeric(22,7),
    BRLOC_ATTRIB08 char(1),
    BRLOC_ATTRIB09 char(1),
    BRLOC_ATTRIB10 char(1),
    BRLOC_ATTRIB11 char(1),
    BRLOC_ATTRIB12 char(1),
    BRLOC_ATTRIB13 char(1),
    CASH_AMT numeric(22,7),
    CBR_SERVICE_LVL numeric(10,0),
    CLEAR_DUP_AUTH_FLG char(1),
    CLEAR_FRD_AUTH_FLG char(1),
    CMNUTY_PRPTY_DT timestamp,
    COB_FLG char(1),
    COMP_OWNER_FLG char(1),
    CRDT_SCRE_OVRD_FLG char(1),
    CREDIT_BUR_HIT_NUM numeric(10,0),
    CREDIT_SCORE numeric(22,7),
    CRRPT_REQ_FLG char(1),
    DECEASED_FLG char(1),
    DLR_TLR_OVRD_FLG char(1),
    DR_LICENSE_EXP_DT timestamp,
    EBPP_ENRL_FLG char(1),
    EBP_ENRL_FLG char(1),
    EBP_PAYMT_LIMIT numeric(22,7),
    EMPL_START_DT timestamp,
    ENTRD_REGN_FLG char(1),
    FINPLAN_COMPL_DT timestamp,
    FST_AUTO_INS_DT timestamp,
    HLTCR_POA_UPD_DT timestamp,
    IDEN2_EXP_DT timestamp,
    INS_NEED_REV_DT timestamp,
    IRR_INSTRST_UPD_DT timestamp,
    IRR_TRST_UPD_DT timestamp,
    JOBS_FIVE_YRS numeric(10,0),
    LAST_CONTACTED_DT timestamp,
    LAST_MARRIAGE_DT timestamp,
    LIVE_TRUST_DT timestamp,
    LIVE_WILL_UPD_DT timestamp,
    LOAN_FORECLSURE_DT timestamp,
    LST_WILL_UPD_DT timestamp,
    MAX_RQST_PRTY_LVL numeric(10,0),
    MTH_OBLG_AMT numeric(22,7),
    NO_YRS_SCHOOL numeric(22,7),
    NUM_DEPENDS numeric(22,7),
    NUM_EST_DEPOSIT numeric(22,7),
    NUM_VAC_DAYS numeric(10,0),
    NUM_VISIT_RESD numeric(10,0),
    NUM_VISIT_WORK numeric(10,0),
    OVRD_AUTO_VAL_FLG char(1),
    PASSPORT_EXP_DT timestamp,
    PASSPORT_ISSUE_DT timestamp,
    PERM_RESIDENT_FLG char(1),
    PERSIST_RATIO numeric(22,7),
    POA_UPD_DT timestamp,
    POST_NUPTL_AGR_DT timestamp,
    PRE_NUPTL_AGR_DT timestamp,
    RECV_TRUST_UPD_DT timestamp,
    RESDNCE_VAL numeric(22,7),
    RESDNCE_YRS numeric(10,0),
    RETIRED_FLG char(1),
    REVOC_TRST_UPD_DT timestamp,
    SCR_RPT_OVRD_FLG char(1),
    SELF_EMPL_FLG char(1),
    SPOUSE_BIRTH_DT timestamp,
    STATE_IDEN_DT timestamp,
    STG_RTE_OVRD_FLG char(1),
    TAX_BRACKET numeric(22,7),
    TOTAL_ASSET numeric(22,7),
    TOTAL_LIABILITY numeric(22,7),
    TRUST_AGREE_DT timestamp,
    TURNDOWN_AUTH_FLG char(1),
    US_CITIZEN_FLG char(1),
    WED_ANVRSRY_DT timestamp,
    YEARS_EMPLYMT numeric(10,0),
    YL_LAST_LOGIN_TS timestamp,
    YL_LAST_UPD_TS timestamp,
    YL_START_UPD_TS timestamp,
    ACCESS_LVL_CD varchar(30),
    ANNL_REV_CURCY_CD varchar(20),
    ATTRITION_RISK_CD varchar(30),
    AUTH_TEXT varchar(250),
    BEHAVIOUR_CD varchar(30),
    BEST_CALLTM_CD varchar(30),
    BILL_PAY_MTHD_CD varchar(30),
    BIRTH_PLACE varchar(50),
    BK_CASE_NUM varchar(10),
    BK_CHPTR_CD varchar(30),
    BK_COURT_NAME varchar(50),
    BK_REF_ASSET_ID varchar(15),
    BK_REF_ASSET_NAME varchar(50),
    BRLOC_ATTRIB01 varchar(50),
    BRLOC_ATTRIB02 varchar(30),
    BRLOC_ATTRIB04 varchar(30),
    BRLOC_ATTRIB05 varchar(10),
    BRLOC_ATTRIB06 varchar(30),
    BRLOC_ATTRIB07 varchar(30),
    COM_PREFERENCE varchar(30),
    CRRPT_FMT_CD varchar(30),
    CURR_FUNDS_MGD varchar(250),
    DEAR_NAME varchar(50),
    DEBT_FEEL_CD varchar(30),
    DEPENDS_DESC varchar(50),
    DEPT_TYPE_CD varchar(30),
    DR_LICENSE_NUM varchar(40),
    DR_LICENSE_STATE varchar(30),
    EBP_IDEN_NUM varchar(30),
    EDUCATION varchar(250),
    EDU_CD varchar(30),
    EMPLOYER_NAME varchar(250),
    EVAL_STAT_CD varchar(30),
    EVIDENCE_REASON varchar(250),
    GOALS varchar(250),
    HEIGHT varchar(20),
    HIST_FUNDS_MGD varchar(250),
    HOBBY_CD varchar(30),
    IDEN2_NUM varchar(40),
    IDEN2_TYPE_CD varchar(30),
    IDEN_NUM varchar(40),
    IDEN_TYPE_CD varchar(30),
    INCOME_RANGE_CD varchar(30),
    INFO_SOURCE_CD varchar(30),
    INS_CVRG_CD varchar(30),
    INTERESTS_TEXT varchar(250),
    INTR_CHG_IMP_CD varchar(30),
    INTR_RATE_SRVEY_CD varchar(30),
    INVST_EXPR_CD varchar(30),
    INVST_HORIZ_CD varchar(30),
    INVST_KNWLDG_CD varchar(30),
    INVST_OBJ_CD varchar(30),
    INVST_PROFILE_CD varchar(30),
    INVST_RISK_CD varchar(30),
    ISSUE_DESC varchar(250),
    LAST_CONTACTED_BY varchar(15),
    LIFE_EVENT_CD varchar(30),
    LIQUDTY_SRVEY_CD varchar(30),
    LOB_REFER_SRC_CD varchar(30),
    MEMBER_NUM varchar(50),
    MGR_TENURE varchar(20),
    MRKT_CAP_PREF_CD varchar(30),
    NET_WORTH_CD varchar(30),
    NET_WRTHVALMTHD_CD varchar(30),
    NET_WRTHVALTYPE_CD varchar(30),
    NET_WRTH_SRC_CD varchar(30),
    NOT_VERIFIED_REASN varchar(250),
    NPI_NUM varchar(30),
    PANEL_CD varchar(30),
    PEEVES_TEXT varchar(250),
    PERF_EXPECT_CD varchar(30),
    PHLNTRPHY_OBJTV_CD varchar(30),
    POST_RETIREMENT_CD varchar(30),
    PRACTICE_CD varchar(30),
    PREV_BANK_BRANCH varchar(50),
    PREV_BANK_PH_NUM varchar(40),
    PRONUNCIATION varchar(100),
    PR_METRP_STAT_AREA varchar(10),
    PURCH_TYPE_CD varchar(30),
    REFER_SRC_CD varchar(30),
    REGION_CD varchar(30),
    RESDNCE_CATG_CD varchar(30),
    RESDNCE_TYPE_CD varchar(30),
    RESIDENCY_INSTN varchar(50),
    RISK_RATING_INFO varchar(50),
    RSRCH_CHNL_PREF_CD varchar(30),
    SALUTATION_CD varchar(30),
    SERVICE_GUIDELINE varchar(250),
    SHOW_APPL_CHOICE varchar(100),
    STATUS_CD varchar(30),
    STMT_FORMAT_CD varchar(30),
    STMT_FREQ_CD varchar(30),
    TECH_IMP_CD varchar(30),
    TLR_INTG_MSG varchar(250),
    TLR_INTG_RET_CD varchar(30),
    UPIN_NUM varchar(30),
    WEIGHT varchar(20),
    WILL_PREP_LOC varchar(50),
    YL_ENCRPKEY_REF varchar(30),
    YL_LASTUPD_TYPE_CD varchar(30),
    YL_LAST_ERR_MSG varchar(250),
    YL_LAST_UPD_STATUS varchar(50),
    YL_LOGIN varchar(50),
    YL_PASSWD varchar(90),
    YL_STATUS varchar(40),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    HOLD_PYMT_FLG char(1),
    IDEN2_STATE_CD varchar(30),
    IDEN_EXP_DT timestamp,
    IDEN_STATE_CD varchar(30),
    OFAC_FST_ACCESS_DT timestamp,
    OFAC_LST_ACCESS_DT timestamp,
    OFAC_STAT_CD varchar(30)
);


CREATE TABLE sfa_history.s_med_spec
(
    ROW_ID varchar(15),
    CREATED timestamp,
    CREATED_BY varchar(15),
    LAST_UPD timestamp,
    LAST_UPD_BY varchar(15),
    MODIFICATION_NUM numeric(10,0),
    CONFLICT_ID varchar(15),
    NAME varchar(50),
    SPEC_CD varchar(15),
    ASGN_TYPE_CD varchar(30),
    DB_LAST_UPD timestamp,
    DB_LAST_UPD_SRC varchar(50),
    PAR_SPEC_CD varchar(30),
    SPEC_SEQ varchar(30)
);


CREATE  VIEW sfa_history.v_siebel_account_calls AS
 SELECT rep_p.X_SALES_FORCE AS sales_force_id,
        ea.PAR_EVT_ID AS par_evt_id,
        ea.ROW_ID AS csf_call_id,
        ea.TARGET_OU_ID AS csf_demo_id,
        'ACCT'::varchar(4) AS call_type,
        o.OU_TYPE_CD AS ou_type_cd,
        ea.NAME AS name_on_call,
        ea.ZIPCODE AS zip_on_call,
        ea.SUBTYPE_CD AS subtype_cd,
        ea.TODO_CD AS todo_cd,
        ea.ROW_ID AS siebel_evt_act_row_id,
        ea.TARGET_OU_ID AS siebel_target_ou_id,
        emp.CSN AS rep_id,
        rep_p.NAME AS territory_num,
        trunc(ea.APPT_START_DT, 'DD'::varchar(2)) AS call_date,
        details.first_detailed_product_id,
        details.first_detailed_product,
        details.second_detailed_product_id,
        details.second_detailed_product,
        details.third_detailed_product_id,
        details.third_detailed_product,
        details.fourth_detailed_product_id,
        details.fourth_detailed_product,
        details.fifth_detailed_product_id,
        details.fifth_detailed_product,
        details.sixth_detailed_product_id,
        details.sixth_detailed_product,
        CASE WHEN (length(o.INTEGRATION_ID) = 18) THEN o.INTEGRATION_ID ELSE NULL END AS veeva_account_id,
        ea.INTEGRATION_ID AS integration_id
 FROM ((((sfa_history.s_evt_act ea LEFT  JOIN sfa_history.s_postn rep_p ON ((rep_p.ROW_ID = ea.OWNER_POSTN_ID))) LEFT  JOIN sfa_history.s_org_ext o ON ((o.ROW_ID = ea.TARGET_OU_ID))) LEFT  JOIN sfa_history.s_contact emp ON ((emp.ROW_ID = ea.CREATED_BY))) LEFT  JOIN ( SELECT iq.activity_id,
        max(CASE WHEN (iq.priority = 1) THEN iq.product_id ELSE NULL END) AS first_detailed_product_id,
        max(CASE WHEN (iq.priority = 1) THEN iq.product_name ELSE NULL END) AS first_detailed_product,
        max(CASE WHEN (iq.priority = 2) THEN iq.product_id ELSE NULL END) AS second_detailed_product_id,
        max(CASE WHEN (iq.priority = 2) THEN iq.product_name ELSE NULL END) AS second_detailed_product,
        max(CASE WHEN (iq.priority = 3) THEN iq.product_id ELSE NULL END) AS third_detailed_product_id,
        max(CASE WHEN (iq.priority = 3) THEN iq.product_name ELSE NULL END) AS third_detailed_product,
        max(CASE WHEN (iq.priority = 4) THEN iq.product_id ELSE NULL END) AS fourth_detailed_product_id,
        max(CASE WHEN (iq.priority = 4) THEN iq.product_name ELSE NULL END) AS fourth_detailed_product,
        max(CASE WHEN (iq.priority = 5) THEN iq.product_id ELSE NULL END) AS fifth_detailed_product_id,
        max(CASE WHEN (iq.priority = 5) THEN iq.product_name ELSE NULL END) AS fifth_detailed_product,
        max(CASE WHEN (iq.priority = 6) THEN iq.product_id ELSE NULL END) AS sixth_detailed_product_id,
        max(CASE WHEN (iq.priority = 6) THEN iq.product_name ELSE NULL END) AS sixth_detailed_product
 FROM ( SELECT appl.ACTIVITY_ID AS activity_id,
        spi.PRODUCT_ID AS product_id,
        upper(spi.NAME) AS product_name,
        row_number() OVER (PARTITION BY appl.ACTIVITY_ID ORDER BY appl.PRIORITY_NUM, upper(spi.NAME)) AS priority
 FROM (sfa_history.s_act_prod_appl appl LEFT  JOIN sfa_history.s_prod_int spi ON ((appl.PRDINT_ID = spi.ROW_ID)))
 WHERE (appl.CONFLICT_ID = '0'::varchar(1))) iq
 GROUP BY iq.activity_id) details ON ((details.activity_id = ea.PAR_EVT_ID)))
 WHERE ((ea.EVT_STAT_CD = 'Submitted'::varchar(9)) AND (rep_p.POSTN_TYPE_CD = ANY (ARRAY['Sales Representative'::varchar(20), 'TSP Test Position'::varchar(17)])) AND (ea.OWNER_POSTN_ID <> '0-5220'::varchar(6)) AND (ea.APPT_START_DT >= '2011-01-01 00:00:00'::timestamp(0)) AND (ea.APPT_START_DT < (statement_timestamp())::timestamp) AND (ea.SUBTYPE_CD = 'Account Call'::varchar(12)) AND (ea.TODO_CD = 'Account Call'::varchar(12)));

CREATE  VIEW sfa_history.v_siebel_samples_account_calls AS
 SELECT rep_p.X_SALES_FORCE AS sales_force_id,
        ea.PAR_EVT_ID AS par_evt_id,
        ea.ROW_ID AS csf_call_id,
        ea.TARGET_PER_ID AS csf_demo_id,
        'ACCT'::varchar(4) AS call_type,
        ea.NAME AS name_on_call,
        ea.ZIPCODE AS zip_on_call,
        ea.SUBTYPE_CD AS subtype_cd,
        ea.TODO_CD AS todo_cd,
        ea.INTEGRATION_ID AS integration_id,
        ea.ROW_ID AS siebel_evt_act_row_id,
        ea.TARGET_PER_ID AS siebel_target_per_id,
        emp.CSN AS rep_id,
        rep_p.NAME AS territory_num,
        trunc(ea.APPT_START_DT, 'DD'::varchar(2)) AS call_date,
        details.product_name,
        details.lot_num,
        details.qty,
        details.relation_type_cd,
        o.OU_TYPE_CD AS ou_type_cd,
        CASE WHEN (length(emp.INTEGRATION_ID) = 18) THEN emp.INTEGRATION_ID ELSE NULL END AS veeva_account_id
 FROM ((((sfa_history.s_evt_act ea LEFT  JOIN sfa_history.s_postn rep_p ON ((rep_p.ROW_ID = ea.OWNER_POSTN_ID))) LEFT  JOIN sfa_history.s_org_ext o ON ((o.ROW_ID = rep_p.BU_ID))) LEFT  JOIN sfa_history.s_contact emp ON ((emp.ROW_ID = ea.TARGET_PER_ID))) JOIN ( SELECT appl.ACTIVITY_ID AS activity_id,
        upper(spi.NAME) AS product_name,
        appl.LOT_NUM AS lot_num,
        appl.QTY AS qty,
        appl.RELATION_TYPE_CD AS relation_type_cd
 FROM (sfa_history.s_act_prdint appl JOIN sfa_history.s_prod_int spi ON ((appl.PRDINT_ID = spi.ROW_ID)))
 WHERE ((appl.CONFLICT_ID = '0'::varchar(1)) AND (appl.RELATION_TYPE_CD = ANY (ARRAY['DirectSend'::varchar(10), 'Sample'::varchar(6)])))) details ON ((details.activity_id = ea.ROW_ID)))
 WHERE ((rep_p.NAME <> ALL (ARRAY['Siebel Administrator'::varchar(24), 'TWH Siebel Administrator'::varchar(24)])) AND (o.NAME <> ALL (ARRAY['Siebel Administration'::varchar(21), 'ERM AnonUser'::varchar(12), 'Default Organization'::varchar(20)])) AND (coalesce(o.OU_TYPE_CD, 'XXX'::varchar(3)) <> 'Manufacturer'::varchar(12)));

CREATE  VIEW sfa_history.v_siebel_demo AS
 SELECT c.ROW_ID AS csf_demo_id,
        p.X_SALES_FORCE AS sales_force_id,
        'PROF'::varchar(4) AS demo_type,
        x.ATTRIB_03 AS ims_id,
        x.X_ATTRIB_50 AS hms_id,
        substr(btrim(x.ATTRIB_36), 1, 10) AS me_num,
        ca.DEA_NUM AS dea_num,
        ca.DEA_EXPR_DT AS dea_expir_date,
        substr(ca.X_ATTRIB_03, 1, 12) AS dea_drug_schedule,
        p.NAME AS territory_num,
        'N'::varchar(1) AS house_acct_flag,
        'A'::varchar(1) AS src_verification_status,
        c.LAST_NAME AS last_name,
        c.FST_NAME AS first_name,
        c.MID_NAME AS middle_name,
        c.PER_TITLE_SUFFIX AS suffix_name,
        fnx.CRRPT_FMT_CD AS degree,
        substr(btrim(ap.ADDR), 1, 75) AS address1,
        substr(btrim(ap.ADDR_LINE_2), 1, 75) AS address2,
        substr(btrim(ap.ADDR_LINE_3), 1, 75) AS address3,
        ap.CITY AS city,
        ap.STATE AS state,
        ap.ZIPCODE AS zip,
        c.WORK_PH_NUM AS phone,
        c.FAX_PH_NUM AS fax,
        c.CELL_PH_NUM AS mobile,
        c.EMAIL_ADDR AS email,
        ms.NAME AS prim_specialty,
        substr(btrim(l.LICENSE_NUM), 1, 20) AS state_license_number,
        l.STATE_CD AS state_license_state,
        CASE WHEN (l.X_OK_TO_SAMPLE_FLG = 'Y'::char(1)) THEN 'E'::varchar(1) ELSE 'I'::varchar(1) END AS state_license_elig_code,
        l.LICENSE_EXP_DT AS state_license_expir_date,
        substr(btrim(CASE WHEN ((btrim(fnx.CRRPT_FMT_CD) IS NOT NULL) AND (btrim(l.STATE_CD) IS NOT NULL) AND (btrim(l.LICENSE_NUM) IS NOT NULL)) THEN ((((btrim(fnx.CRRPT_FMT_CD) || '-'::varchar(1)) || btrim(l.STATE_CD)) || '-'::varchar(1)) || btrim(l.LICENSE_NUM)) ELSE NULL END), 1, 30) AS state_num,
        l.X_VALIDATION_DT AS sln_validation_date,
        CASE WHEN ((l.X_VALIDATION_DT IS NOT NULL) AND (l.X_OK_TO_SAMPLE_FLG = 'Y'::char(1))) THEN 'MedPro'::varchar(6) ELSE NULL END AS sln_validation_source,
        x.ATTRIB_09 AS no_spend,
        pc.X_ATTRIB_11 AS treats_es,
        CASE WHEN (p.X_SALES_FORCE = 'TC'::varchar(2)) THEN x.X_ATTRIB_58 ELSE NULL END AS nuvigil_dnc,
        CASE WHEN (p.X_SALES_FORCE = 'TC'::varchar(2)) THEN x.X_ATTRIB_83 ELSE NULL::"char" END AS nuvigil_rems_pb,
        CASE WHEN (p.X_SALES_FORCE = 'TC'::varchar(2)) THEN substr(x.X_ATTRIB_73, 1, 1) ELSE NULL END AS nuvigil_app,
        CASE WHEN (p.X_SALES_FORCE = 'TP'::varchar(2)) THEN x.X_ATTRIB_72 ELSE NULL END AS fentora_dnc,
        CASE WHEN (p.X_SALES_FORCE = 'TP'::varchar(2)) THEN x.X_ATTRIB_71 ELSE NULL::"char" END AS fentora_app,
        CASE WHEN (p.X_SALES_FORCE = 'TP'::varchar(2)) THEN x.ATTRIB_42 ELSE NULL END AS fentora_rems_status,
        pc.LAST_CALL_DT AS sfa_last_call_date,
        coalesce(cm2.CM_ID, cm1.CM_ID) AS cm_id,
        c.ROW_ID AS sfa_history_contact_row_id,
        ap.ROW_ID AS sfa_history_addr_per_row_id,
        'Y'::varchar(1) AS ora_viewable_flag,
        c.CREATED AS sfa_create_date,
        (statement_timestamp())::timestamp AS last_build_date,
        NULL AS ceph_id,
        CASE WHEN (length(c.INTEGRATION_ID) = 18) THEN c.INTEGRATION_ID ELSE NULL END AS veeva_account_id,
        pc.STATUS AS territory_status
 FROM (((((((((((sfa_history.s_contact c JOIN sfa_history.s_postn_con pc ON ((pc.CON_ID = c.ROW_ID))) JOIN sfa_history.s_postn p ON ((pc.POSTN_ID = p.ROW_ID))) JOIN sfa_history.s_org_ext o ON ((p.BU_ID = o.ROW_ID))) LEFT  JOIN sfa_history.s_contact_x x ON ((x.ROW_ID = c.ROW_ID))) LEFT  JOIN sfa_history.s_contact_fnx fnx ON ((fnx.ROW_ID = c.ROW_ID))) LEFT  JOIN sfa_history.s_addr_per ap ON ((ap.ROW_ID = pc.PR_ADDR_ID))) LEFT  JOIN sfa_history.s_med_spec ms ON ((ms.ROW_ID = c.MED_SPEC_ID))) LEFT  JOIN ( SELECT iq.ROW_ID,
        iq.CREATED,
        iq.CREATED_BY,
        iq.LAST_UPD,
        iq.LAST_UPD_BY,
        iq.MODIFICATION_NUM,
        iq.CONFLICT_ID,
        iq.ACTIVE_FLG,
        iq.ADDR_PER_ID,
        iq.BL_ADDR_FLG,
        iq.FRAUD_FLG,
        iq.MAIN_ADDR_FLG,
        iq.RELATION_TYPE_CD,
        iq.SHIP_ADDR_FLG,
        iq.DEA_EXPR_DT,
        iq.END_DT,
        iq.FRI_1ST_CLOSE_TM,
        iq.FRI_1ST_OPEN_TM,
        iq.FRI_2ND_CLOSE_TM,
        iq.FRI_2ND_OPEN_TM,
        iq.MON_1ST_CLOSE_TM,
        iq.MON_1ST_OPEN_TM,
        iq.MON_2ND_CLOSE_TM,
        iq.MON_2ND_OPEN_TM,
        iq.NUM_MONTHS_AT_ADDR,
        iq.SAT_1ST_CLOSE_TM,
        iq.SAT_1ST_OPEN_TM,
        iq.SAT_2ND_CLOSE_TM,
        iq.SAT_2ND_OPEN_TM,
        iq.START_DT,
        iq.SUN_1ST_CLOSE_TM,
        iq.SUN_1ST_OPEN_TM,
        iq.SUN_2ND_CLOSE_TM,
        iq.SUN_2ND_OPEN_TM,
        iq.THU_1ST_CLOSE_TM,
        iq.THU_1ST_OPEN_TM,
        iq.THU_2ND_CLOSE_TM,
        iq.THU_2ND_OPEN_TM,
        iq.TUE_1ST_CLOSE_TM,
        iq.TUE_1ST_OPEN_TM,
        iq.TUE_2ND_CLOSE_TM,
        iq.TUE_2ND_OPEN_TM,
        iq.WED_1ST_CLOSE_TM,
        iq.WED_1ST_OPEN_TM,
        iq.WED_2ND_CLOSE_TM,
        iq.WED_2ND_OPEN_TM,
        iq.ACCNT_ID,
        iq.ADDR_MAIL_CD,
        iq.ADDR_TYPE_CD,
        iq.BRICK_ID,
        iq.BU_ID,
        iq.CONTACT_ID,
        iq.DEA_NUM,
        iq.DFLT_SHIP_PRIO_CD,
        iq.EMAIL_ADDR,
        iq.FAX_PH_NUM,
        iq.MAIL_TYPE_CD,
        iq.OCCUPANCY_CD,
        iq.ORG_GROUP_ID,
        iq.PH_NUM,
        iq.TRNSPRT_ZONE_CD,
        iq.X_ATTRIB_01,
        iq.X_ATTRIB_02,
        iq.X_ATTRIB_03,
        iq.X_ATTRIB_04,
        iq.X_ATTRIB_05,
        iq.X_ATTRIB_06,
        iq.X_ATTRIB_07,
        iq.X_OK_TO_SAMPLE,
        iq.ADDRESSEE,
        iq.ALIGNMENT_FLG,
        iq.DB_LAST_UPD,
        iq.DB_LAST_UPD_SRC,
        iq.YEARLY_END_DT,
        iq.YEARLY_START_DT,
        iq.X_SRC_LAST_UPD,
        iq.rnk
 FROM ( SELECT sca.ROW_ID,
        sca.CREATED,
        sca.CREATED_BY,
        sca.LAST_UPD,
        sca.LAST_UPD_BY,
        sca.MODIFICATION_NUM,
        sca.CONFLICT_ID,
        sca.ACTIVE_FLG,
        sca.ADDR_PER_ID,
        sca.BL_ADDR_FLG,
        sca.FRAUD_FLG,
        sca.MAIN_ADDR_FLG,
        sca.RELATION_TYPE_CD,
        sca.SHIP_ADDR_FLG,
        sca.DEA_EXPR_DT,
        sca.END_DT,
        sca.FRI_1ST_CLOSE_TM,
        sca.FRI_1ST_OPEN_TM,
        sca.FRI_2ND_CLOSE_TM,
        sca.FRI_2ND_OPEN_TM,
        sca.MON_1ST_CLOSE_TM,
        sca.MON_1ST_OPEN_TM,
        sca.MON_2ND_CLOSE_TM,
        sca.MON_2ND_OPEN_TM,
        sca.NUM_MONTHS_AT_ADDR,
        sca.SAT_1ST_CLOSE_TM,
        sca.SAT_1ST_OPEN_TM,
        sca.SAT_2ND_CLOSE_TM,
        sca.SAT_2ND_OPEN_TM,
        sca.START_DT,
        sca.SUN_1ST_CLOSE_TM,
        sca.SUN_1ST_OPEN_TM,
        sca.SUN_2ND_CLOSE_TM,
        sca.SUN_2ND_OPEN_TM,
        sca.THU_1ST_CLOSE_TM,
        sca.THU_1ST_OPEN_TM,
        sca.THU_2ND_CLOSE_TM,
        sca.THU_2ND_OPEN_TM,
        sca.TUE_1ST_CLOSE_TM,
        sca.TUE_1ST_OPEN_TM,
        sca.TUE_2ND_CLOSE_TM,
        sca.TUE_2ND_OPEN_TM,
        sca.WED_1ST_CLOSE_TM,
        sca.WED_1ST_OPEN_TM,
        sca.WED_2ND_CLOSE_TM,
        sca.WED_2ND_OPEN_TM,
        sca.ACCNT_ID,
        sca.ADDR_MAIL_CD,
        sca.ADDR_TYPE_CD,
        sca.BRICK_ID,
        sca.BU_ID,
        sca.CONTACT_ID,
        sca.DEA_NUM,
        sca.DFLT_SHIP_PRIO_CD,
        sca.EMAIL_ADDR,
        sca.FAX_PH_NUM,
        sca.MAIL_TYPE_CD,
        sca.OCCUPANCY_CD,
        sca.ORG_GROUP_ID,
        sca.PH_NUM,
        sca.TRNSPRT_ZONE_CD,
        sca.X_ATTRIB_01,
        sca.X_ATTRIB_02,
        sca.X_ATTRIB_03,
        sca.X_ATTRIB_04,
        sca.X_ATTRIB_05,
        sca.X_ATTRIB_06,
        sca.X_ATTRIB_07,
        sca.X_OK_TO_SAMPLE,
        sca.ADDRESSEE,
        sca.ALIGNMENT_FLG,
        sca.DB_LAST_UPD,
        sca.DB_LAST_UPD_SRC,
        sca.YEARLY_END_DT,
        sca.YEARLY_START_DT,
        sca.X_SRC_LAST_UPD,
        row_number() OVER (PARTITION BY sca.CONTACT_ID, sca.ADDR_PER_ID ORDER BY sca.LAST_UPD DESC, sca.CREATED DESC) AS rnk
 FROM sfa_history.s_con_addr sca) iq
 WHERE (iq.rnk = 1)) ca ON (((ca.ADDR_PER_ID = pc.PR_ADDR_ID) AND (ca.CONTACT_ID = pc.CON_ID)))) LEFT  JOIN sfa_history.s_state_lic_ls l ON (((l.ROW_ID = ca.X_ATTRIB_02) AND (l.CONTACT_ID = ca.CONTACT_ID) AND (l.STATUS_CD <> 'Invalid'::varchar(7))))) LEFT  JOIN sfa_history.STG_CM_ID_XREF cm1 ON (((c.ROW_ID = cm1.ID_NUM) AND (cm1.ID_TYPE = 'sfa_histo'::varchar(9))))) LEFT  JOIN sfa_history.STG_CM_ID_XREF cm2 ON (((x.ATTRIB_03 = cm2.ID_NUM) AND (cm2.ID_TYPE = 'IMS_ID'::varchar(6)))))
 WHERE ((p.X_SALES_FORCE = ANY (ARRAY['TB'::varchar(2), 'TC'::varchar(2), 'TN'::varchar(2), 'TP'::varchar(2), 'TR'::varchar(2), 'TW'::varchar(2)])) AND (p.NAME !~~ '%sfa_historyAdministr'::varchar(21)) AND (p.NAME <> 'Align_2007'::varchar(10)) AND (NOT ((x.ATTRIB_03 IS NULL) AND (c.DEGREE = ANY (ARRAY['Billing Staff'::varchar(24), 'Office Staff'::varchar(24), 'Other Contact'::varchar(24), 'Pharmacist/Pharm D'::varchar(24), 'Practice Manager'::varchar(24), 'Refill Coordinator'::varchar(24), 'Reimbursement Specialist'::varchar(24)])))));

CREATE  VIEW sfa_history.v_siebel_samples_prof AS
SELECT ap.ROW_ID AS sample_id, ea.ROW_ID AS call_id, c.ROW_ID AS siebel_contact_row_id, CASE WHEN (length(c.INTEGRATION_ID) = 18) THEN c.INTEGRATION_ID ELSE NULL END AS veeva_account_id, trunc(ea.APPT_START_DT, 'DD'::varchar(2)) AS call_date, rep_p.X_SALES_FORCE AS sales_force_id, rep_p.NAME AS territory_num, ea.SUBTYPE_CD AS subtype_cd, ea.TODO_CD AS todo_cd, CASE WHEN (ap.RELATION_TYPE_CD = 'Direct Send'::varchar(11)) THEN 'REQUEST'::varchar(7) WHEN (ap.RELATION_TYPE_CD = 'Sample'::varchar(6)) THEN 'DROP'::varchar(4) ELSE 'UNKNOWN'::varchar(7) END AS sample_type, CASE WHEN (p.DESC_TEXT ~~ 'Adipex%'::varchar(7)) THEN 'ADIPEX-P'::varchar(8) WHEN (p.DESC_TEXT ~~ 'Amrix%'::varchar(6)) THEN 'AMRIX'::varchar(5) WHEN (p.DESC_TEXT ~~ 'Azilect%'::varchar(8)) THEN 'AZILECT'::varchar(7) WHEN (p.DESC_TEXT ~~ 'Budesonide%'::varchar(11)) THEN 'BUDESONIDE'::varchar(10) WHEN (p.DESC_TEXT ~~ 'COPAXONE%'::varchar(9)) THEN 'COPAXONE'::varchar(8) WHEN (p.DESC_TEXT ~~ 'ENJUVIA%'::varchar(8)) THEN 'ENJUVIA'::varchar(7) WHEN (p.DESC_TEXT ~~ 'LoSeasonique%'::varchar(13)) THEN 'LOSEASONIQUE'::varchar(12) WHEN (p.DESC_TEXT ~~ 'NIASPAN%'::varchar(8)) THEN 'NIASPAN'::varchar(7) WHEN (p.DESC_TEXT ~~ 'Nuvigil%'::varchar(8)) THEN 'NUVIGIL'::varchar(7) WHEN (p.DESC_TEXT ~~ 'ProAir%'::varchar(7)) THEN 'PROAIR'::varchar(6) WHEN (p.DESC_TEXT ~~ 'Qnasl%'::varchar(6)) THEN 'QNASL'::varchar(5) WHEN (p.DESC_TEXT ~~ 'QVAR%'::varchar(5)) THEN 'QVAR'::varchar(4) WHEN (p.DESC_TEXT ~~ 'Seasonique%'::varchar(11)) THEN 'SEASONIQUE'::varchar(10) WHEN (p.DESC_TEXT ~~ 'Tev-Tropin%'::varchar(11)) THEN 'TEV-TROPIN'::varchar(10) ELSE 'UNKNOWN'::varchar(7) END AS product_name, p.DESC_TEXT AS sample_name, p.PART_NUM AS sample_ndc, ap.QTY AS qty, ea.NAME AS name_on_call, ea.COMMENTS AS address_line_on_call, ea.ZIPCODE AS zip_on_call, d.ims_id, eax.ATTRIB_03 AS dea_num, ea.OWNER_PER_ID AS ownerid, emp.CSN AS employeenumber, ea.CREATED_BY AS created_by, ea.CREATED AS created_date FROM (((((((sfa_history.s_evt_act ea JOIN sfa_history.s_contact c ON ((ea.TARGET_PER_ID = c.ROW_ID))) JOIN sfa_history.s_postn rep_p ON ((ea.OWNER_POSTN_ID = rep_p.ROW_ID))) JOIN sfa_history.s_act_prdint ap ON ((ea.ROW_ID = ap.ACTIVITY_ID))) JOIN sfa_history.s_prod_int p ON ((ap.PRDINT_ID = p.ROW_ID))) LEFT JOIN sfa_history.s_evt_act_x eax ON ((ea.ROW_ID = eax.ROW_ID))) LEFT JOIN sfa_history.s_contact emp ON ((emp.ROW_ID = ea.CREATED_BY))) LEFT JOIN (SELECT iq.ims_id, iq.cm_id, iq.me_num, iq.siebel_contact_row_id, iq.rnk FROM (SELECT DIM_SFA_CSF_DEMO.IMS_ID AS ims_id, DIM_SFA_CSF_DEMO.CM_ID AS cm_id, DIM_SFA_CSF_DEMO.ME_NUM AS me_num, DIM_SFA_CSF_DEMO.SIEBEL_CONTACT_ROW_ID AS siebel_contact_row_id, row_number() OVER (PARTITION BY DIM_SFA_CSF_DEMO.SIEBEL_CONTACT_ROW_ID ORDER BY DIM_SFA_CSF_DEMO.VEEVA_ACCOUNT_ID, DIM_SFA_CSF_DEMO.SALES_FORCE_ID) AS rnk FROM WSMP_ADMIN.DIM_SFA_CSF_DEMO) iq WHERE (iq.rnk = 1)) d ON ((c.ROW_ID = d.siebel_contact_row_id))) WHERE ((rep_p.POSTN_TYPE_CD = ANY (ARRAY['Sales Representative'::varchar(20), 'TSP Test Position'::varchar(17)])) AND (ap.RELATION_TYPE_CD = ANY (ARRAY['Direct Send'::varchar(11), 'Sample'::varchar(6)])) AND (ea.OWNER_POSTN_ID <> '0-5220'::varchar(6)) AND (ea.APPT_START_DT >= '2012-01-01 00:00:00'::timestamp(0)) AND (ea.APPT_START_DT < (statement_timestamp())::timestamp));

CREATE  VIEW sfa_history.v_siebel_calls AS
 SELECT rep_p.X_SALES_FORCE AS sales_force_id,
        ea.PAR_EVT_ID AS par_evt_id,
        ea.ROW_ID AS csf_call_id,
        ea.TARGET_PER_ID AS csf_demo_id,
        'PROF'::varchar(4) AS legacy_call_type,
        ea.NAME AS name_on_call,
        ea.ZIPCODE AS zip_on_call,
        ea.SUBTYPE_CD AS subtype_cd,
        ea.TODO_CD AS todo_cd,
        ea.INTEGRATION_ID AS integration_id,
        ea.ROW_ID AS sfa_history_evt_act_row_id,
        ea.TARGET_PER_ID AS siebel_target_per_id,
        d.ims_id,
        d.cm_id,
        d.me_num,
        ca.DEA_NUM AS dea_num,
        emp.CSN AS rep_id,
        rep_p.NAME AS territory_num,
        trunc(ea.APPT_START_DT, 'DD'::varchar(2)) AS call_date,
        details.first_detailed_product_id,
        details.first_detailed_product,
        details.second_detailed_product_id,
        details.second_detailed_product,
        details.third_detailed_product_id,
        details.third_detailed_product,
        details.fourth_detailed_product_id,
        details.fourth_detailed_product,
        details.fifth_detailed_product_id,
        details.fifth_detailed_product,
        details.sixth_detailed_product_id,
        details.sixth_detailed_product,
        CASE WHEN (length(c.INTEGRATION_ID) = 18) THEN c.INTEGRATION_ID ELSE NULL END AS veeva_account_id
 FROM (((((((sfa_history.s_evt_act ea JOIN sfa_history.s_contact c ON ((c.ROW_ID = ea.TARGET_PER_ID))) LEFT  JOIN sfa_history.s_contact_x x ON ((x.ROW_ID = c.ROW_ID))) JOIN sfa_history.s_postn rep_p ON ((rep_p.ROW_ID = ea.OWNER_POSTN_ID))) LEFT  JOIN sfa_history.s_contact emp ON ((emp.ROW_ID = ea.CREATED_BY))) LEFT  JOIN ( SELECT iq.ims_id,
        iq.cm_id,
        iq.me_num,
        iq.sfa_history_contact_row_id,
        iq.rnk
 FROM ( SELECT v_siebel_demo.ims_id,
        v_siebel_demo.cm_id,
        v_siebel_demo.me_num,
        v_siebel_demo.sfa_history_contact_row_id,
        row_number() OVER (PARTITION BY v_siebel_demo.sfa_history_contact_row_id ORDER BY v_siebel_demo.veeva_account_id, v_siebel_demo.sales_force_id) AS rnk
 FROM sfa_history.v_siebel_demo) iq
 WHERE (iq.rnk = 1)) d ON ((c.ROW_ID = d.sfa_history_contact_row_id))) LEFT  JOIN ( SELECT iq2.ROW_ID,
        iq2.CREATED,
        iq2.CREATED_BY,
        iq2.LAST_UPD,
        iq2.LAST_UPD_BY,
        iq2.MODIFICATION_NUM,
        iq2.CONFLICT_ID,
        iq2.ACTIVE_FLG,
        iq2.ADDR_PER_ID,
        iq2.BL_ADDR_FLG,
        iq2.FRAUD_FLG,
        iq2.MAIN_ADDR_FLG,
        iq2.RELATION_TYPE_CD,
        iq2.SHIP_ADDR_FLG,
        iq2.DEA_EXPR_DT,
        iq2.END_DT,
        iq2.FRI_1ST_CLOSE_TM,
        iq2.FRI_1ST_OPEN_TM,
        iq2.FRI_2ND_CLOSE_TM,
        iq2.FRI_2ND_OPEN_TM,
        iq2.MON_1ST_CLOSE_TM,
        iq2.MON_1ST_OPEN_TM,
        iq2.MON_2ND_CLOSE_TM,
        iq2.MON_2ND_OPEN_TM,
        iq2.NUM_MONTHS_AT_ADDR,
        iq2.SAT_1ST_CLOSE_TM,
        iq2.SAT_1ST_OPEN_TM,
        iq2.SAT_2ND_CLOSE_TM,
        iq2.SAT_2ND_OPEN_TM,
        iq2.START_DT,
        iq2.SUN_1ST_CLOSE_TM,
        iq2.SUN_1ST_OPEN_TM,
        iq2.SUN_2ND_CLOSE_TM,
        iq2.SUN_2ND_OPEN_TM,
        iq2.THU_1ST_CLOSE_TM,
        iq2.THU_1ST_OPEN_TM,
        iq2.THU_2ND_CLOSE_TM,
        iq2.THU_2ND_OPEN_TM,
        iq2.TUE_1ST_CLOSE_TM,
        iq2.TUE_1ST_OPEN_TM,
        iq2.TUE_2ND_CLOSE_TM,
        iq2.TUE_2ND_OPEN_TM,
        iq2.WED_1ST_CLOSE_TM,
        iq2.WED_1ST_OPEN_TM,
        iq2.WED_2ND_CLOSE_TM,
        iq2.WED_2ND_OPEN_TM,
        iq2.ACCNT_ID,
        iq2.ADDR_MAIL_CD,
        iq2.ADDR_TYPE_CD,
        iq2.BRICK_ID,
        iq2.BU_ID,
        iq2.CONTACT_ID,
        iq2.DEA_NUM,
        iq2.DFLT_SHIP_PRIO_CD,
        iq2.EMAIL_ADDR,
        iq2.FAX_PH_NUM,
        iq2.MAIL_TYPE_CD,
        iq2.OCCUPANCY_CD,
        iq2.ORG_GROUP_ID,
        iq2.PH_NUM,
        iq2.TRNSPRT_ZONE_CD,
        iq2.X_ATTRIB_01,
        iq2.X_ATTRIB_02,
        iq2.X_ATTRIB_03,
        iq2.X_ATTRIB_04,
        iq2.X_ATTRIB_05,
        iq2.X_ATTRIB_06,
        iq2.X_ATTRIB_07,
        iq2.X_OK_TO_SAMPLE,
        iq2.ADDRESSEE,
        iq2.ALIGNMENT_FLG,
        iq2.DB_LAST_UPD,
        iq2.DB_LAST_UPD_SRC,
        iq2.YEARLY_END_DT,
        iq2.YEARLY_START_DT,
        iq2.X_SRC_LAST_UPD,
        iq2.rnk
 FROM ( SELECT ca.ROW_ID,
        ca.CREATED,
        ca.CREATED_BY,
        ca.LAST_UPD,
        ca.LAST_UPD_BY,
        ca.MODIFICATION_NUM,
        ca.CONFLICT_ID,
        ca.ACTIVE_FLG,
        ca.ADDR_PER_ID,
        ca.BL_ADDR_FLG,
        ca.FRAUD_FLG,
        ca.MAIN_ADDR_FLG,
        ca.RELATION_TYPE_CD,
        ca.SHIP_ADDR_FLG,
        ca.DEA_EXPR_DT,
        ca.END_DT,
        ca.FRI_1ST_CLOSE_TM,
        ca.FRI_1ST_OPEN_TM,
        ca.FRI_2ND_CLOSE_TM,
        ca.FRI_2ND_OPEN_TM,
        ca.MON_1ST_CLOSE_TM,
        ca.MON_1ST_OPEN_TM,
        ca.MON_2ND_CLOSE_TM,
        ca.MON_2ND_OPEN_TM,
        ca.NUM_MONTHS_AT_ADDR,
        ca.SAT_1ST_CLOSE_TM,
        ca.SAT_1ST_OPEN_TM,
        ca.SAT_2ND_CLOSE_TM,
        ca.SAT_2ND_OPEN_TM,
        ca.START_DT,
        ca.SUN_1ST_CLOSE_TM,
        ca.SUN_1ST_OPEN_TM,
        ca.SUN_2ND_CLOSE_TM,
        ca.SUN_2ND_OPEN_TM,
        ca.THU_1ST_CLOSE_TM,
        ca.THU_1ST_OPEN_TM,
        ca.THU_2ND_CLOSE_TM,
        ca.THU_2ND_OPEN_TM,
        ca.TUE_1ST_CLOSE_TM,
        ca.TUE_1ST_OPEN_TM,
        ca.TUE_2ND_CLOSE_TM,
        ca.TUE_2ND_OPEN_TM,
        ca.WED_1ST_CLOSE_TM,
        ca.WED_1ST_OPEN_TM,
        ca.WED_2ND_CLOSE_TM,
        ca.WED_2ND_OPEN_TM,
        ca.ACCNT_ID,
        ca.ADDR_MAIL_CD,
        ca.ADDR_TYPE_CD,
        ca.BRICK_ID,
        ca.BU_ID,
        ca.CONTACT_ID,
        ca.DEA_NUM,
        ca.DFLT_SHIP_PRIO_CD,
        ca.EMAIL_ADDR,
        ca.FAX_PH_NUM,
        ca.MAIL_TYPE_CD,
        ca.OCCUPANCY_CD,
        ca.ORG_GROUP_ID,
        ca.PH_NUM,
        ca.TRNSPRT_ZONE_CD,
        ca.X_ATTRIB_01,
        ca.X_ATTRIB_02,
        ca.X_ATTRIB_03,
        ca.X_ATTRIB_04,
        ca.X_ATTRIB_05,
        ca.X_ATTRIB_06,
        ca.X_ATTRIB_07,
        ca.X_OK_TO_SAMPLE,
        ca.ADDRESSEE,
        ca.ALIGNMENT_FLG,
        ca.DB_LAST_UPD,
        ca.DB_LAST_UPD_SRC,
        ca.YEARLY_END_DT,
        ca.YEARLY_START_DT,
        ca.X_SRC_LAST_UPD,
        row_number() OVER (PARTITION BY ca.CONTACT_ID, ca.ADDR_PER_ID ORDER BY ca.LAST_UPD DESC, ca.CREATED DESC) AS rnk
 FROM sfa_history.s_con_addr ca) iq2
 WHERE (iq2.rnk = 1)) ca ON (((ca.ADDR_PER_ID = ea.TARGET_PER_ADDR_ID) AND (ca.CONTACT_ID = ea.TARGET_PER_ID)))) LEFT  JOIN ( SELECT d.activity_id,
        max(CASE WHEN (d.priority = 1) THEN d.product_id ELSE NULL END) AS first_detailed_product_id,
        max(CASE WHEN (d.priority = 1) THEN d.product_name ELSE NULL END) AS first_detailed_product,
        max(CASE WHEN (d.priority = 2) THEN d.product_id ELSE NULL END) AS second_detailed_product_id,
        max(CASE WHEN (d.priority = 2) THEN d.product_name ELSE NULL END) AS second_detailed_product,
        max(CASE WHEN (d.priority = 3) THEN d.product_id ELSE NULL END) AS third_detailed_product_id,
        max(CASE WHEN (d.priority = 3) THEN d.product_name ELSE NULL END) AS third_detailed_product,
        max(CASE WHEN (d.priority = 4) THEN d.product_id ELSE NULL END) AS fourth_detailed_product_id,
        max(CASE WHEN (d.priority = 4) THEN d.product_name ELSE NULL END) AS fourth_detailed_product,
        max(CASE WHEN (d.priority = 5) THEN d.product_id ELSE NULL END) AS fifth_detailed_product_id,
        max(CASE WHEN (d.priority = 5) THEN d.product_name ELSE NULL END) AS fifth_detailed_product,
        max(CASE WHEN (d.priority = 6) THEN d.product_id ELSE NULL END) AS sixth_detailed_product_id,
        max(CASE WHEN (d.priority = 6) THEN d.product_name ELSE NULL END) AS sixth_detailed_product
 FROM ( SELECT appl.ACTIVITY_ID AS activity_id,
        spi.PRODUCT_ID AS product_id,
        upper(spi.NAME) AS product_name,
        row_number() OVER (PARTITION BY appl.ACTIVITY_ID ORDER BY appl.PRIORITY_NUM, upper(spi.NAME)) AS priority
 FROM (sfa_history.s_act_prod_appl appl LEFT  JOIN sfa_history.s_prod_int spi ON ((appl.PRDINT_ID = spi.ROW_ID)))
 WHERE (appl.CONFLICT_ID = '0'::varchar(1))) d
 GROUP BY d.activity_id) details ON ((details.activity_id = ea.PAR_EVT_ID)))
 WHERE ((ea.EVT_STAT_CD = 'Submitted'::varchar(9)) AND (rep_p.POSTN_TYPE_CD = ANY (ARRAY['Sales Representative'::varchar(20), 'TSP Test Position'::varchar(17)])) AND (ea.OWNER_POSTN_ID <> '0-5220'::varchar(6)) AND (((ea.APPT_START_DT >= '2012-01-01 00:00:00'::timestamp) AND (rep_p.X_SALES_FORCE = ANY (ARRAY['TB'::varchar(2), 'TN'::varchar(2), 'TR'::varchar(2), 'TW'::varchar(2)]))) OR ((ea.APPT_START_DT >= '2012-03-01 00:00:00'::timestamp) AND (rep_p.X_SALES_FORCE = ANY (ARRAY['TC'::varchar(2), 'TP'::varchar(2)])))) AND (ea.APPT_START_DT < (statement_timestamp())::timestamp) AND (ea.SUBTYPE_CD = ANY (ARRAY['Contact Call'::varchar(13), 'Attendee Call'::varchar(13)])) AND ((ea.TODO_CD ~~ '%Detail%'::varchar(8)) OR (ea.TODO_CD ~~ '%Call%'::varchar(6))));