CREATE ROLE "CDWAdmin";
CREATE ROLE "DataIntegration";
CREATE ROLE "DataburstUpdateUser";
CREATE ROLE "HPSDevOpsUser";
CREATE ROLE "HPSDevOpsViewer";
CREATE ROLE "ITDevOpsUser";
CREATE ROLE "InboundETLUser";
CREATE ROLE "ONCADJ_ADMIN";
CREATE ROLE "OraSuperUser";
CREATE ROLE "ProductAdmin";
CREATE ROLE "TableauUser";
CREATE ROLE "TevaBusinessUser";
CREATE ROLE "TevaDataSuperUser";
CREATE ROLE "TevaITUser";
CREATE ROLE "TevaMDMUser";
CREATE ROLE "sys_catalog_role";
CREATE USER "AWANG02" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "BEinersen" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "CDW_Admin" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "CDW_EXTRACT" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "CDW_Reporting" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "CDW_User" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "Databurst_Updt" RESOURCE POOL tevauser_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "FieldOps" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "ITAdhoc" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "Kscarani" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "MCM_Tableau" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "MDM_ETL" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "MKHAN14" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "Marketacc" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "ONCADJ" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "PKONIARIS" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "ProductAdminUser" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "SalesOps" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "VRao" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "aalvarez" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "abrennan" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "adong01" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "agokhman" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "akashyap" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "akramer" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "alarkins" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "aschmidt" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "asudhaka" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "aswaminath" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "bfages" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "bkoziol" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "boberkro" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "cchalla" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "ccompton" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "cdigiacomo" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "cdw_rpa" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "chriskim" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "cmason01" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "cmchenry" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "cmeyer" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "cstoeben" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "cwilliam05" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "dallen04" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "dconklin" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "di_user" RESOURCE POOL diuser_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "dluscomb" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "dpence" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "dwhite03" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "eaquino" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "ecs" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "egunders" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "ehalabe" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "ejiang" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "ekane" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "gattili02" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "gmartin" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "gmwhite" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "gobrien01" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "harli" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "hdyer" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "hmohamma" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "impersonation_CDWAdmin" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_DataIntegration" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_DataburstUpdateUser" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_HPSDevOpsUser" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_ITDevOpsUser" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_InboundETLUser" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_ONCADJ_ADMIN" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_ProductAdmin" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_TableauUser" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_TevaBusinessUser" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_TevaDataSuperUser" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_TevaITUser" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "impersonation_TevaMDMUser" RESOURCE POOL superset_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "integration_user" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "jbutler01" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "jchung" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "jmayhew" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "jmorrow" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "jonahuy" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "jpeng01" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "jrizzo" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "jsmith11" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "jsteadman" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "jstruthe" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "kavyag" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "kbixler" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "kerker" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "kgantenapa" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "kgantenapa01" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "ksinclai" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "ksubramani03" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "lshelton" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "m_habeeb" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "mbhawsar" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "mcapehar" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "mfletcher01" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "mlundt" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "mophif" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "moshaughnessy" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "mramsuesmi" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "mvvergar" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "nreigel" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "nreigel02" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "nshanfelt" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "nwright02" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "pmanto" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "ppatel40" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "prathaps" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "psingh22" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "pwilson" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "qa_user" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "rashmiraj" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "rbansal01" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "rgopaluni01" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "rkrutsic" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "rkrutsic_nl" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "rmotley" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "rohit.amarnath" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "rrajendr" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "rweinsch" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "smcnulty02" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "smukku" ACCOUNT LOCK SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "snandan" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "spatkar" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "sqlpad" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "sramamur" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "ssurana" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "sthomas1" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "syengalwar01" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "system_monitor" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "tableau_user" RESOURCE POOL diuser_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "teva_user" ACCOUNT LOCK RESOURCE POOL tevauser_pool SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "tkeys" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "tmcdowel" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "tmoore02" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "tokeefe" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "tryan01" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "twhalen" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "twoltkam" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal;
CREATE USER "vertica_admin" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "yagarwal" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
CREATE USER "yzhao03" SEARCH_PATH "$user", public, v_catalog, v_monitor, v_internal, v_func;
