CREATE SCHEMA datamart;


CREATE TABLE datamart.touchpoint_presentation
(
    call_id int,
    call_attempt_id int,
    presentation_id int,
    product varchar(50),
    "position" int,
    item_type varchar(50),
    item_description varchar(100),
    quantity float,
    basket_id int,
    basket_name varchar(300),
    file_id int,
    record_id int
);


CREATE TABLE datamart.plantrak_workbook
(
    payer_number varchar(6),
    payer_name varchar(100),
    payer_parent_number varchar(6),
    payer_parent_name varchar(100),
    plan_number varchar(4),
    payer_plan_number varchar(10) NOT NULL,
    plan_name varchar(100),
    model varchar(10),
    method_of_payment varchar(250),
    city varchar(30),
    hq_state varchar(2),
    operating_state varchar(2),
    months_with_data varchar(4),
    pbm_number varchar(6),
    pbm_name varchar(100),
    pbm_parent varchar(6),
    pbm_parent_name varchar(100),
    file_id int NOT NULL,
    record_id int NOT NULL,
    CONSTRAINT PK_plantrak_workbook PRIMARY KEY (payer_plan_number) ENABLED
);


CREATE TABLE datamart.mm_ram_to_rsm
(
    mm_ram varchar(40),
    state varchar(8),
    rsm varchar(40)
);


CREATE TABLE datamart.call_plan
(
    sales_force_id varchar(5),
    period varchar(20),
    veeva_account_id varchar(18),
    ims_id varchar(10),
    first_name varchar(50),
    last_name varchar(50),
    specialty varchar(100),
    area_number varchar(8),
    region_number varchar(8),
    territory_number varchar(8),
    basket_id int,
    basket_name varchar(300),
    p1 int,
    p2 int,
    p3 int,
    file_id int,
    record_id int,
    tvcmid int
);


CREATE TABLE datamart.cmop_rx
(
    data_month date,
    comp_month date,
    pharmacy varchar(100),
    visn varchar(2),
    station_number varchar(10),
    station varchar(50),
    va_product varchar(70),
    basket_id int,
    basket_name varchar(300),
    cmop_rxs_raw numeric(37,15),
    cmop_rxs_normalized numeric(37,15),
    total_quantity numeric(37,15),
    cmop_quantity numeric(37,15),
    rxs_30_days numeric(37,15),
    zip varchar(5),
    id varchar(10),
    file_id int,
    record_id int,
    rollup_flag char(1),
    basket_type varchar(100),
    total_rxs_normalized numeric(37,15)
);


CREATE TABLE datamart.rems_pharmacy
(
    enrollment_id varchar(20),
    pharmacy_type varchar(20),
    pharmacy_name varchar(200),
    address_line_1 varchar(40),
    address_line_2 varchar(40),
    city varchar(40),
    state varchar(2),
    zip varchar(5),
    phone varchar(10),
    file_id int,
    record_id int,
    ncpdp varchar(20),
    dea_num varchar(20),
    status varchar(60),
    license_number varchar(20),
    obsolescence_reason varchar(64),
    obsolescence_date date,
    last_build_date date,
    channel varchar(20),
    effective_date date,
    expiration_date date,
    first_name varchar(36),
    in_progress_step varchar(40),
    last_name varchar(40),
    middle_name varchar(36),
    program_id varchar(10),
    program_name varchar(48)
);


CREATE TABLE datamart.customer_hco_demographics
(
    tvcmid int,
    ims_org_id varchar(11),
    npi varchar(10),
    hin varchar(18),
    outlet_code varchar(18),
    business_name varchar(80),
    address_line1 varchar(80),
    address_line2 varchar(80),
    city varchar(40),
    state_code varchar(2),
    zip varchar(5),
    cot_classification varchar(50),
    cot_facility_type varchar(50),
    cot_specialty varchar(50),
    file_id int,
    record_id int,
    address_id int,
    address_latitude varchar(20),
    address_longitude varchar(20)
);


CREATE TABLE datamart.customer_level_flags
(
    tvcmid int,
    basket_id int,
    basket_name varchar(300),
    territory_number varchar(8),
    sales_force_id varchar(2),
    flag_type varchar(50),
    flag_value varchar(50),
    flag_effective_start_date timestamp,
    flag_effective_end_date timestamp,
    file_id int,
    record_id int
);


CREATE TABLE datamart.do_not_promote
(
    tvcmid int,
    first_name varchar(50),
    last_name varchar(50),
    zip varchar(5)
);


CREATE TABLE datamart.tvcmid_xref
(
    tvcmid int,
    id_num varchar(255),
    id_type varchar(14),
    state varchar(2),
    file_id int,
    record_id int,
    status varchar(10)
);


CREATE TABLE datamart.oncology_adjusted_sales
(
    acct_demo_id int,
    outlet_name varchar(100),
    outlet_zip varchar(5),
    basket_id int,
    basket_name varchar(300),
    date date,
    rollup_week date,
    rollup_month date,
    source_quantity float,
    source_dollars float,
    adjustment_quantity float,
    adjustment_dollars float,
    reported_quantity float,
    reported_dollars float,
    data_date date,
    file_id int,
    record_id int,
    reported_trx_strength_units float,
    report_frequency varchar(20),
    rollup_flag char(1),
    basket_type varchar(100),
    rollup_445_month date,
    tvcmid int,
    sales_force_id varchar(10)
);


CREATE TABLE datamart.oncology_sales_adjustments
(
    adjustment_type varchar(50),
    adjustment_description varchar(200),
    acct_demo_id int,
    outlet_name varchar(100),
    adjustment_month date,
    adjustment_start_date date,
    adjustment_end_date date,
    basket_id int,
    basket_name varchar(50),
    adjustment_quantity float,
    adjustment_dollars float,
    tvcmid int
);


CREATE TABLE datamart.specialty_pharmacy_enrollment
(
    specialty_pharmacy_name varchar(50),
    patient_id varchar(80),
    rx_received_date date,
    insurance_information varchar(200),
    most_recent_cml_treatment varchar(200),
    basket_id int,
    basket_name varchar(300),
    date_of_discontinuation date,
    reason_for_discontinuation varchar(200),
    physician_last_name varchar(200),
    physician_first_name varchar(200),
    physician_address varchar(400),
    physician_city varchar(200),
    physician_state varchar(8),
    physician_zip varchar(40),
    file_id int,
    record_id int,
    tvcmid int
);


CREATE TABLE datamart.chargebacks
(
    account_id varchar(100),
    location_id varchar(100),
    shipment_date date,
    ndc_code varchar(20),
    basket_id int,
    basket_name varchar(300),
    product_name varchar(100),
    contract_id varchar(100),
    chargeback_quantity numeric(37,15),
    chargeback_amount numeric(37,15),
    receipt_date date,
    debit_memo_number varchar(30),
    credit_memo_date date,
    credit_memo_number varchar(30),
    settlement_date timestamp,
    contract_price numeric(37,15),
    file_id int,
    record_id int,
    unit_ap float,
    ap float,
    tvcmid int
);


CREATE TABLE datamart.sfa_reprints
(
    sales_force_id varchar(2),
    territory_number varchar(8),
    product_name varchar(80),
    promo_item_id int,
    promo_item_name varchar(300),
    distribution_date date,
    quantity int,
    reprint_name varchar(150),
    reprint_id varchar(30),
    call_id varchar(20),
    veeva_sample_id varchar(20),
    rep_id varchar(20),
    rep_first_name varchar(50),
    rep_last_name varchar(50),
    veeva_account_id varchar(20),
    ims_id varchar(10),
    prescriber_first_name varchar(50),
    prescriber_last_name varchar(50),
    name_on_call varchar(150),
    zip_on_call varchar(30),
    area_number varchar(8),
    region_number varchar(8),
    tvcmid int,
    basket_id int,
    basket_name varchar(300)
);


CREATE TABLE datamart.sfa_sample
(
    sample_id varchar(20),
    call_id varchar(20),
    veeva_account_id varchar(20),
    ims_id varchar(10),
    call_date date,
    sales_force_id varchar(2),
    territory_number varchar(8),
    call_type varchar(50),
    attendee_type varchar(50),
    customer_type varchar(50),
    sample_type varchar(10),
    product_name varchar(80),
    sample_name varchar(80),
    sample_ndc varchar(50),
    basket_id int,
    basket_name varchar(300),
    qty int,
    name_on_call varchar(100),
    zip_on_call varchar(10),
    dea_num varchar(9),
    ownerid varchar(20),
    employee_number varchar(20),
    employee_first_name varchar(50),
    employee_last_name varchar(50),
    parent_call_id varchar(20),
    created_by varchar(20),
    created_date date,
    area_number varchar(8),
    region_number varchar(8),
    tvcmid int,
    how_executed varchar(40)
);


CREATE TABLE datamart.affiliations
(
    ims_org_id varchar(15),
    business_name varchar(80),
    hce_id_prfsnl varchar(64),
    professional_id int,
    ims_id varchar(10),
    first_name varchar(40),
    last_name varchar(80),
    affiliation_type_code varchar(10),
    affiliation_type_description varchar(50),
    affiliation_group_description varchar(50),
    affiliation_indicator varchar(1),
    affiliation_rank int,
    file_id int,
    record_id int,
    professional_tvcmid int,
    org_tvcmid int
);


CREATE TABLE datamart.patient_months_count
(
    tvcmid int,
    ims_id varchar(10),
    npi varchar(20),
    ims_surrogate_patient_id varchar(20),
    basket_id int,
    basket_name varchar(300),
    indication varchar(20),
    approved_indication varchar(5),
    rollup_shipment_month date,
    patient_months numeric(37,15),
    dispense_type_code varchar(50),
    dispense_type varchar(500)
);


CREATE TABLE datamart.psr_enrollment
(
    veeva_account_id varchar(20),
    ims_id varchar(10),
    npi varchar(10),
    tvcmid int,
    basket_name varchar(300),
    basket_id int,
    indication varchar(5),
    prescriber_last_name varchar(80),
    prescriber_first_name varchar(50),
    prescriber_middle_name varchar(50),
    specialty_code varchar(255),
    prescriber_date date,
    in_progress_count int,
    completed_count int,
    cancelled_count int,
    prescriber_count int,
    week_ending date,
    file_id int,
    record_id int
);


CREATE TABLE datamart.psr_enrollment_rej
(
    file_id int,
    record_id int,
    null_npi varchar(5),
    null_lkp_veeva_id varchar(5),
    null_lkp_ims_id varchar(5),
    count_mismatch varchar(5),
    week_ending date,
    npi varchar(10)
);


CREATE TABLE datamart.rems_prescriber
(
    first_name varchar(36),
    last_name varchar(40),
    site_name varchar(200),
    address_line_1 varchar(50),
    address_line_2 varchar(40),
    city varchar(40),
    state varchar(2),
    zip varchar(5),
    phone varchar(10),
    npi varchar(10),
    dea_num varchar(20),
    file_id int,
    record_id int,
    enrollment_id varchar(20),
    program_id varchar(10),
    program_name varchar(48),
    status varchar(60),
    in_progress_step varchar(40),
    effective_date date,
    expiration_date date,
    prescriber_tvcmid int,
    ppaf_count int,
    channel varchar(20),
    middle_name varchar(36),
    obsolescence_date date
);


CREATE TABLE datamart.dddmd_demographics_detail
(
    account_demo_id int,
    outlet_code varchar(10),
    ims_facility_number varchar(11),
    ims_prescriber_number varchar(7),
    category_code varchar(10),
    subcategory_code varchar(2),
    alignment_zip varchar(5),
    outlet_name varchar(100),
    outlet_address varchar(120),
    outlet_city varchar(40),
    outlet_state varchar(2),
    outlet_zip varchar(5),
    facility_name varchar(100),
    facility_address1 varchar(60),
    facility_address2 varchar(60),
    facility_address3 varchar(60),
    facility_address4 varchar(60),
    facility_city varchar(40),
    facility_state varchar(2),
    facility_zip varchar(5),
    prescriber_name varchar(100),
    prescriber_address1 varchar(60),
    prescriber_address2 varchar(60),
    prescriber_address3 varchar(60),
    prescriber_address4 varchar(60),
    prescriber_city varchar(40),
    prescriber_state varchar(2),
    prescriber_zip varchar(5),
    account_status varchar(1),
    tvcmid int,
    sales_force_id varchar(2),
    outlet_tvcmid int,
    facility_tvcmid int,
    prescriber_tvcmid int,
    tvcmid_assignment_rule varchar(25)
);


CREATE TABLE datamart.prescriber_rx_qty_base
(
    ims_id varchar(10),
    payer_plan_number varchar(10),
    ims_client_number varchar(64),
    report_frequency varchar(10),
    ims_product_group varchar(64),
    basket_id int,
    data_date date,
    date date,
    sales_category varchar(64),
    tvcmid int,
    prescriber_first_name varchar(25),
    prescriber_last_name varchar(25),
    basket_name varchar(300),
    basket_type varchar(100),
    rollup_week date,
    rollup_month date,
    nrx_count numeric(18,3),
    trx_count numeric(18,3),
    nrx_quantity numeric(18,3),
    trx_quantity numeric(18,3),
    unnormalized_nrx_count numeric(18,3),
    unnormalized_trx_count numeric(18,3),
    market_name varchar(300),
    payer_name varchar(100),
    plan_name varchar(100),
    pbm_name varchar(100),
    model varchar(10),
    payment_method varchar(250),
    ims_specialty varchar(10),
    ims_rx_type varchar(1),
    ims_supplemental_data varchar(20),
    zip_other varchar(10),
    ims_report_number varchar(64),
    file_id int,
    record_id int,
    ims_report_number_cnt varchar(5),
    indication varchar(20),
    pbm_parent_name varchar(100),
    load_step int
) INCLUDE SCHEMA PRIVILEGES;


CREATE TABLE datamart.prescriber_rx_cnt_base
(
    ims_id varchar(10),
    payer_plan_number varchar(10),
    ims_client_number varchar(64),
    report_frequency varchar(10),
    ims_product_group varchar(64),
    basket_id int,
    data_date date,
    date date,
    sales_category varchar(64),
    tvcmid int,
    prescriber_first_name varchar(25),
    prescriber_last_name varchar(25),
    basket_name varchar(300),
    basket_type varchar(100),
    rollup_week date,
    rollup_month date,
    nrx_count numeric(18,3),
    trx_count numeric(18,3),
    nrx_quantity numeric(18,3),
    trx_quantity numeric(18,3),
    unnormalized_nrx_count numeric(18,3),
    unnormalized_trx_count numeric(18,3),
    market_name varchar(300),
    payer_name varchar(100),
    plan_name varchar(100),
    pbm_name varchar(100),
    model varchar(10),
    payment_method varchar(250),
    ims_specialty varchar(10),
    ims_rx_type varchar(1),
    ims_supplemental_data varchar(20),
    zip_other varchar(10),
    ims_report_number varchar(64),
    file_id int,
    record_id int,
    ims_report_number_qty varchar(5),
    indication varchar(20),
    pbm_parent_name varchar(100),
    load_step int
) INCLUDE SCHEMA PRIVILEGES;


CREATE TABLE datamart.prescriber_rx_cnt_base_adhoc
(
    ims_id varchar(10),
    payer_plan_number varchar(10),
    ims_client_number varchar(64),
    report_frequency varchar(10),
    ims_product_group varchar(64),
    basket_id int,
    data_date date,
    date date,
    sales_category varchar(64),
    tvcmid int,
    prescriber_first_name varchar(25),
    prescriber_last_name varchar(25),
    basket_name varchar(300),
    basket_type varchar(100),
    rollup_week date,
    rollup_month date,
    nrx_count numeric(37,15),
    trx_count numeric(37,15),
    nrx_quantity varchar(1),
    trx_quantity varchar(1),
    unnormalized_nrx_count numeric(37,15),
    unnormalized_trx_count numeric(37,15),
    market_name varchar(300),
    payer_name varchar(100),
    plan_name varchar(100),
    pbm_name varchar(100),
    model varchar(10),
    payment_method varchar(250),
    ims_specialty varchar(10),
    ims_rx_type varchar(1),
    ims_supplemental_data varchar(20),
    zip_other varchar(10),
    ims_report_number varchar(64),
    file_id int,
    record_id int,
    ims_report_number_qty varchar(5),
    indication varchar(20),
    load_step int
);


CREATE TABLE datamart.prescriber_rx_qty_base_adhoc
(
    ims_id varchar(10),
    payer_plan_number varchar(10),
    ims_client_number varchar(64),
    report_frequency varchar(10),
    ims_product_group varchar(64),
    basket_id int,
    data_date date,
    date date,
    sales_category varchar(64),
    tvcmid int,
    prescriber_first_name varchar(25),
    prescriber_last_name varchar(25),
    basket_name varchar(300),
    basket_type varchar(100),
    rollup_week date,
    rollup_month date,
    nrx_count numeric(126,67),
    trx_count numeric(126,67),
    nrx_quantity numeric(37,15),
    trx_quantity numeric(37,15),
    unnormalized_nrx_count varchar(1),
    unnormalized_trx_count varchar(1),
    market_name varchar(300),
    payer_name varchar(100),
    plan_name varchar(100),
    pbm_name varchar(100),
    model varchar(10),
    payment_method varchar(250),
    ims_specialty varchar(10),
    ims_rx_type varchar(1),
    ims_supplemental_data varchar(20),
    zip_other varchar(10),
    ims_report_number varchar(64),
    file_id int,
    record_id int,
    ims_report_number_cnt varchar(5),
    indication varchar(20),
    load_step int
);


CREATE TABLE datamart.prescriber_rx_adhoc
(
    ims_id varchar(10),
    payer_plan_number varchar(10),
    ims_client_number varchar(5),
    report_frequency varchar(20),
    ims_product_group varchar(10),
    basket_id int,
    data_date date,
    date date,
    sales_category varchar(2),
    tvcmid int,
    prescriber_first_name varchar(50),
    prescriber_last_name varchar(50),
    basket_name varchar(300),
    basket_type varchar(100),
    rollup_week date,
    rollup_month date,
    nrx_count float,
    trx_count float,
    nrx_quantity float,
    trx_quantity float,
    unnormalized_nrx_count float,
    unnormalized_trx_count float,
    market_name varchar(75),
    payer_name varchar(100),
    plan_name varchar(100),
    pbm_name varchar(100),
    model varchar(100),
    payment_method varchar(250),
    ims_specialty varchar(10),
    ims_rx_type varchar(1),
    ims_supplemental_data varchar(20),
    ims_zip_other varchar(10),
    ims_report_number_cnt varchar(5),
    cnt_file_id int,
    cnt_record_id int,
    ims_report_number_qty varchar(5),
    qty_file_id int,
    qty_record_id int,
    rollup_flag char(1),
    indication varchar(20)
);


CREATE TABLE datamart.copay
(
    redemption_type varchar(10),
    physician_tvcmid int,
    pharmacy_tvcmid int,
    basket_id int,
    basket_name varchar(300),
    asi_txn_id varchar(20),
    orig_asi_txn_id varchar(20),
    rx_num varchar(50),
    fill_date date,
    date_written date,
    days_supply int,
    ndc_code varchar(20),
    daw int,
    new_refill int,
    quantity numeric(9,2),
    refills int,
    other_coverage_code varchar(10),
    program_number varchar(15),
    copay_card_number varchar(20),
    sex varchar(1),
    age_at_redemption int,
    pharmacy_process_date date,
    pharmacy_chain_number varchar(5),
    nabp varchar(7),
    pharmacy_chain varchar(50),
    pharmacy_name varchar(100),
    pharmacy_address varchar(100),
    pharmacy_address2 varchar(100),
    pharmacy_city varchar(50),
    pharmacy_state varchar(2),
    pharmacy_zip varchar(15),
    pharmacy_phone varchar(10),
    pharmacy_npi_num varchar(10),
    principle_physician_dea varchar(9),
    physician_npi varchar(10),
    physician_ims_id varchar(10),
    physician_veeva_id varchar(20),
    physician_name varchar(100),
    physician_address1 varchar(100),
    physician_address2 varchar(100),
    physician_city varchar(50),
    physician_state varchar(2),
    physician_zip varchar(5),
    rebate_amount numeric(9,2),
    member_cash_expense numeric(9,2),
    submitted_cost numeric(9,2),
    pharmacy_fee numeric(9,2),
    total_amount_due numeric(9,2),
    calc_awp numeric(9,2),
    create_date date,
    occ_payment_type varchar(10),
    counted_copay varchar(1),
    auth_refills int,
    admin_hcp_npi varchar(10),
    admin_hcp_name varchar(100),
    admin_hcp_address varchar(100),
    admin_hcp_address2 varchar(100),
    admin_hcp_city varchar(50),
    admin_hcp_state varchar(2),
    admin_hcp_zip varchar(10),
    claim_type varchar(50),
    administration_flag char(1),
    soc_name varchar(60),
    soc_phone varchar(10),
    soc_fax varchar(10),
    soc_address varchar(100),
    soc_city varchar(50),
    soc_state varchar(2),
    soc_zip varchar(10),
    soc_id varchar(50),
    soc_npi varchar(10),
    payer_name varchar(60),
    cpt_code varchar(10),
    trans_type varchar(15),
    previous_payer_id int,
    member_id varchar(20),
    benefit_amount numeric(9,2),
    patient_expense numeric(9,2),
    submission_method varchar(1),
    report_frequency varchar(20),
    source_name varchar(255),
    file_id int,
    record_id int,
    patient_type varchar(100),
    primary_bin varchar(100),
    primary_bin_description varchar(100),
    reject_code varchar(100)
);


CREATE TABLE datamart.customer_hcp_demographics
(
    tvcmid int,
    ims_id varchar(7),
    npi varchar(10),
    last_name varchar(40),
    first_name varchar(40),
    middle_name varchar(40),
    personal_suffix varchar(10),
    medical_suffix varchar(10),
    primary_specialty varchar(5),
    secondary_specialty varchar(5),
    address_line1 varchar(80),
    address_line2 varchar(80),
    city varchar(40),
    state_code varchar(2),
    zip varchar(5),
    business_phone varchar(100),
    business_email varchar(100),
    hce_status_desc varchar(50),
    np_pa_flag varchar(1),
    address_id int,
    address_latitude varchar(20),
    address_longitude varchar(20),
    file_id int,
    record_id int
);


CREATE TABLE datamart.prescriber_combined_demographics
(
    sales_force_id varchar(20),
    ims_id varchar(10),
    npi varchar(10),
    tvcmid int,
    veeva_account_id varchar(20),
    specialty varchar(255),
    secondary_specialty varchar(255),
    first_name varchar(50),
    middle_name varchar(50),
    last_name varchar(50),
    ptr_veeva_address_id varchar(20),
    ptr_address_1 varchar(100),
    ptr_address_2 varchar(100),
    ptr_address_3 varchar(100),
    ptr_city varchar(50),
    ptr_state varchar(2),
    ptr_zip varchar(5),
    ptr_phone varchar(40),
    ptr_territory_num varchar(15),
    ptr_territory_type varchar(30),
    ptr_address_source varchar(50),
    ptr_mailable varchar(1) DEFAULT 'N',
    dea_num varchar(10),
    pdrp_flag varchar(1) DEFAULT 'N',
    pdrp_date timestamp,
    np_pa_flag varchar(1) DEFAULT 'N',
    no_spend varchar(1) DEFAULT 'N',
    ama_no_contact_flag varchar(1) DEFAULT 'N',
    email varchar(100),
    degree varchar(100),
    address_id int,
    address_latitude varchar(20),
    address_longitude varchar(20),
    row_source varchar(100)
);


CREATE TABLE datamart.oncology_invoice_adjustments
(
    adj_code varchar(10),
    adj_descr varchar(50),
    act_time_period varchar(10),
    act_start_date date,
    act_end_date date,
    status_code varchar(10),
    basket_id int,
    basket_name varchar(300),
    adj_factor float,
    tvcmid int,
    record_id int,
    file_id int
);


CREATE TABLE datamart.rx_deciles
(
    ims_id varchar(10),
    tvcmid int,
    basket_id int,
    basket_name varchar(300),
    basket_type varchar(100),
    report_frequency varchar(20),
    decile_trx_count_6_mo int,
    decile_trx_count_12_mo int,
    trx_count_6_mo float,
    trx_count_12_mo float,
    trx_count_24_mo float,
    decile_date date,
    first_name varchar(50),
    last_name varchar(50),
    decile_name varchar(50)
);


CREATE TABLE datamart.formulary_restrictions
(
    health_plan_id varchar(6),
    drug_id varchar(6),
    restriction_code varchar(7),
    restriction_detail_id varchar(6),
    restriction_detail_text varchar(250),
    restriction_addtnl_information_1 varchar(4000),
    restriction_addtnl_information_2 varchar(4000),
    step_count varchar(50),
    pa_form varchar(4000),
    indication varchar(255),
    grouped_restriction_level varchar(255),
    record_id int,
    file_id int
);


CREATE TABLE datamart.fia
(
    basket_id int,
    basket_name varchar(300),
    claim_id varchar(64),
    patient_id int,
    sequence_number int,
    product_id varchar(11),
    fill_date date,
    claim_type varchar(2),
    reject_code varchar(3),
    days_supply numeric(10,6),
    quantity varchar(12),
    refill_code int,
    payer_plan_id varchar(10),
    opc_ask varchar(10),
    sec_payer_plan_id varchar(10),
    buy_down varchar(11),
    opc_paid varchar(10),
    prescriber_id varchar(20),
    sob varchar(3),
    sub_product_id varchar(11),
    sub_opc varchar(10),
    initial_claim_id varchar(64),
    prev_product_id varchar(11),
    daw_code varchar(2),
    wrt_date date,
    claim_status varchar(1),
    copay_card_flg varchar(4),
    zip_code varchar(5),
    ecoup_flag int,
    ecoup_offset_amt numeric(10,2),
    standard_copay numeric(10,2),
    standard_copay_yn varchar(1),
    market_id int,
    flexible_fld_1_char varchar(50),
    flexible_fld_2_char varchar(50),
    flexible_fld_3_char varchar(50),
    flexible_fld_4_char varchar(50),
    file_id int,
    record_id int,
    cbsa_code varchar(5),
    cbsa_description varchar(100),
    state_code varchar(2),
    payer_name varchar(64),
    plan_name varchar(64),
    pbm_name varchar(60),
    pbm_id varchar(6),
    method_of_payment varchar(50),
    model_type varchar(64),
    product_group varchar(80),
    product_group_id int,
    product_name varchar(100),
    generic_name varchar(100),
    brand_generic_flag varchar(1),
    product_form varchar(100),
    product_strength varchar(100),
    package_size float,
    manufacturer varchar(100),
    cmf10 varchar(10),
    usc_code varchar(5),
    fia_market_desc varchar(50),
    reject_reason varchar(200),
    reject_group varchar(50),
    mpd_year int,
    mpd_eligibility_class varchar(11),
    deductible_start_date date,
    copay_start_date date,
    gap_start_date date,
    catastrophic_start_date date,
    mpd_panel_patient int,
    PROVIDER_TYPE varchar(2),
    IQVIA_RXER_ID varchar(7),
    PRIMARY_SPECIALTY_CODE varchar(10),
    PRIMARY_SPECIALTY_DESC varchar(100),
    FIRST_NAME varchar(100),
    LAST_NAME varchar(100),
    ORG_NM varchar(50),
    ADDRESS varchar(200),
    CITY varchar(100),
    PVR_ZIP_CODE varchar(5),
    PVR_STATE_CODE varchar(2),
    PHONE_NUMBER varchar(20),
    DEA_NUMBER varchar(20),
    ME_NUMBER varchar(20),
    PVR_FLEXIBLE_FLD_1_CHAR varchar(50),
    PVR_FLEXIBLE_FLD_2_CHAR varchar(50)
);


CREATE TABLE datamart.sfa_call_new
(
    sales_force_id varchar(2),
    call_id varchar(20),
    veeva_account_id varchar(20),
    ims_id varchar(10),
    ims_outlet_id varchar(15),
    customer_type varchar(50),
    first_name varchar(50),
    last_name varchar(80),
    call_type varchar(50),
    legacy_call_type varchar(50),
    ceph_id varchar(10),
    dea_num varchar(10),
    rep_id varchar(20),
    rep_first_name varchar(50),
    rep_last_name varchar(50),
    territory_number varchar(8),
    zip_on_call varchar(10),
    call_date date,
    submit_date timestamp,
    attendees int,
    attendee_type varchar(50),
    area_number varchar(8),
    region_number varchar(8),
    tvcmid int,
    call_recordtype varchar(80),
    call_duration numeric(3,0),
    call_datetime timestamp,
    call_timezone varchar(30),
    how_executed varchar(40),
    remote_meeting_id varchar(100),
    parent_call_id varchar(64),
    is_parent_call varchar(18),
    t21s10_austedo_indication varchar(255)
);


CREATE TABLE datamart.specialty_pharmacy_shipment
(
    specialty_pharmacy_data_source varchar(50),
    ims_id varchar(10),
    tw_ship_to_address_id int,
    tw_bill_to_address_id int,
    source_customer_id varchar(50),
    customer_name varchar(100),
    physician_first_name varchar(50),
    physician_last_name varchar(50),
    ship_to_address_line_1 varchar(100),
    ship_to_address_line_2 varchar(100),
    ship_to_city varchar(50),
    ship_to_state varchar(2),
    ship_to_zip varchar(20),
    source_transaction_id varchar(50),
    invoice_date date,
    ship_date date,
    source_product_code varchar(25),
    basket_id int,
    basket_name varchar(300),
    quantity float,
    invoice_unit_price float,
    invoice_amount float,
    invoice_discount float,
    order_type varchar(50),
    customer_type varchar(20),
    source_parent_customer_id varchar(20),
    parent_customer_name varchar(100),
    file_id int,
    record_id int,
    lob_code_desc varchar(100),
    order_type_desc varchar(50),
    price_matrix_def varchar(20),
    whse_code varchar(20),
    order_no varchar(50),
    package_size int,
    tvcmid int,
    trx_cnt numeric(37,15),
    net_sales_amt numeric(37,15),
    adj_invoice_unit_price float,
    adj_invoice_amount float,
    comp_month date,
    hin varchar(20),
    dea_number varchar(20),
    net_cost numeric(37,15),
    payer_flag varchar(50),
    optum_briova_flag varchar(50),
    physician_middle_name varchar(50),
    rollup_flag char(1),
    basket_type varchar(100),
    unnormalized_trx_count numeric(37,15),
    days_supplied int,
    SPP_Physician_ID int,
    Primary_Payer_BIN varchar(20),
    Primary_Payer_PCN varchar(20),
    Primary_Group_Num varchar(30),
    Primary_Payer_Name varchar(100),
    Primary_Payer_Type varchar(25),
    Primary_Copay_Amount numeric(20,2),
    NPI varchar(10),
    state_license_number varchar(15)
);


CREATE TABLE datamart.select_brand_sales
(
    data_source varchar(50),
    transaction_id varchar(100),
    invoice_date date,
    basket_id int,
    basket_name varchar(300),
    product_brand varchar(50),
    product_ndc varchar(20),
    product_desc varchar(100),
    invoice_qty numeric(37,15),
    invoice_units numeric(37,15),
    invoice_cost numeric(18,4),
    invoice_pack_cost numeric(18,4),
    invoice_unit_cost numeric(18,4),
    contract_pack_cost numeric(18,4),
    contract_purchases numeric(18,4),
    contract_number varchar(100),
    dispensing_location varchar(100),
    dl_address_1 varchar(100),
    dl_address_2 varchar(100),
    dl_city varchar(50),
    dl_state varchar(2),
    dl_zip varchar(20),
    dl_dea_number varchar(20),
    depot_location varchar(100),
    dep_address_1 varchar(100),
    dep_address_2 varchar(100),
    dep_city varchar(50),
    dep_state varchar(2),
    dep_zip varchar(5),
    dep_dea_number varchar(20),
    unit_ap float,
    ap float,
    file_id int,
    record_id int,
    dispensing_tvcmid int,
    depot_tvcmid int
);


CREATE TABLE datamart.oncology_fcr
(
    time_period varchar(10),
    sales_force_id varchar(2),
    area_number varchar(8),
    region_number varchar(8),
    territory_number varchar(8),
    employee_id varchar(20),
    contact_date date,
    duration_days float,
    ss_opening int,
    ss_probing int,
    ss_resources int,
    ss_commitment int,
    ss_transitioning int,
    ss_acumen int,
    archive_flag varchar(1),
    file_id int,
    record_id int
);


CREATE TABLE datamart.alternate_call_plans
(
    sales_force_id varchar(2),
    period varchar(20),
    veeva_account_id varchar(20),
    ims_id varchar(10),
    first_name varchar(50),
    last_name varchar(50),
    specialty varchar(100),
    territory_number varchar(8),
    area_number varchar(8),
    region_number varchar(8),
    product_name varchar(20),
    basket_id int,
    basket_name varchar(300),
    p1 int,
    p2 int,
    p3 int,
    file_id int,
    record_id int,
    call_plan_name varchar(100),
    tvcmid int,
    start_date date,
    end_date date
);


CREATE TABLE datamart.dynamic_segment
(
    federation_id varchar(64),
    basket_id int,
    segment_name varchar(50),
    segment_value varchar(50),
    file_id int,
    record_id int
);


CREATE TABLE datamart.sfa_affiliations
(
    affiliated_from_id varchar(18),
    affiliated_from_account_type varchar(80),
    affiliated_from_ims_id varchar(20),
    affiliated_from_ims_outlet_cd varchar(100),
    affiliated_from_acct_demo_id varchar(30),
    affiliated_from_bp_code varchar(120),
    affiliated_from_tvcmid int,
    affiliated_to_id varchar(18),
    affiliated_to_account_type varchar(80),
    affiliated_to_ims_id varchar(20),
    affiliated_to_ims_outlet_code varchar(100),
    affiliated_to_acct_demo_id varchar(30),
    affiliated_to_bp_code varchar(120),
    affiliated_to_tvcmid int,
    role varchar(50),
    affiliated_last_modified_date timestamp,
    sales_force_id varchar(2),
    territory_number varchar(100),
    employee_full_name varchar(100),
    employee_id varchar(100)
);


CREATE TABLE datamart.digital_sales_aid_analysis
(
    sales_force_id varchar(2),
    territory_number varchar(8),
    region_num varchar(8),
    area_num varchar(8),
    veeva_id varchar(20),
    ims_id varchar(10),
    npi_num varchar(10),
    account_type varchar(80),
    account_sub_type varchar(40),
    account_name varchar(255),
    first_name varchar(40),
    middle_name varchar(40),
    last_name varchar(80),
    address varchar(80),
    city varchar(40),
    state varchar(2),
    zip varchar(10),
    credential varchar(255),
    degree varchar(30),
    specialty varchar(255),
    call_id varchar(20),
    call_date date,
    product_name varchar(80),
    basket_id int,
    basket_name varchar(300),
    detail_priority int,
    display_order int,
    duration int,
    presentation_name varchar(80),
    message_name varchar(80),
    detailed_products varchar(255),
    detail_type varchar(20),
    sampled_call varchar(1),
    message_visit_number int,
    visit_number int,
    rep_name varchar(125),
    week_ending date,
    call_type varchar(25),
    rep_id varchar(20),
    tvcmid int,
    message_desc varchar(255)
);


CREATE TABLE datamart.touchpoint_call
(
    call_id int,
    call_attempt_id int,
    touchpoint_id int,
    veeva_id varchar(20),
    ims_id varchar(10),
    first_name varchar(50),
    last_name varchar(50),
    call_type varchar(100),
    call_date date,
    status_code varchar(10),
    status_description varchar(100),
    rep_id int,
    rep_first_name varchar(50),
    rep_last_name varchar(50),
    file_id int,
    record_id int,
    tvcmid int
);


CREATE TABLE datamart.sfa_call
(
    sales_force_id varchar(2),
    call_id varchar(20),
    veeva_account_id varchar(20),
    ims_id varchar(10),
    ims_outlet_id varchar(15),
    customer_type varchar(50),
    first_name varchar(50),
    last_name varchar(80),
    call_type varchar(50),
    legacy_call_type varchar(50),
    ceph_id varchar(10),
    dea_num varchar(10),
    rep_id varchar(20),
    rep_first_name varchar(50),
    rep_last_name varchar(50),
    territory_number varchar(8),
    zip_on_call varchar(10),
    call_date date,
    submit_date timestamp,
    attendees int,
    attendee_type varchar(50),
    area_number varchar(8),
    region_number varchar(8),
    tvcmid int,
    call_recordtype varchar(80),
    call_duration numeric(3,0),
    call_datetime timestamp,
    call_timezone varchar(30),
    how_executed varchar(40),
    remote_meeting_id varchar(100),
    parent_call_id varchar(64),
    is_parent_call varchar(18),
    t21s10_austedo_indication varchar(255),
    Outcomes_from_Visit varchar(50),
    Visit_Trigger varchar(50),
    Visit_Trigger_Date date,
    call_name varchar(80),
    veeva_address_id varchar(18)
);


CREATE TABLE datamart.sfa_demographics
(
    veeva_account_id varchar(32),
    sales_force_id varchar(5),
    customer_type varchar(50),
    ims_id varchar(10),
    npi varchar(10),
    ims_outlet_code varchar(12),
    territory_number varchar(8),
    territory_type varchar(10),
    territory_status varchar(30),
    last_name varchar(80),
    first_name varchar(50),
    middle_name varchar(50),
    suffix_name varchar(10),
    credentials varchar(50),
    organization_name varchar(255),
    veeva_address_id varchar(20),
    address_line1 varchar(100),
    address_line2 varchar(100),
    address_line3 varchar(100),
    city varchar(50),
    state varchar(2),
    zip varchar(10),
    address_status varchar(20),
    phone varchar(50),
    phone_ext varchar(12),
    fax varchar(50),
    mobile varchar(50),
    email varchar(200),
    prim_specialty varchar(255),
    specialty_code varchar(5),
    sfa_create_date date,
    demo_rank int,
    last_call_date date,
    calls_last_90_days int,
    zip_valid_for_territory_num varchar(1),
    bp_code varchar(20),
    sfa_align_date date,
    account_demo_id varchar(30),
    pdrp_flag varchar(5),
    designation varchar(255),
    business_type varchar(40),
    area_number varchar(8),
    region_number varchar(8),
    tvcmid int,
    address_latitude varchar(20),
    address_longitude varchar(20),
    calls_last_6_months int,
    address_id int,
    staff_email varchar(80),
    company_managed_email varchar(80),
    alternate_email varchar(80)
);


CREATE TABLE datamart.sfa_promotional_items
(
    sales_force_id varchar(2),
    territory_number varchar(8),
    product_name varchar(80),
    promo_item_id int,
    promo_item_name varchar(300),
    distribution_date date,
    quantity int,
    item_name varchar(150),
    item_type varchar(30),
    call_id varchar(20),
    veeva_sample_id varchar(20),
    rep_id varchar(20),
    rep_first_name varchar(50),
    rep_last_name varchar(50),
    veeva_account_id varchar(20),
    ims_id varchar(10),
    prescriber_first_name varchar(50),
    prescriber_last_name varchar(80),
    name_on_call varchar(150),
    zip_on_call varchar(30),
    area_number varchar(8),
    region_number varchar(8),
    tvcmid int,
    basket_id int,
    basket_name varchar(300),
    product_value numeric(7,2)
);


CREATE TABLE datamart.territory_history
(
    territory_number varchar(50),
    employee_id varchar(50),
    start_date date,
    end_date date,
    first_name varchar(50),
    last_name varchar(50),
    rep_type varchar(10),
    termination_date date,
    hire_date date,
    end_reason varchar(10),
    original_hire_date date,
    source_id varchar(20)
);


CREATE TABLE datamart.leave_of_absence
(
    employee_id varchar(50),
    leave_date date,
    return_date date,
    days_of_leave int
);


CREATE TABLE datamart.time_off_territory
(
    territory_number varchar(8),
    time_off_date date,
    time_on_date date,
    description varchar(50),
    duration_in_days numeric(10,1),
    veeva_account_id varchar(20),
    file_id int,
    record_id int
);


CREATE TABLE datamart.product_basket
(
    parent_basket_name varchar(300),
    parent_basket_type varchar(100),
    parent_basket_id int,
    child_basket_name varchar(300),
    child_basket_type varchar(100),
    child_basket_id int
);


CREATE TABLE datamart.oncology_sales_quotas
(
    time_period varchar(10),
    sales_force_id varchar(2),
    area_number varchar(8),
    region_number varchar(8),
    territory_number varchar(8),
    product_name varchar(20),
    basket_id int,
    quota_qty int,
    quota_dollars numeric(18,4),
    quota_strength_unit int,
    file_id int,
    record_id int
);


CREATE TABLE datamart.direct_sales
(
    account_id varchar(100),
    location_id varchar(100),
    shipment_date date,
    ndc_code varchar(20),
    product_name varchar(100),
    basket_id int,
    basket_name varchar(300),
    transaction_type varchar(100),
    direct_sales_units float,
    direct_sales_dollars float,
    unit_ap float,
    total_ap float,
    file_id int,
    record_id int,
    tvcmid int
);


CREATE TABLE datamart.ahm_interactions
(
    sourcesystemid varchar(10),
    batchid varchar(18),
    batchdate date,
    transactionstatuscode varchar(1),
    interactionid varchar(18),
    interactioncode varchar(50),
    interactionname varchar(200),
    interactioncategory varchar(50),
    interactiontype varchar(50),
    locationtype varchar(50),
    interactionstatus varchar(50),
    interactionstartdate date,
    interactionenddate date,
    interactionstarttime varchar(50),
    interactionendtime varchar(50),
    interactiontimezone varchar(80),
    interactionstartdatetime varchar(26),
    interactionenddatetime varchar(26),
    requestingregion varchar(100),
    parentinteractionid varchar(18),
    parentinteractioncode varchar(50),
    employeeid varchar(18),
    clientemployeeid varchar(50),
    employeefirstname varchar(80),
    employeelastname varchar(80),
    employeeorganizationunitid varchar(18),
    employeeorganizationunitcode varchar(50),
    employeeorganizationunitname varchar(200),
    venueid varchar(18),
    clientvenueid varchar(18),
    venuename varchar(80),
    venueaddressline1 varchar(50),
    venueaddressline2 varchar(50),
    venueaddressline3 varchar(50),
    venuecity varchar(80),
    venuestateprovince varchar(50),
    venuepostalcode varchar(20),
    venuecountry varchar(50),
    venueregion varchar(100),
    totalestimatedparticipantcount int,
    financialcloseddate date,
    product1name varchar(80),
    product1id varchar(18),
    product1clientid varchar(100),
    topic1name varchar(255),
    topic1id varchar(18),
    topic1clientid varchar(80),
    product2name varchar(80),
    product2id varchar(18),
    product2clientid varchar(100),
    topic2name varchar(255),
    topic2id varchar(18),
    topic2clientid varchar(80),
    product3name varchar(80),
    product3id varchar(18),
    product3clientid varchar(100),
    topic3name varchar(255),
    topic3id varchar(18),
    topic3clientid varchar(80),
    product4name varchar(80),
    product4id varchar(18),
    product4clientid varchar(100),
    topic4name varchar(255),
    topic4id varchar(18),
    topic4clientid varchar(80),
    product5name varchar(80),
    product5id varchar(18),
    product5clientid varchar(100),
    topic5name varchar(255),
    topic5id varchar(18),
    topic5clientid varchar(80),
    record_id int,
    file_id int
);


CREATE TABLE datamart.ahm_participant
(
    sourcesystemid varchar(10),
    batchid varchar(18),
    batchdate date,
    transactionstatuscode varchar(1),
    interactionid varchar(18),
    interactioncode varchar(50),
    participantid varchar(18),
    clientcustomerid varchar(100),
    participanttype varchar(80),
    firstname varchar(80),
    middlename varchar(80),
    lastname varchar(80),
    suffix varchar(80),
    professionaldesignation varchar(80),
    primaryspecialty varchar(80),
    organizationname varchar(80),
    npinumber varchar(10),
    addressid varchar(18),
    clientaddressid varchar(100),
    addressline1 varchar(255),
    addressline2 varchar(255),
    addressline3 varchar(255),
    addresscity varchar(80),
    addressstateprovince varchar(50),
    addresspostalcode varchar(20),
    addresspostalcodeextension varchar(10),
    addresscountry varchar(50),
    region varchar(50),
    primarystatelicensestate varchar(50),
    primarystatelicensenumber varchar(50),
    attended varchar(1),
    mealconsumed varchar(1),
    contractid varchar(18),
    clientcontractid varchar(50),
    contractname varchar(100),
    contractcategory varchar(50),
    contractsubcategory varchar(50),
    contractclassification varchar(50),
    contracttier varchar(50),
    contracteffectivedate date,
    contractexpirationdate date,
    contracttotalvalue numeric(10,2),
    record_id int,
    file_id int
);


CREATE TABLE datamart.ahm_unnamedparticipant
(
    sourcesystemid varchar(10),
    batchid varchar(18),
    batchdate date,
    transactionstatuscode varchar(1),
    interactionid varchar(18),
    interactioncode varchar(50),
    particpantcategoryid varchar(18),
    categorytype varchar(100),
    totalattendedcount int,
    totalmealconsumedcount int,
    record_id int,
    file_id int
);


CREATE TABLE datamart.ahm_expense
(
    sourcesystemid varchar(10),
    batchid varchar(18),
    batchdate date,
    transactionstatuscode varchar(1),
    interactionid varchar(18),
    interactioncode varchar(50),
    spendid varchar(18),
    clientspendid varchar(100),
    spendamount numeric(10,2),
    spendcurrency varchar(3),
    spenddate date,
    spendtype varchar(50),
    spendpurpose varchar(50),
    traveldestinationcity varchar(80),
    traveldestinationstateprovince varchar(50),
    traveldestinationcountry varchar(50),
    spenddescription varchar(2000),
    taxincludedindicator varchar(1),
    taxamount numeric(10,2),
    taxrate numeric(10,2),
    recipientid varchar(18),
    clientrecipientid varchar(100),
    participantid varchar(18),
    recipientfirstname varchar(80),
    recipientmiddlename varchar(80),
    recipientlastname varchar(80),
    recipientsuffix varchar(80),
    recipientprofessionaldesignation varchar(80),
    recipientprimaryspecialty varchar(80),
    recipientorganizationname varchar(80),
    recipientnpinumber varchar(10),
    recipientaddressid varchar(18),
    recipientclientaddressid varchar(100),
    recipientaddressline1 varchar(255),
    recipientaddressline2 varchar(255),
    recipientaddressline3 varchar(255),
    recipientaddresscity varchar(80),
    recipientaddressstateprovince varchar(50),
    recipientaddresspostalcode varchar(20),
    recipientaddresspostalcodeextension varchar(10),
    recipientaddresscountry varchar(50),
    recipientprimarystatelicensestate varchar(50),
    recipientprimarystatelicensenumber varchar(50),
    thirdpartyrecipientindicator varchar(1),
    thirdpartyrecipientid varchar(18),
    thirdpartyclientrecipientid varchar(100),
    thirdpartyrecipientname varchar(80),
    thirdpartycoveredrecipientindicator varchar(1),
    paymentid varchar(18),
    clientpaymentid varchar(50),
    paymentdate date,
    paymentmethod varchar(50),
    paymentreferencenumber varchar(50),
    paymentstatus varchar(50),
    record_id int,
    file_id int
);


CREATE TABLE datamart.customer_address
(
    tvcmid int,
    address_id int,
    address_type varchar(10),
    address_type_name varchar(50),
    address_line_1 varchar(80),
    address_line_2 varchar(80),
    county varchar(40),
    city varchar(40),
    state varchar(2),
    state_name varchar(50),
    country_code varchar(3),
    country_name varchar(50),
    zip5_postal_code varchar(5),
    zip4_postal_extension_code varchar(4),
    address_status varchar(10),
    address_status_name varchar(50),
    address_effective_date timestamp,
    msa_cbsa varchar(5),
    fips_state_code varchar(2),
    fips_state_description varchar(50),
    fips_county_code varchar(3),
    fips_county_description varchar(50),
    deliverability_confidence varchar(10),
    address_setting_type_code varchar(10),
    address_setting_type_description varchar(50),
    address_category_code varchar(10),
    address_category_description varchar(50),
    address_latitude varchar(20),
    address_longitude varchar(20),
    postal_barcode varchar(10),
    single_address_indicator varchar(1),
    practice_location_confidence_indicator varchar(10),
    practice_location_rank varchar(10),
    validation_message varchar(100),
    created_by varchar(50),
    created_date timestamp,
    updated_by varchar(50),
    updated_date timestamp,
    file_id int,
    record_id int
);


CREATE TABLE datamart.customer_address_link
(
    tvcmid int,
    tvcm_addr_id int,
    dsp_id varchar(10),
    dsp_hce_id varchar(100),
    dsp_addr_id varchar(100),
    file_id int,
    record_id int
);


CREATE TABLE datamart.oncology_target_accounts
(
    tvcmid int,
    sales_force_id varchar(2),
    basket_id int,
    basket_name varchar(20),
    acct_demo_id int,
    outlet_code varchar(10),
    target_type varchar(20),
    target_value varchar(20),
    applies_from_date date,
    applies_to_date date,
    active_ind varchar(1),
    system_start_date date,
    system_end_date date,
    end_reason varchar(100),
    veeva_account_id varchar(20),
    file_id int,
    record_id int
);


CREATE TABLE datamart.patient_response
(
    basket_id int,
    basket_name varchar(300),
    tvcmid int,
    week_end_date date,
    practice_name varchar(255),
    practice_address_line_1 varchar(255),
    practice_address_line_2 varchar(255),
    city varchar(255),
    state varchar(255),
    zip_code varchar(255),
    provider_first_name varchar(255),
    provider_last_name varchar(255),
    npi varchar(255),
    specialty_1 varchar(255),
    specialty_2 varchar(255),
    total_cml_patients_with_poor_response_to_treatment int,
    pts_with_moderate_severe_asthma_and_eosinophils_0_149 int,
    pts_with_moderate_severe_asthma_and_eosinophils_150_399 int,
    pts_with_moderate_severe_asthma_and_eosinophils_400_or_greater int,
    pts_with_ao_asthma_and_eosinophils_0_149 int,
    pts_with_ao_asthma_and_eosinophils_150_399 int,
    pts_with_ao_asthma_and_eosinophils_400_or_greater int,
    file_id int,
    record_id int,
    pts_with_moderate_severe_asthma_and_has_eosinophils_300_499 int,
    pts_with_moderate_severe_asthma_and_has_eosinophils_500_or_greater int
);


CREATE TABLE datamart.prescriber_rx
(
    ims_id varchar(10),
    payer_plan_number varchar(10),
    ims_client_number varchar(5),
    report_frequency varchar(20),
    ims_product_group varchar(10),
    basket_id int,
    data_date date,
    date date,
    sales_category varchar(2),
    tvcmid int,
    prescriber_first_name varchar(50),
    prescriber_last_name varchar(50),
    basket_name varchar(300),
    basket_type varchar(100),
    rollup_week date,
    rollup_month date,
    nrx_count numeric(18,3),
    trx_count numeric(18,3),
    nrx_quantity numeric(18,3),
    trx_quantity numeric(18,3),
    unnormalized_nrx_count numeric(18,3),
    unnormalized_trx_count numeric(18,3),
    market_name varchar(75),
    payer_name varchar(100),
    plan_name varchar(100),
    pbm_name varchar(100),
    model varchar(100),
    payment_method varchar(250),
    ims_specialty varchar(10),
    ims_rx_type varchar(1),
    ims_supplemental_data varchar(20),
    ims_zip_other varchar(10),
    ims_report_number_cnt varchar(5),
    cnt_file_id int,
    cnt_record_id int,
    ims_report_number_qty varchar(5),
    qty_file_id int,
    qty_record_id int,
    rollup_flag char(1),
    indication varchar(20),
    pbm_parent_name varchar(100)
) INCLUDE SCHEMA PRIVILEGES;


CREATE TABLE datamart.prescriber_combined_demo_frozen
(
    start_date date,
    end_date date,
    sales_force_id varchar(20),
    ims_id varchar(10),
    npi varchar(10),
    tvcmid int,
    veeva_account_id varchar(20),
    specialty varchar(255),
    first_name varchar(50),
    middle_name varchar(50),
    last_name varchar(50),
    ptr_veeva_address_id varchar(20),
    ptr_address_1 varchar(100),
    ptr_address_2 varchar(100),
    ptr_address_3 varchar(100),
    ptr_city varchar(50),
    ptr_state varchar(2),
    ptr_zip varchar(5),
    ptr_phone varchar(40),
    ptr_territory_num varchar(15),
    ptr_territory_type varchar(30),
    ptr_address_source varchar(50),
    ptr_mailable varchar(1) DEFAULT 'N',
    dea_num varchar(10),
    pdrp_flag varchar(1) DEFAULT 'N',
    pdrp_date timestamp,
    np_pa_flag varchar(1) DEFAULT 'N',
    no_spend varchar(1) DEFAULT 'N',
    ama_no_contact_flag varchar(1) DEFAULT 'N',
    email varchar(100),
    degree varchar(100),
    address_id int,
    address_latitude varchar(20),
    address_longitude varchar(20),
    row_source varchar(100),
    freeze_reason varchar(100),
    freeze_date date DEFAULT now(),
    secondary_specialty varchar(255)
);


CREATE TABLE datamart.alternate_alignments
(
    alignment_name varchar(100),
    zip_code varchar(5),
    city varchar(50),
    state_code varchar(2),
    territory_number varchar(8),
    territory_name varchar(50),
    area_name varchar(50),
    region_name varchar(50),
    sales_force_id varchar(5),
    organization_code varchar(200),
    mirror_flag varchar(64),
    mirror_territory_number varchar(8),
    file_id int,
    record_id int,
    start_date date,
    end_date date
);


CREATE TABLE datamart.chargeback_demographics
(
    account_id varchar(100),
    location_id varchar(100),
    dea_number varchar(20),
    end_customer varchar(100),
    address_1 varchar(100),
    address_2 varchar(100),
    city varchar(50),
    state varchar(2),
    zip varchar(10),
    contract_title varchar(100),
    contract_id varchar(100),
    wholesaler_name varchar(100),
    hin varchar(20),
    contract_alias varchar(100),
    wholesaler_dea varchar(20),
    cot_source varchar(30),
    class_of_trade varchar(30),
    file_id int,
    record_id int,
    tvcmid int
);


CREATE TABLE datamart.current_alignment
(
    zip_code varchar(5),
    city varchar(50),
    state_code varchar(2),
    territory_number varchar(8),
    territory_name varchar(50),
    area_number varchar(8),
    area_name varchar(50),
    region_number varchar(8),
    region_name varchar(50),
    sales_force_id varchar(5),
    organization_code varchar(200),
    inactive_flag varchar(64),
    comments varchar(255),
    mirror_flag varchar(64),
    mirror_territory_number varchar(8),
    file_id int,
    record_id int
) INCLUDE SCHEMA PRIVILEGES;


CREATE TABLE datamart.direct_sales_demographics
(
    account_id varchar(100),
    location_id varchar(100),
    account_name varchar(100),
    account_class varchar(100),
    address_1 varchar(100),
    address_2 varchar(100),
    city varchar(50),
    state varchar(50),
    zip varchar(10),
    file_id int,
    record_id int,
    tvcmid int
);


CREATE TABLE datamart.event
(
    source_system_name varchar(255),
    event_number varchar(100),
    event_name varchar(100),
    event_status_code varchar(100),
    event_status_description varchar(100),
    event_status_change_date timestamp,
    event_start_date timestamp,
    event_end_date timestamp,
    funding_source varchar(100),
    event_type varchar(100),
    event_type_description varchar(100),
    event_location varchar(100),
    event_schedule_date timestamp,
    attendee_closeout_date timestamp,
    financial_closeout_date timestamp,
    cancellation_date timestamp,
    cancellation_reason varchar(100),
    estimated_attendance varchar(100),
    venue_id varchar(100),
    venue_full_name varchar(100),
    venue_address_line_1 varchar(100),
    venue_address_line_2 varchar(100),
    venue_city varchar(100),
    venue_state varchar(100),
    venue_zip varchar(100),
    venue_contact varchar(100),
    venue_phone varchar(100),
    venue_fax varchar(100),
    venue_email varchar(100),
    file_id int,
    record_id int,
    event_time_zone varchar(100),
    event_format varchar(100),
    pending_mgmnt_approval_date timestamp(6),
    event_approval_date timestamp(6),
    event_approver_id varchar(100),
    cancellation_source varchar(100),
    event_venue_min_cnt_req_ind varchar(100),
    event_venue_min_count varchar(100),
    venue_address_line_3 varchar(100),
    venue_address_line_4 varchar(100),
    venue_postal_extended_code varchar(100),
    venue_country_code varchar(100),
    trade_secret_indicator varchar(100),
    trade_secret_reason varchar(100),
    custom_field_1 varchar(100),
    custom_field_2 varchar(100),
    custom_field_3 varchar(100),
    custom_field_4 varchar(100),
    custom_field_5 varchar(100),
    rec_stat_cd varchar(100),
    parent_event_number varchar(100)
);


CREATE TABLE datamart.event_attendee_count
(
    source_system_name varchar(255),
    event_number varchar(100),
    attendee_category_code varchar(20),
    count int,
    file_id int,
    record_id int,
    attendee_category varchar(250)
);


CREATE TABLE datamart.event_expense
(
    source_system_name varchar(255),
    event_number varchar(100),
    payment_id varchar(10),
    expense_category varchar(50),
    amount float,
    remit_to_id varchar(50),
    recipient_id varchar(50),
    check_number varchar(50),
    check_date timestamp,
    file_id int,
    record_id int
);


CREATE TABLE datamart.factory_sales_852
(
    trading_partner varchar(50),
    distribution_center varchar(50),
    distribution_center_dea_number varchar(20),
    reporting_date date,
    product_name varchar(50),
    description varchar(50),
    ndc varchar(20),
    basket_id int,
    basket_name varchar(300),
    qty_received float,
    qty_received_dollars float,
    qty_sold float,
    qty_sold_dollars float,
    qty_omit float,
    qty_omit_dollars float,
    month_end_qty_on_hand float,
    month_end_qty_on_hand_dollars float,
    month_end_committed float,
    month_end_committed_dollars float,
    month_end_reserved float,
    month_end_reserved_dollars float,
    qty_return float,
    qty_return_dollars float,
    qty_customer_return float,
    qty_customer_return_dollars float,
    file_id int,
    record_id int
);


CREATE TABLE datamart.formulary
(
    formulary_date timestamp,
    health_plan_id varchar(6),
    health_plan varchar(100),
    provider_id varchar(6),
    provider varchar(250),
    parent_id varchar(6),
    parent varchar(250),
    national_lives_count int,
    operating_state varchar(2),
    state_lives_count int,
    plan_type_name varchar(250),
    preferred_brand_tier varchar(64),
    drug_id varchar(6),
    drug_class varchar(100),
    drug varchar(100),
    basket_id int,
    basket_name varchar(300),
    generic varchar(10),
    manufacturer varchar(100),
    tier_code varchar(2),
    restrictions varchar(20),
    reason_code varchar(100),
    reason_code_description varchar(100),
    file_id int,
    record_id int
);


CREATE TABLE datamart.dddmd_demographics
(
    account_demo_id int,
    outlet_code varchar(10),
    ims_facility_number varchar(11),
    ims_prescriber_number varchar(7),
    category_code varchar(10),
    subcategory_code varchar(2),
    alignment_zip varchar(5),
    outlet_name varchar(100),
    outlet_address varchar(120),
    outlet_city varchar(40),
    outlet_state varchar(2),
    outlet_zip varchar(5),
    facility_name varchar(100),
    facility_address1 varchar(60),
    facility_address2 varchar(60),
    facility_address3 varchar(60),
    facility_address4 varchar(60),
    facility_city varchar(40),
    facility_state varchar(2),
    facility_zip varchar(5),
    prescriber_name varchar(100),
    prescriber_address1 varchar(60),
    prescriber_address2 varchar(60),
    prescriber_address3 varchar(60),
    prescriber_address4 varchar(60),
    prescriber_city varchar(40),
    prescriber_state varchar(2),
    prescriber_zip varchar(5),
    account_status varchar(1),
    tvcmid int,
    sales_force_id varchar(2),
    outlet_tvcmid int,
    facility_tvcmid int,
    prescriber_tvcmid int,
    tvcmid_assignment_rule varchar(25)
);


CREATE TABLE datamart.sfa_survey
(
    sales_force_id varchar(2),
    territory_number varchar(8),
    region_num varchar(8),
    area_num varchar(8),
    veeva_survey_target_id varchar(20),
    survey_name varchar(80),
    veeva_account_id varchar(20),
    survey_target_first_name varchar(50),
    survey_target_last_name varchar(50),
    status varchar(255),
    rep_id varchar(20),
    rep_first_name varchar(50),
    rep_last_name varchar(50),
    question_position int,
    question varchar(1000),
    response varchar(2500),
    tvcmid int,
    response_update_date date,
    response_create_date date
);


CREATE TABLE datamart.ims_outlet_master
(
    client_number varchar(3),
    outlet_number varchar(8),
    outlet_name varchar(50),
    address varchar(80),
    city varchar(40),
    state varchar(2),
    zip varchar(5),
    report_type varchar(2),
    status varchar(1),
    subcategory_code varchar(5),
    state_code varchar(2),
    county_code varchar(10),
    record_type varchar(3),
    file_id int,
    record_id int,
    retail_flag varchar(1),
    activity_date varchar(4),
    dea_number varchar(9)
);


CREATE TABLE datamart.ddd
(
    outlet_code varchar(10),
    outlet_name varchar(100),
    outlet_zip varchar(10),
    ims_client_number varchar(5),
    ims_report_number varchar(5),
    report_frequency varchar(20),
    ims_product_code varchar(10),
    basket_id int,
    basket_name varchar(300),
    data_date date,
    date date,
    rollup_week date,
    rollup_month date,
    comp_month date,
    quantity float,
    file_id int,
    record_id int,
    market_name varchar(75),
    outlet_tvcmid int,
    sales_force_id varchar(2),
    category_code varchar(2),
    rollup_flag char(1),
    basket_type varchar(100),
    rollup_445_month date,
    dollars float,
    COUNT float,
    subcategory_code varchar(10)
);


CREATE TABLE datamart.ddd_md
(
    onc_account_demo_id int,
    alt_seq_num varchar(20),
    outlet_name varchar(100),
    outlet_code varchar(10),
    subcategory_code varchar(5),
    outlet_zip varchar(5),
    ims_client_num varchar(5),
    ims_report_num varchar(5),
    report_frequency varchar(20),
    ims_product_code varchar(10),
    basket_id int,
    basket_name varchar(300),
    data_date date,
    date date,
    rollup_week date,
    rollup_month date,
    comp_month date,
    quantity float,
    dollars float,
    file_id int,
    record_id int,
    sales_force_id varchar(2),
    rollup_445_month date,
    tvcmid int,
    ims_facility_number varchar(11),
    ims_prescriber_number varchar(7),
    facility_tvcmid int,
    prescriber_tvcmid int,
    outlet_tvcmid int,
    normalized_quantity float
);


CREATE TABLE datamart.event_attendee
(
    source_system_name varchar(255),
    event_number varchar(100),
    employee_id varchar(20),
    attendee_id varchar(20),
    attendee_first_name varchar(50),
    attendee_middle_name varchar(50),
    attendee_last_name varchar(50),
    attendee_address varchar(100),
    attendee_city varchar(50),
    attendee_state varchar(100),
    attendee_zip varchar(100),
    attendee_phone varchar(15),
    attendee_fax varchar(15),
    attendee_email varchar(100),
    dea_number varchar(100),
    ims_number varchar(10),
    me_number varchar(10),
    npi_number varchar(10),
    attendee_category_code varchar(20),
    attended int,
    meal int,
    non_hcp_count int,
    other_hcp_count int,
    file_id int,
    record_id int,
    tvcmid int,
    attendee_title varchar(100),
    attendee_specialty varchar(100),
    attendee_degree varchar(100),
    attendee_address_line_2 varchar(100),
    attendee_address_line_3 varchar(100),
    attendee_address_line_4 varchar(100)
);


CREATE TABLE datamart.specialty_pharmacy_rx
(
    specialty_pharmacy_name varchar(50),
    sub_specialty_pharmacy_name varchar(50),
    pharmacy_npi varchar(10),
    ncpdp varchar(7),
    pharmacy_store_number varchar(20),
    pharmacy_address_1 varchar(100),
    pharmacy_address_2 varchar(100),
    pharmacy_city varchar(50),
    pharmacy_state varchar(2),
    pharmacy_zip varchar(10),
    pharmacy_phone varchar(20),
    pharmacy_fax varchar(20),
    dsp_patient_id varchar(100),
    gender varchar(1),
    age int,
    patient_state varchar(2),
    primary_icd9 varchar(20),
    secondary_icd9 varchar(20),
    prescriber_npi varchar(10),
    prescriber_name_first varchar(50),
    prescriber_name_last varchar(50),
    prescriber_address_1 varchar(100),
    prescriber_address_2 varchar(100),
    prescriber_city varchar(50),
    prescriber_state varchar(2),
    prescriber_zip varchar(10),
    prescriber_phone varchar(20),
    prescriber_fax varchar(20),
    basket_id int,
    basket_name varchar(300),
    drug_name varchar(50),
    drug_ndc_11 varchar(20),
    drug_strength varchar(20),
    drug_form varchar(20),
    package_size varchar(20),
    dose_form varchar(50),
    rx_number varchar(20),
    refill_number int,
    rx_refills_written int,
    dispense_qty int,
    days_supply int,
    rx_written_date date,
    rx_receipt_date date,
    fill_date date,
    rx_type varchar(1),
    copay numeric(18,4),
    primary_plan_name varchar(100),
    primary_bin varchar(20),
    primary_pcn varchar(20),
    secondary_plan_name varchar(100),
    secondary_bin varchar(20),
    secondary_pcn varchar(20),
    tertiary_plan_name varchar(100),
    tertiary_bin varchar(20),
    tertiary_pcn varchar(20),
    ship_date date,
    shipping_carrier varchar(20),
    file_id int,
    record_id int,
    prescriber_tvcmid int,
    pharmacy_tvcmid int
);


CREATE TABLE datamart.veeva_sync
(
    employee_id varchar(20),
    first_name varchar(50),
    last_name varchar(50),
    sync_date date,
    sync_type varchar(100),
    number_of_syncs int
);


CREATE TABLE datamart.aggregated_activity
(
    aggregated_id varchar(64),
    level varchar(64),
    federation_id varchar(200),
    source_name varchar(100),
    contact varchar(200),
    originating_id varchar(200),
    prior_activity varchar(64),
    activity_role_name varchar(100),
    count int,
    aggregated_type_name varchar(100),
    file_id int,
    record_id int
);


CREATE TABLE datamart.sample_shipment
(
    veeva_id varchar(25),
    tvcmid int,
    ims_id varchar(20),
    first_name varchar(50),
    middle_name varchar(50),
    last_name varchar(50),
    designation varchar(30),
    state_license_number varchar(20),
    address_line_1 varchar(35),
    address_line_2 varchar(35),
    address_line_3 varchar(35),
    city varchar(50),
    state varchar(2),
    zip varchar(10),
    dea_license_number varchar(20),
    order_id varchar(20),
    ndc varchar(15),
    basket_id int,
    basket_name varchar(300),
    order_job_code varchar(14),
    order_job_description varchar(50),
    ship_qty int,
    ship_date date,
    file_id int,
    record_id int,
    territory varchar(20),
    repid varchar(20),
    replastname varchar(50),
    repmiddlename varchar(50),
    repfirstname varchar(50),
    signature_type varchar(50),
    attendeename varchar(50),
    literature_product_id varchar(20),
    literature_product_name varchar(50)
);


CREATE TABLE datamart.sfa_call_detail
(
    sales_force_id varchar(2),
    call_id varchar(20),
    product varchar(30),
    basket_id int,
    basket_name varchar(300),
    detail_position int,
    indication varchar(5000)
);


CREATE TABLE datamart.enrollment_summary
(
    tvcmid int,
    ims_id varchar(10),
    npi varchar(10),
    veeva_account_id varchar(20),
    ndc varchar(11),
    indication varchar(5),
    week_ending date,
    in_progress_count int,
    completed_count int,
    cancelled_count int,
    prescriber_count int
);


CREATE TABLE datamart.specialty_pharmacy_patient_txn
(
    patient_yob numeric(4,0),
    patient_gender varchar(10),
    ims_surrogate_patient_id numeric(38,0),
    product_ndc varchar(15),
    product_name varchar(50),
    product_strength varchar(50),
    unit_of_measure varchar(50),
    extended_wac_price numeric(9,4),
    transaction_id varchar(20),
    patient_status_date date,
    patient_status_ varchar(50),
    patient_sub_status varchar(100),
    specialty_pharmacy_patient_or_case_id varchar(20),
    primary_icd_9 varchar(30),
    primary_icd_10 varchar(30),
    script_receipt_date date,
    primary_appeal_status varchar(50),
    primary_copay_type varchar(50),
    primary_deductible numeric(9,4),
    primary_pa_required varchar(10),
    primary_copay_amount numeric(9,4),
    primary_payer_name varchar(128),
    primary_plan_name varchar(70),
    primary_payer_type varchar(50),
    primary_plan_type varchar(50),
    primary_payer_reject_reason_code varchar(70),
    primary_reimbursement_status varchar(100),
    primary_reimbursement_status_date date,
    primary_step_therapy_required varchar(30),
    secondary_copay_type varchar(50),
    secondary_deductible numeric(9,4),
    secondary_pa_required varchar(10),
    secondary_copay_amount numeric(9,4),
    secondary_payer_name varchar(128),
    secondary_plan_name varchar(70),
    secondary_payer_type varchar(50),
    secondary_plan_type varchar(50),
    secondary_payer_reject_reason_code varchar(70),
    secondary_step_therapy_required varchar(30),
    ncpdp_number varchar(10),
    pharmacy_name varchar(75),
    pharmacy_zip varchar(10),
    prescribing_physician_first_name varchar(35),
    prescribing_physician_last_name varchar(35),
    prescribing_physician_middle_initial varchar(35),
    prescribing_physician_dea_number varchar(15),
    prescribing_physician_me_number varchar(10),
    prescribing_physician_npi_number varchar(15),
    prescribing_physician_address_1 varchar(70),
    prescribing_physician_address_2 varchar(70),
    prescribing_physician_city varchar(50),
    prescribing_physician_state varchar(20),
    prescribing_physician_zip varchar(5),
    number_of_fills_prescribed numeric(10,0),
    number_of_refills_remaining numeric(4,0),
    fill_type varchar(10),
    rx_date date,
    rx_number varchar(15),
    carrier varchar(50),
    date_of_drug_receipt date,
    initial_ship_date date,
    quantity_shipped numeric(9,4),
    out_of_pocket_cost numeric(9,4),
    shipment_date date,
    product_lot_number varchar(35),
    program_dispense_type varchar(50),
    days_supply_dispensed varchar(20),
    primary_payer_pa_outcome varchar(30),
    secondary_payer_pa_outcome varchar(30),
    rx_communication_method varchar(30),
    tertiary_icd_10 varchar(30),
    ims_file_id numeric(38,0),
    ims_transaction_id numeric(38,0),
    ims_cycle_date date,
    ims_supplier_id numeric(15,0),
    ims_supplier_name varchar(150),
    ims_transaction_type_code numeric(2,0),
    ims_duplicate_transaction varchar(1),
    ims_prescriber_id varchar(10),
    ims_phys_first_name varchar(50),
    ims_phys_last_name varchar(50),
    ims_phys_address varchar(40),
    ims_phys_city varchar(40),
    ims_phys_state varchar(14),
    ims_phys_zip varchar(5),
    ims_phys_specialty varchar(3),
    ims_product_id varchar(10),
    ims_product_description varchar(100),
    ims_outlet_id varchar(10),
    ims_outlet_name varchar(50),
    ims_outlet_address varchar(100),
    ims_outlet_city varchar(40),
    ims_outlet_state varchar(14),
    ims_outlet_zip varchar(5),
    ims_outlet_subcategory varchar(2),
    ims_plan_id varchar(10),
    ims_plan_name varchar(100),
    ims_plan_model varchar(50),
    primary_icd10_grouping varchar(20),
    primary_icd10_grouping_reason_code varchar(30),
    secondary_icd10_grouping varchar(20),
    secondary_icd10_grouping_reason_code varchar(30),
    ims_ndc_flag varchar(1),
    ims_dispensed_date_flag varchar(1),
    ims_dispensed_quantity_flag varchar(1),
    ims_cost_flag varchar(1),
    ims_overall_flag varchar(1),
    patient_months numeric(37,15),
    approved_indication varchar(5),
    tvcmid int,
    basket_id int,
    file_id int,
    record_id int
);


CREATE TABLE datamart.sales_geography
(
    sales_force_id varchar(4),
    geography_number varchar(15),
    geography_name varchar(100),
    geography_desc varchar(100),
    geography_type varchar(15),
    employee_type varchar(10),
    sales_team varchar(100),
    parent_geography_number varchar(15),
    fleet_eligible_flag varchar(1)
);


CREATE TABLE datamart.roster
(
    employee_id varchar(100),
    territory_number varchar(100),
    territory_name varchar(255),
    sales_force_id varchar(100),
    full_name varchar(100),
    first_name varchar(100),
    middle_name varchar(100),
    last_name varchar(100),
    address_line1 varchar(100),
    address_line2 varchar(100),
    address_line3 varchar(100),
    city varchar(100),
    state varchar(100),
    zip varchar(100),
    country varchar(100),
    business_address_line1 varchar(100),
    business_address_line2 varchar(100),
    business_address_line3 varchar(100),
    business_city varchar(100),
    business_state varchar(2),
    business_zip varchar(100),
    business_country varchar(100),
    shipping_address_line1 varchar(100),
    shipping_address_line2 varchar(100),
    shipping_address_line3 varchar(100),
    shipping_city varchar(100),
    shipping_state varchar(2),
    shipping_zip varchar(100),
    shipping_country varchar(100),
    business_phone varchar(100),
    home_phone varchar(100),
    mobile_phone varchar(100),
    fax varchar(100),
    voice_mail_extension varchar(100),
    email varchar(255),
    hire_date date,
    title varchar(100),
    rep_type varchar(10),
    username varchar(100),
    out_of_territory varchar(5),
    parent_territory_number varchar(100),
    company_code varchar(100),
    original_hire_date date,
    team varchar(100),
    salutation varchar(15),
    suffix varchar(15),
    cost_center varchar(30),
    sample_eligibility_flag varchar(10),
    samplestorage_address_line1 varchar(100),
    samplestorage_address_line2 varchar(100),
    samplestorage_address_line3 varchar(100),
    samplestorage_city varchar(100),
    samplestorage_zip varchar(100),
    samplestorage_state varchar(2),
    samplestorage_country varchar(100),
    hr_status varchar(100),
    reg_contract varchar(100),
    preferred_name varchar(100),
    business_unit_cd varchar(10),
    business_unit_name varchar(100),
    veeva_user_id varchar(100),
    mngr_employee_id varchar(100),
    birth_month_day varchar(5),
    calculated_rep_type varchar(20),
    job_code varchar(10),
    oracle_string varchar(50),
    global_employee_id varchar(35),
    supervisor_global_employee_id varchar(35),
    separation_date date,
    separation_reason varchar(100),
    fleet_eligible varchar(255),
    certified_field_trainer varchar(5),
    assignment_type varchar(255)
);


CREATE TABLE datamart.dx_code
(
    dx_code varchar(20),
    dx_description varchar(100)
);


CREATE TABLE datamart.dx_claims
(
    tvcmid int,
    ims_id varchar(7),
    npi varchar(10),
    dx_code varchar(20),
    month date,
    claim_count int,
    patient_count int,
    file_id int,
    record_id int
);


CREATE TABLE datamart.wholesaler_sales_867
(
    basket_id int,
    basket_name varchar(300),
    ndc varchar(20),
    product_description varchar(50),
    product_name varchar(25),
    trading_partner_name varchar(50),
    trading_partner_dea varchar(15),
    trading_partner_hin varchar(15),
    trading_partner_location_type varchar(5),
    trading_partner_dc_dea varchar(15),
    trading_partner_dc_hin varchar(15),
    trading_partner_dc_name varchar(50),
    trading_partner_dc_address varchar(50),
    trading_partner_dc_address_2 varchar(50),
    trading_partner_dc_city varchar(30),
    trading_partner_dc_state varchar(2),
    trading_partner_dc_zip varchar(10),
    class_of_trade varchar(50),
    outlet_location_name varchar(150),
    outlet_dea varchar(15),
    outlet_hin varchar(15),
    outlet_340b varchar(15),
    outlet_ncpdp varchar(15),
    outlet_npi varchar(15),
    outlet_location_address varchar(100),
    outlet_location_address_2 varchar(100),
    outlet_location_city varchar(30),
    outlet_location_state varchar(2),
    outlet_location_zip varchar(10),
    reporting_date date,
    rollup_reporting_month date,
    rollup_reporting_quarter varchar(7),
    contract_number varchar(30),
    contract_description varchar(30),
    invoice_number varchar(30),
    invoice_date date,
    invoice_line_id int,
    quanitity_stock_sales_ss int DEFAULT 0,
    ds_sales_ds int DEFAULT 0,
    summary_sales_su int DEFAULT 0,
    dock_to_dock_bq int DEFAULT 0,
    interbranch_ib int DEFAULT 0,
    return_to_useable_ru int DEFAULT 0,
    return_to_vendor_rv int DEFAULT 0,
    transfer_to_disposal_td int DEFAULT 0,
    adjusted_price numeric(37,15),
    gross_amount numeric(37,15),
    record_id int,
    file_id int,
    trx_count_normalized numeric(18,3)
);


CREATE TABLE datamart.xpd_core_metrics_antimigraine
(
    ims_client_number varchar(3),
    ims_report_number varchar(2),
    channel_indicator int,
    ims_id varchar(10),
    tvcmid int,
    specialty varchar(10),
    ims_product_group varchar(3),
    basket_id int,
    basket_name varchar(300),
    rollup_period date,
    xpo_nrx numeric(37,15),
    xpo_trx numeric(37,15),
    unknown_nrx numeric(37,15),
    unknown_trx numeric(37,15),
    new_therapy_starts numeric(37,15),
    continued_new numeric(37,15),
    switch_to numeric(37,15),
    add_on numeric(37,15),
    restart_same_new numeric(37,15),
    restart_different numeric(37,15),
    continued_refill numeric(37,15),
    restart_same_refill numeric(37,15),
    switch_from numeric(37,15),
    restart_different_from numeric(37,15),
    add_to numeric(37,15),
    market_new_to_brand_rx numeric(37,15),
    dynamic_capture_rx numeric(37,15),
    record_id int,
    file_id int,
    report_frequency varchar(20)
);


CREATE TABLE datamart.xpd_demographics_antimigraine
(
    ims_client_number varchar(3),
    ims_report_number varchar(2),
    ims_id varchar(10),
    tvcmid int,
    last_name varchar(40),
    first_name varchar(40),
    middle_name varchar(40),
    address_1 varchar(40),
    address_2 varchar(40),
    city varchar(40),
    state varchar(2),
    zip varchar(5),
    specialty varchar(3),
    specialty_description varchar(25),
    trx_decile_retail int,
    nrx_decile_retail int,
    nbrx_decile_retail int,
    trx_decile_mail int,
    nrx_decile_mail int,
    nbrx_decile_mail int,
    market_prescriber_reliability_retail varchar(2),
    market_prescriber_reliability_mail varchar(2),
    record_id int,
    file_id int,
    report_frequency varchar(20)
);


CREATE TABLE datamart.xpd_switch_details_antimigraine
(
    ims_client_number varchar(3),
    ims_report_number varchar(2),
    channel_indicator int,
    ims_id varchar(10),
    tvcmid int,
    specialty varchar(10),
    switch_from_product_group_num varchar(3),
    switch_from_basket_id int,
    switch_from_basket_name varchar(300),
    switch_to_product_group_num varchar(3),
    switch_to_basket_id int,
    switch_to_basket_name varchar(300),
    rollup_period date,
    rx numeric(37,15),
    record_id int,
    file_id int,
    report_frequency varchar(20)
);


CREATE TABLE datamart.drm45_product_list
(
    file_location varchar(255),
    source_name varchar(255),
    file_code varchar(8),
    product_group varchar(8),
    product_name varchar(100),
    mfg_number varchar(10),
    status varchar(10),
    cmf_code varchar(20),
    product_description varchar(255),
    mfg_name varchar(100),
    usc_code varchar(10),
    file_id int,
    record_id int
);


CREATE TABLE datamart.activity_hub
(
    activity_id varchar(64),
    federation_id varchar(200),
    contact varchar(200),
    source_name varchar(100),
    "datetime" timestamp,
    trackback_id varchar(200),
    previous_activity varchar(64),
    level_name varchar(64),
    activity_role_name varchar(100),
    type_name varchar(100),
    native_type varchar(200),
    details varchar(200),
    line_item_id varchar(64),
    brand_name varchar(200),
    activity varchar(200),
    line_item_datetime timestamp,
    line_item_previous_line_item varchar(200),
    line_item_trackback_id varchar(200),
    line_item_details varchar(200),
    line_item_type_name varchar(100),
    line_item_native_type varchar(200),
    basket_id varchar(64),
    web_url varchar(5000)
);


CREATE TABLE datamart.xpd_add_on_details
(
    ims_client_number varchar(3),
    ims_report_number varchar(2),
    channel_indicator int,
    ims_id varchar(10),
    tvcmid int,
    specialty varchar(10),
    addon_from_product_group_num varchar(3),
    addon_from_basket_id int,
    addon_from_basket_name varchar(300),
    addon_to_product_group_num varchar(3),
    addon_to_basket_id int,
    addon_to_basket_name varchar(300),
    rollup_period date,
    addon_rx numeric(37,15),
    report_frequency varchar(20),
    record_id int,
    file_id int
);


CREATE TABLE datamart.xpd_restart_diff_details
(
    ims_client_number varchar(3),
    ims_report_number varchar(2),
    channel_indicator int,
    ims_id varchar(10),
    tvcmid int,
    specialty varchar(10),
    restart_from_product_group_num varchar(3),
    restart_from_basket_id int,
    restart_from_basket_name varchar(300),
    restart_to_product_group_num varchar(3),
    restart_to_basket_id int,
    restart_to_basket_name varchar(300),
    rollup_period date,
    restart_diff_rx numeric(37,15),
    report_frequency varchar(20),
    record_id int,
    file_id int
);


CREATE TABLE datamart.xpd_core_metrics_respiratory
(
    ims_client_number varchar(3),
    ims_report_number varchar(2),
    channel_indicator int,
    ims_id varchar(10),
    tvcmid int,
    specialty varchar(10),
    ims_product_group varchar(3),
    basket_id int,
    basket_name varchar(300),
    rollup_period date,
    xpo_nrx numeric(37,15),
    xpo_trx numeric(37,15),
    unknown_nrx numeric(37,15),
    unknown_trx numeric(37,15),
    new_therapy_starts numeric(37,15),
    continued_new numeric(37,15),
    switch_to numeric(37,15),
    add_on numeric(37,15),
    restart_same_new numeric(37,15),
    restart_different numeric(37,15),
    continued_refill numeric(37,15),
    restart_same_refill numeric(37,15),
    switch_from numeric(37,15),
    restart_different_from numeric(37,15),
    add_to numeric(37,15),
    market_new_to_brand_rx numeric(37,15),
    dynamic_capture_rx numeric(37,15),
    record_id int,
    file_id int,
    report_frequency varchar(20)
);


CREATE TABLE datamart.xpd_demographics_respiratory
(
    ims_client_number varchar(3),
    ims_report_number varchar(2),
    ims_id varchar(10),
    tvcmid int,
    last_name varchar(40),
    first_name varchar(40),
    middle_name varchar(40),
    address_1 varchar(40),
    address_2 varchar(40),
    city varchar(40),
    state varchar(2),
    zip varchar(5),
    specialty varchar(3),
    specialty_description varchar(25),
    trx_decile_retail int,
    nrx_decile_retail int,
    nbrx_decile_retail int,
    trx_decile_mail int,
    nrx_decile_mail int,
    nbrx_decile_mail int,
    market_prescriber_reliability_retail varchar(2),
    market_prescriber_reliability_mail varchar(2),
    record_id int,
    file_id int,
    report_frequency varchar(20)
);


CREATE TABLE datamart.xpd_switch_details_respiratory
(
    ims_client_number varchar(3),
    ims_report_number varchar(2),
    channel_indicator int,
    ims_id varchar(10),
    tvcmid int,
    specialty varchar(10),
    switch_from_product_group_num varchar(3),
    switch_from_basket_id int,
    switch_from_basket_name varchar(300),
    switch_to_product_group_num varchar(3),
    switch_to_basket_id int,
    switch_to_basket_name varchar(300),
    rollup_period date,
    rx numeric(37,15),
    record_id int,
    file_id int,
    report_frequency varchar(20)
);


CREATE TABLE datamart.ddd_adhoc
(
    outlet_code varchar(10),
    outlet_name varchar(100),
    outlet_zip varchar(10),
    ims_client_number varchar(5),
    ims_report_number varchar(5),
    report_frequency varchar(20),
    ims_product_code varchar(10),
    basket_id int,
    basket_name varchar(300),
    data_date date,
    date date,
    rollup_week date,
    rollup_month date,
    comp_month date,
    quantity float,
    file_id int,
    record_id int,
    market_name varchar(75),
    outlet_tvcmid int,
    sales_force_id varchar(2),
    category_code varchar(2),
    rollup_flag char(1),
    basket_type varchar(100),
    rollup_445_month date,
    dollars float,
    COUNT float,
    subcategory_code varchar(10)
);


CREATE TABLE datamart.fia_adhoc
(
    basket_id int,
    basket_name varchar(300),
    claim_id varchar(64),
    patient_id int,
    sequence_number int,
    product_id varchar(11),
    fill_date date,
    claim_type varchar(2),
    reject_code varchar(3),
    days_supply numeric(10,6),
    quantity varchar(12),
    refill_code int,
    payer_plan_id varchar(10),
    opc_ask varchar(10),
    sec_payer_plan_id varchar(10),
    buy_down varchar(11),
    opc_paid varchar(10),
    prescriber_id varchar(20),
    sob varchar(1),
    sub_product_id varchar(11),
    sub_opc varchar(10),
    initial_claim_id varchar(64),
    prev_product_id varchar(11),
    daw_code varchar(2),
    wrt_date date,
    claim_status varchar(1),
    copay_card_flg varchar(4),
    zip_code varchar(5),
    ecoup_flag int,
    ecoup_offset_amt numeric(10,2),
    standard_copay numeric(10,2),
    standard_copay_yn varchar(1),
    market_id int,
    flexible_fld_1_char varchar(50),
    flexible_fld_2_char varchar(50),
    flexible_fld_3_char varchar(50),
    flexible_fld_4_char varchar(50),
    file_id int,
    record_id int,
    cbsa_code varchar(5),
    cbsa_description varchar(100),
    state_code varchar(2),
    payer_name varchar(64),
    plan_name varchar(64),
    pbm_name varchar(60),
    pbm_id varchar(6),
    method_of_payment varchar(50),
    model_type varchar(64),
    product_group varchar(80),
    product_group_id int,
    product_name varchar(100),
    generic_name varchar(100),
    brand_generic_flag varchar(1),
    product_form varchar(100),
    product_strength varchar(100),
    package_size float,
    manufacturer varchar(100),
    cmf10 varchar(10),
    usc_code varchar(5),
    fia_market_desc varchar(50),
    reject_reason varchar(200),
    reject_group varchar(50),
    mpd_year int,
    mpd_eligibility_class varchar(11),
    deductible_start_date date,
    copay_start_date date,
    gap_start_date date,
    catastrophic_start_date date,
    mpd_panel_patient int,
    PROVIDER_TYPE varchar(2),
    IQVIA_RXER_ID varchar(7),
    PRIMARY_SPECIALTY_CODE varchar(10),
    PRIMARY_SPECIALTY_DESC varchar(100),
    FIRST_NAME varchar(100),
    LAST_NAME varchar(100),
    ORG_NM varchar(50),
    ADDRESS varchar(200),
    CITY varchar(100),
    PVR_ZIP_CODE varchar(5),
    PVR_STATE_CODE varchar(2),
    PHONE_NUMBER varchar(20),
    DEA_NUMBER varchar(20),
    ME_NUMBER varchar(20),
    PVR_FLEXIBLE_FLD_1_CHAR varchar(50),
    PVR_FLEXIBLE_FLD_2_CHAR varchar(50)
);


CREATE TABLE datamart.titration_dosage
(
    TVCM_ID int,
    IMS_ID varchar(50),
    product_id int,
    PRODUCT_NAME varchar(50),
    Data_Type varchar(50),
    Avg_TD_Daily_Dose_New_Patient numeric(10,3),
    Avg_TD_Daily_Dose_Cont_Patient numeric(10,3),
    Data_Ending_Month date,
    file_id int
);


CREATE  VIEW datamart.territory_region_area_hierarchy AS
 SELECT a.geography_number AS territory_number,
        a.geography_name AS territory_name,
        b.geography_number AS region_number,
        b.geography_name AS region_name,
        c.geography_number AS area_number,
        c.geography_name AS area_name
 FROM ((datamart.sales_geography a LEFT  JOIN datamart.sales_geography b ON ((a.parent_geography_number = b.geography_number))) LEFT  JOIN datamart.sales_geography c ON ((b.parent_geography_number = c.geography_number)))
 ORDER BY a.geography_number;