CONNECT TO VERTICA vaasdemo USER dbadmin PASSWORD 'Alabama7878!' ON '35.166.171.38' , 5433;
COPY /*28*/ aetna.provider_specialty_sql_src FROM VERTICA teva.aetna.provider_specialty_sql_src;
COPY /*196*/ aetna.provider_base_db2_src FROM VERTICA teva.aetna.provider_base_db2_src;
COPY /*198*/ aetna.provider_loc_sql_src FROM VERTICA teva.aetna.provider_loc_sql_src;
COPY /*198*/ aetna.provider_base_sql_src FROM VERTICA teva.aetna.provider_base_sql_src;
COPY /*200*/ aetna.provider_specialty_db2_src FROM VERTICA teva.aetna.provider_specialty_db2_src;
COPY /*80000*/ aetna.specialty FROM VERTICA teva.aetna.specialty;
COPY /*27912300*/ aetna.specialty_int FROM VERTICA teva.aetna.specialty_int;
COPY /*27912300*/ aetna.provider_base_src FROM VERTICA teva.aetna.provider_base_src;
COPY /*27912300*/ aetna.provider_base_dup FROM VERTICA teva.aetna.provider_base_dup;
DISCONNECT vaasdemo;
