GRANT CREATE ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapDelimitedExtractor(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapLookup() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_Geography(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_GeometryPoint(Float, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_GetExportShapefileDirectory() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(Float, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Area(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Boundary(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Centroid(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeometryType(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Touches(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Within(geography, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_XMax(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.aws_set_config(Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.FlexTokenizer() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MSE(Float, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapKeys(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Create_Index(Integer, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_inverse_svd() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.get_model_attribute() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.rf_predictor_importance() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.rsquared(Float, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.APPROXIMATE_MEDIAN(Float) TO public;
GRANT EXECUTE ON FUNCTION public.EmptyMap() TO public;
GRANT EXECUTE ON FUNCTION public.MapToString(Long Varbinary) TO public;
GRANT EXECUTE ON FUNCTION public.STV_Geography(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Disjoint(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeometryType(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeometryType(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_IsSimple(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_NumPoints(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_NumPoints(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Relate(geometry, geometry, Char) TO public;
GRANT EXECUTE ON FUNCTION public.ST_SRID(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Simplify(geometry, Float) TO public;
GRANT EXECUTE ON FUNCTION public.ST_X(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.isOrContains(map Long Varchar, val Varchar) TO public;
GRANT EXECUTE ON FUNCTION v_func.Soundex_matches(Varchar, Varchar) TO public;
GRANT EXECUTE ON FUNCTION v_txtindex.Stemmer(v Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapAggregate(Long Varchar, Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapValuesOrField(Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Intersect(Integer, geography) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_LineStringPoint(Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_NN(geography, geography, Integer) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_PolygonPoint(geometry) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_rf_classifier_classes() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.FourGrams(Varchar) TO public;
GRANT SELECT ON v_catalog.comments TO public;
GRANT SELECT ON v_catalog.hcatalog_columns TO public;
GRANT SELECT ON v_catalog.hcatalog_tables TO public;
GRANT SELECT ON v_catalog.projections TO public;
GRANT SELECT ON v_catalog.user_function_parameters TO public;
GRANT SELECT ON v_internal.dc_analyze_statistics TO public;
GRANT SELECT ON v_internal.dc_cluster_events TO public;
GRANT SELECT ON v_internal.dc_depot_evictions TO public;
GRANT SELECT ON v_internal.dc_file_reads TO public;
GRANT SELECT ON v_internal.dc_mars_operations TO public;
GRANT SELECT ON v_internal.dc_node_oid_cache TO public;
GRANT SELECT ON v_internal.dc_runtime_priority_changes TO public;
GRANT SELECT ON v_internal.dc_session_temprel_events TO public;
GRANT SELECT ON v_internal.recv_protocol TO public;
GRANT SELECT ON v_internal.system TO public;
GRANT SELECT ON v_internal.vs_blob_chunks TO public;
GRANT SELECT ON v_internal.vs_catalog_event_restore TO public;
GRANT SELECT ON v_internal.vs_deployment_projection_statements TO public;
GRANT SELECT ON v_internal.vs_deployments TO public;
GRANT SELECT ON v_internal.vs_depot_pin_policies TO public;
GRANT SELECT ON v_internal.vs_depot_size TO public;
GRANT SELECT ON v_internal.vs_local_nodes TO public;
GRANT SELECT ON v_internal.vs_logical_statistics TO public;
GRANT SELECT ON v_internal.vs_models TO public;
GRANT SELECT ON v_internal.vs_parameters_mismatch TO public;
GRANT SELECT ON v_internal.vs_partitions TO public;
GRANT SELECT ON v_internal.vs_plan_phases TO public;
GRANT SELECT ON v_internal.vs_resource_acquisitions TO public;
GRANT SELECT ON v_internal.vs_view_tables TO public;
GRANT SELECT ON v_monitor.critical_nodes TO public;
GRANT SELECT ON v_monitor.depot_evictions TO public;
GRANT SELECT ON v_monitor.depot_files TO public;
GRANT SELECT ON v_monitor.disk_resource_rejections TO public;
GRANT SELECT ON v_monitor.node_resources TO public;
GRANT SELECT ON v_monitor.recovery_status TO public;
GRANT SELECT ON v_monitor.sessions TO public;
GRANT SELECT ON v_monitor.storage_containers TO public;
ALTER SCHEMA atlas DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA brdbeer DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA commodity DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA cortex DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA migration DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA public DEFAULT EXCLUDE PRIVILEGES;
ALTER TABLE atlas.arrivals_src EXCLUDE PRIVILEGES;
ALTER TABLE beer.events_by_user EXCLUDE PRIVILEGES;
ALTER TABLE commodity.daily_futures EXCLUDE PRIVILEGES;
ALTER TABLE cortex.flight EXCLUDE PRIVILEGES;
ALTER TABLE masterdata.places_src EXCLUDE PRIVILEGES;
ALTER TABLE aetna.address_int OWNER TO dbadmin;
ALTER TABLE aetna.specialty_int OWNER TO dbadmin;
ALTER TABLE atlas.big_report OWNER TO dbadmin;
ALTER TABLE atlas.date_dim_src OWNER TO dbadmin;
ALTER TABLE click.main_fact OWNER TO dbadmin;
ALTER TABLE ehr.icd_nine_lkp_src OWNER TO dbadmin;
ALTER TABLE masterdata.lsad_lkp OWNER TO dbadmin;
GRANT DELETE ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Timestamp) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Uuid) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.EmptyMap() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_AsText(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Crosses(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromText(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromText(Long Varchar, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_IsValid(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_NumGeometries(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_PointN(geography, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_XMax(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_txtindex.DELETE_TOKENIZER_CONFIG_FILE() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON PARSER public.FAvroParser() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON PARSER public.FCsvParser() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON PARSER public.STV_ShpParser() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapItems() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapValuesOrField(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.OrcExport() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Intersect(Integer, Float, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_normalize() TO dbadmin WITH GRANT OPTION;
GRANT REFERENCES ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT SELECT ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdSynToCount(Long Varbinary) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Long Varbinary) TO public;
GRANT EXECUTE ON FUNCTION public.MapContainsValue(Long Varbinary, Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.MapPut() TO public;
GRANT EXECUTE ON FUNCTION public.MapVersion(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.STV_ForceLHR(geography) TO public;
GRANT EXECUTE ON FUNCTION public.STV_Geometry(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_AsBinary(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Boundary(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Contains(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Disjoint(Long Varchar, Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeoHash(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromWKB(Long Varbinary, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Intersection(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_YMax(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_YMin(geometry) TO public;
GRANT EXECUTE ON FUNCTION v_txtindex.caseInsensitiveNoStemming(x Long Varchar) TO public;
GRANT EXECUTE ON PARSER public.FAvroParser() TO public;
GRANT EXECUTE ON PARSER public.FDelimitedPairParser() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.DelimitedExport() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Drop_Index() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_svd() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.reverse_normalize() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.StringTokenizerDelim(Varchar, Varchar) TO public;
GRANT SELECT ON v_catalog.ca_bundles TO public;
GRANT SELECT ON v_catalog.catalog_subscription_changes TO public;
GRANT SELECT ON v_catalog.certificates TO public;
GRANT SELECT ON v_catalog.cryptographic_keys TO public;
GRANT SELECT ON v_catalog.fault_groups TO public;
GRANT SELECT ON v_catalog.hcatalog_schemata TO public;
GRANT SELECT ON v_catalog.profiles TO public;
GRANT SELECT ON v_catalog.projection_delete_concerns TO public;
GRANT SELECT ON v_catalog.resource_pools TO public;
GRANT SELECT ON v_catalog.types TO public;
GRANT SELECT ON v_internal.dc_optimizer_events TO public;
GRANT SELECT ON v_internal.dc_plan_activity_details TO public;
GRANT SELECT ON v_internal.dc_plan_resource_phases TO public;
GRANT SELECT ON v_internal.dc_reparenting TO public;
GRANT SELECT ON v_internal.dc_resource_pool_history TO public;
GRANT SELECT ON v_internal.dc_roses_committed TO public;
GRANT SELECT ON v_internal.dc_udfs_events TO public;
GRANT SELECT ON v_internal.vs_catalog_event_truncate TO public;
GRANT SELECT ON v_internal.vs_catalog_event_truncate_catalog TO public;
GRANT SELECT ON v_internal.vs_data_channels_closed TO public;
GRANT SELECT ON v_internal.vs_dv_ros TO public;
GRANT SELECT ON v_internal.vs_logicalstats_regular_colstats TO public;
GRANT SELECT ON v_internal.vs_node_dependencies TO public;
GRANT SELECT ON v_internal.vs_plan_activities TO public;
GRANT SELECT ON v_internal.vs_plan_step_properties TO public;
GRANT SELECT ON v_internal.vs_projection_column_expressions TO public;
GRANT SELECT ON v_internal.vs_projection_column_order TO public;
GRANT SELECT ON v_internal.vs_projection_columns TO public;
GRANT SELECT ON v_internal.vs_projection_refreshes TO public;
GRANT SELECT ON v_internal.vs_projection_user_defined_transforms TO public;
GRANT SELECT ON v_internal.vs_projections TO public;
GRANT SELECT ON v_internal.vs_ros_segment_bounds TO public;
GRANT SELECT ON v_internal.vs_schemata TO public;
GRANT SELECT ON v_internal.vs_subnets TO public;
GRANT SELECT ON v_internal.vs_text_index_arguments TO public;
GRANT SELECT ON v_internal.vs_uploader_tasks TO public;
GRANT SELECT ON v_internal.vs_user_function_parameters TO public;
GRANT SELECT ON v_internal.vs_view_columns TO public;
GRANT SELECT ON v_monitor.critical_hosts TO public;
GRANT SELECT ON v_monitor.deployment_projection_statements TO public;
GRANT SELECT ON v_monitor.design_tables TO public;
GRANT SELECT ON v_monitor.output_query_plan_costs TO public;
GRANT SELECT ON v_monitor.partition_columns TO public;
GRANT SELECT ON v_monitor.resource_queues TO public;
GRANT USAGE ON SCHEMA v_func TO public;
ALTER SCHEMA logistics DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA masterdata DEFAULT EXCLUDE PRIVILEGES;
ALTER DATABASE vaasdemo SET disableinheritedprivileges = 0;
ALTER DATABASE vaasdemo SET disableinheritedprivileges = 0;
ALTER DATABASE vaasdemo SET disableinheritedprivileges = 0;
ALTER TABLE aetna.address EXCLUDE PRIVILEGES;
ALTER TABLE aetna.provider_base_sql_src EXCLUDE PRIVILEGES;
ALTER TABLE aetna.provider_base_src EXCLUDE PRIVILEGES;
ALTER TABLE beer.zipcode EXCLUDE PRIVILEGES;
ALTER TABLE click.main_fact EXCLUDE PRIVILEGES;
ALTER TABLE ehr.departments_src EXCLUDE PRIVILEGES;
ALTER TABLE ehr.hospitals_src EXCLUDE PRIVILEGES;
ALTER TABLE masterdata.lsad_lkp EXCLUDE PRIVILEGES;
ALTER TABLE migration.odd_parms_src EXCLUDE PRIVILEGES;
ALTER VIEW ehr.admission_vw EXCLUDE PRIVILEGES; 
ALTER TABLE aetna.provider_specialty_sql_src OWNER TO dbadmin;
ALTER TABLE atlas.region_dim OWNER TO dbadmin;
ALTER TABLE beer.adj_drinkers OWNER TO dbadmin;
ALTER TABLE beer.events OWNER TO dbadmin;
ALTER TABLE ehr.drugs OWNER TO dbadmin;
ALTER TABLE migration.source_schemas OWNER TO dbadmin;
ALTER VIEW ehr.admission_vw OWNER TO dbadmin;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdDataToLongSyn(Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Interval Day to Second) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_DWithin(geography, geography, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Area(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Difference(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Distance(geography, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeoHash(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeoHash(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeometryN(Long Varchar, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeometryN(geometry, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Intersects(geography, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Length(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Length(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Relate(geometry, geometry, Char) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_SRID(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_SimplifyPreserveTopology(geometry, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Transform(geometry, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Y(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_YMin(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.SetMapKeys() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_naive_bayes() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_svm_classifier() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_txtindex.GET_TOKENIZER_PARAMETER(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON PARSER public.FJSONParser() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapKeysInfo(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Create_Index(Integer, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Intersect(Integer, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Refresh_Index(Integer, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.approximate_quantiles() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.error_rate() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.reverse_normalize() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.AdvancedLogTokenizer() TO dbadmin WITH GRANT OPTION;
GRANT REFERENCES ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT USAGE ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.PickBestType(Varchar) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION public.ST_Union(geometry) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Date) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Interval Day to Second) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Time) TO public;
GRANT EXECUTE ON FUNCTION public.MapRegexExtractor(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.STV_AsGeoJSON(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.STV_AsGeoJSON(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.STV_IsValidReason(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.STV_MemSize(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_AsBinary(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Distance(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeoHash(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_NumGeometries(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_PointFromGeoHash(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.apply_kmeans() TO public;
GRANT EXECUTE ON FUNCTION public.get_model_summary() TO public;
GRANT EXECUTE ON FUNCTION v_func.Soundex(Varchar) TO public;
GRANT EXECUTE ON FUNCTION v_txtindex.DELETE_TOKENIZER_CONFIG_FILE() TO public;
GRANT EXECUTE ON FUNCTION v_txtindex.GET_TOKENIZER_PARAMETER(Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapValues(Long Varbinary) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Export2Shapefile() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Intersect(Integer, Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_PolygonPoint(geography) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Date) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.corr_matrix() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_moving_average() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.read_tree() TO public;
GRANT SELECT ON v_catalog.log_tables TO public;
GRANT SELECT ON v_catalog.nodes TO public;
GRANT SELECT ON v_catalog.roles TO public;
GRANT SELECT ON v_catalog.sequences TO public;
GRANT SELECT ON v_catalog.session_subscriptions TO public;
GRANT SELECT ON v_catalog.tables TO public;
GRANT SELECT ON v_catalog.views TO public;
GRANT SELECT ON v_internal.dc_blob_chunk_events TO public;
GRANT SELECT ON v_internal.dc_catalog_refcounts TO public;
GRANT SELECT ON v_internal.dc_deployment_projections TO public;
GRANT SELECT ON v_internal.dc_merge_events TO public;
GRANT SELECT ON v_internal.dc_plan_parallel_zones TO public;
GRANT SELECT ON v_internal.dc_plan_phases TO public;
GRANT SELECT ON v_internal.dc_projection_recoveries TO public;
GRANT SELECT ON v_internal.dc_resource_rejections TO public;
GRANT SELECT ON v_internal.dc_scan_events TO public;
GRANT SELECT ON v_internal.dc_ts_transfers TO public;
GRANT SELECT ON v_internal.design_configs TO public;
GRANT SELECT ON v_internal.design_output_query_projections_report TO public;
GRANT SELECT ON v_internal.send_protocol TO public;
GRANT SELECT ON v_internal.vs_catalog_event_add_derived_column TO public;
GRANT SELECT ON v_internal.vs_catalog_event_refresh_columns TO public;
GRANT SELECT ON v_internal.vs_catalog_event_replace TO public;
GRANT SELECT ON v_internal.vs_catalog_sync_state TO public;
GRANT SELECT ON v_internal.vs_deployment_status TO public;
GRANT SELECT ON v_internal.vs_epoch_map TO public;
GRANT SELECT ON v_internal.vs_hcatalog_configurations TO public;
GRANT SELECT ON v_internal.vs_logical_colstats_histogram TO public;
GRANT SELECT ON v_internal.vs_logicalstats_datapages TO public;
GRANT SELECT ON v_internal.vs_mergeoutcache_ros TO public;
GRANT SELECT ON v_internal.vs_plan_steps TO public;
GRANT SELECT ON v_internal.vs_ros_containers TO public;
GRANT SELECT ON v_internal.vs_segments_helper TO public;
GRANT SELECT ON v_internal.vs_shards TO public;
GRANT SELECT ON v_internal.vs_tables TO public;
GRANT SELECT ON v_internal.vs_views TO public;
GRANT SELECT ON v_monitor.design_queries TO public;
GRANT SELECT ON v_monitor.partition_reorganize_errors TO public;
GRANT SELECT ON v_monitor.query_plan_profiles TO public;
GRANT SELECT ON v_monitor.resource_acquisitions TO public;
GRANT SELECT ON v_monitor.session_profiles TO public;
ALTER SCHEMA survey DEFAULT EXCLUDE PRIVILEGES;
ALTER TABLE aetna.address_int EXCLUDE PRIVILEGES;
ALTER TABLE atlas.mock_dealer EXCLUDE PRIVILEGES;
ALTER TABLE brdbeer.page_dimension EXCLUDE PRIVILEGES;
ALTER TABLE cops.event_flx_keys EXCLUDE PRIVILEGES;
ALTER TABLE ehr.accounts_src EXCLUDE PRIVILEGES;
ALTER TABLE masterdata.funcstat_lkp EXCLUDE PRIVILEGES;
ALTER TABLE migration.target_grants_src EXCLUDE PRIVILEGES;
ALTER TABLE atlas.control OWNER TO dbadmin;
ALTER TABLE cortex.flight OWNER TO dbadmin;
ALTER TABLE cortex.new_flight OWNER TO dbadmin;
ALTER TABLE masterdata.names_01_src OWNER TO dbadmin;
ALTER TABLE segment.retail OWNER TO dbadmin;
GRANT ALTER ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Interval Year to Month) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON ANALYTIC FUNCTION v_func.argmin() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapContainsValue(Long Varbinary, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapContainsValue(Long Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_AsGeoJSON(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_AsGeoJSON(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_DWithin(Long Varchar, Long Varchar, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_DWithin(geometry, geometry, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_IsValidReason(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Equals(Long Varchar, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_IsEmpty(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_NumPoints(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_PointFromGeoHash(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Within(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_XMin(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_XMin(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_xgb_classifier() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_txtindex.StemmerCaseInsensitive(v Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.ROC() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_LineStringPoint(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Date) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.corr_matrix() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.BasicLogTokenizer() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.TwoGrams(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Long Varchar) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Varbinary) TO public;
GRANT EXECUTE ON FUNCTION public.MapContainsKey(Long Varchar, Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.MapLookup(Long Varchar, Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.STV_IsValidReason(geography) TO public;
GRANT EXECUTE ON FUNCTION public.STV_Reverse(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Centroid(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Distance(geography, geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeographyFromWKB(Long Varbinary) TO public;
GRANT EXECUTE ON FUNCTION public.ST_NumGeometries(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_NumGeometries(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Overlaps(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Transform(geometry, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Union(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Within(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_XMin(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Y(geometry) TO public;
GRANT EXECUTE ON PARSER public.FCefParser() TO public;
GRANT EXECUTE ON SOURCE public.STV_ShpSource() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Explode() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.ParquetExportMulti() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.ROC() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.AdvancedLogTokenizer() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.StringTokenizer() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.WhitespaceLogTokenizer() TO public;
GRANT SELECT ON v_catalog.constraint_columns TO public;
GRANT SELECT ON v_catalog.dual TO public;
GRANT SELECT ON v_catalog.inherited_privileges TO public;
GRANT SELECT ON v_catalog.profile_parameters TO public;
GRANT SELECT ON v_catalog.storage_locations TO public;
GRANT SELECT ON v_catalog.system_columns TO public;
GRANT SELECT ON v_catalog.vs_tls_configurations TO public;
GRANT SELECT ON v_internal.catalog_events TO public;
GRANT SELECT ON v_internal.dc_cpu_affinity_changes TO public;
GRANT SELECT ON v_internal.dc_lock_attempts TO public;
GRANT SELECT ON v_internal.dc_projection_refreshes_completed TO public;
GRANT SELECT ON v_internal.design_output_projection_columns_report TO public;
GRANT SELECT ON v_internal.design_output_projections_report TO public;
GRANT SELECT ON v_internal.design_output_query_plan_costs TO public;
GRANT SELECT ON v_internal.tombstones TO public;
GRANT SELECT ON v_internal.vs_catalog_event_move_partition TO public;
GRANT SELECT ON v_internal.vs_design_segmented_projection_data_distribution TO public;
GRANT SELECT ON v_internal.vs_dfs_file_distributions TO public;
GRANT SELECT ON v_internal.vs_ldap_link_info TO public;
GRANT SELECT ON v_internal.vs_local_projections TO public;
GRANT SELECT ON v_internal.vs_mergeout_request_tracker_queue TO public;
GRANT SELECT ON v_internal.vs_storage_reference_counts TO public;
GRANT SELECT ON v_internal.vs_system_views TO public;
GRANT SELECT ON v_internal.vs_wos_containers TO public;
GRANT SELECT ON v_monitor.blob_chunks TO public;
GRANT SELECT ON v_monitor.column_storage TO public;
GRANT SELECT ON v_monitor.critical_subclusters TO public;
GRANT SELECT ON v_monitor.database_snapshots TO public;
GRANT SELECT ON v_monitor.lock_usage TO public;
GRANT SELECT ON v_monitor.strata_structures TO public;
GRANT SELECT ON v_monitor.table_statistics TO public;
GRANT USAGE ON SCHEMA v_catalog TO public;
GRANT USAGE ON SCHEMA v_internal TO public;
GRANT USAGE ON SCHEMA v_txtindex TO public;
ALTER TABLE brdbeer.user_agent EXCLUDE PRIVILEGES;
ALTER TABLE cortex.new_flight EXCLUDE PRIVILEGES;
ALTER TABLE segment.online_sales EXCLUDE PRIVILEGES;
ALTER TABLE survey.opioid_src EXCLUDE PRIVILEGES;
ALTER TABLE aetna.provider_base OWNER TO dbadmin;
ALTER TABLE aetna.provider_base_dup OWNER TO dbadmin;
ALTER TABLE beer.beer_hours OWNER TO dbadmin;
ALTER TABLE cortex.iata_xref OWNER TO dbadmin;
ALTER TABLE logistics.test OWNER TO dbadmin;
ALTER TABLE survey.opioid_src OWNER TO dbadmin;
GRANT CREATE ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdDataToSyn(Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdSynToCount(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Time) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapContainsKey(Long Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapLookup(Long Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_GeometryPoint(Float, Float, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_IsValidReason(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_SetExportShapefileDirectory() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_AsBinary(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_AsText(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Disjoint(Long Varchar, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Distance(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromWKB(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeometryType(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_SymDifference(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Touches(geography, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_func.Soundex_matches(Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_txtindex.SET_TOKENIZER_PARAMETER(Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.DelimitedExport() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapKeysInfo(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_LineStringPoint(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Char) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_inverse_pca() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_moving_average() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.s3export() TO dbadmin WITH GRANT OPTION;
GRANT INSERT ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT TRUNCATE ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.APPROXIMATE_PERCENTILE(Float) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdSynToSyn(Long Varbinary) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Float) TO public;
GRANT EXECUTE ON ANALYTIC FUNCTION v_func.argmin() TO public;
GRANT EXECUTE ON FUNCTION public.APPROXIMATE_COUNT_DISTINCT_SYNOPSIS_INFO(Long Varbinary) TO public;
GRANT EXECUTE ON FUNCTION public.MapVersion(Long Varbinary) TO public;
GRANT EXECUTE ON FUNCTION public.STV_Geography(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_IsEmpty(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_SimplifyPreserveTopology(geometry, Float) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Within(Long Varchar, Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_X(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.aws_set_config(Varchar, Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.predict_naive_bayes() TO public;
GRANT EXECUTE ON FUNCTION public.predict_pmml() TO public;
GRANT EXECUTE ON FUNCTION v_txtindex.StemmerCaseInsensitive(v Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapKeys(Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_inverse_svd() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_normalize() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.get_model_attribute() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.mode_finder() TO public;
GRANT SELECT ON v_catalog.audit_managing_users_privileges TO public;
GRANT SELECT ON v_catalog.log_params TO public;
GRANT SELECT ON v_catalog.node_subscription_change_phases TO public;
GRANT SELECT ON v_catalog.resource_pool_defaults TO public;
GRANT SELECT ON v_catalog.table_constraints TO public;
GRANT SELECT ON v_internal.dc_catalog_sync_history TO public;
GRANT SELECT ON v_internal.dc_designs TO public;
GRANT SELECT ON v_internal.dc_execution_engine_events TO public;
GRANT SELECT ON v_internal.dc_load_events TO public;
GRANT SELECT ON v_internal.dc_mergeout_requests TO public;
GRANT SELECT ON v_internal.dc_plan_resources TO public;
GRANT SELECT ON v_internal.dc_plans TO public;
GRANT SELECT ON v_internal.dc_renamed_schemata TO public;
GRANT SELECT ON v_internal.dc_requests_retried TO public;
GRANT SELECT ON v_internal.design_output_event_history_report TO public;
GRANT SELECT ON v_internal.vs_catalog_event_drop_partition TO public;
GRANT SELECT ON v_internal.vs_catalog_event_swap_partition TO public;
GRANT SELECT ON v_internal.vs_designs TO public;
GRANT SELECT ON v_internal.vs_dv_wos_containers TO public;
GRANT SELECT ON v_internal.vs_epochs TO public;
GRANT SELECT ON v_internal.vs_index_tool_progress TO public;
GRANT SELECT ON v_internal.vs_logicalstats_rowcount TO public;
GRANT SELECT ON v_internal.vs_parameters_catalog TO public;
GRANT SELECT ON v_internal.vs_projection_column_aggregate_order TO public;
GRANT SELECT ON v_internal.vs_projection_queries TO public;
GRANT SELECT ON v_internal.vs_resource_pool_defaults TO public;
GRANT SELECT ON v_internal.vs_ros TO public;
GRANT SELECT ON v_internal.vs_session_mars_store TO public;
GRANT SELECT ON v_internal.vs_tables_view TO public;
GRANT SELECT ON v_monitor.blobs TO public;
GRANT SELECT ON v_monitor.deployment_projections TO public;
GRANT SELECT ON v_monitor.depot_fetch_queue TO public;
GRANT SELECT ON v_monitor.depot_uploads TO public;
GRANT SELECT ON v_monitor.network_interfaces TO public;
GRANT SELECT ON v_monitor.output_deployment_status TO public;
GRANT SELECT ON v_monitor.partition_status TO public;
GRANT SELECT ON v_monitor.resource_usage TO public;
GRANT SELECT ON v_monitor.session_mars_store TO public;
GRANT SELECT ON v_monitor.udx_fenced_processes TO public;
GRANT SELECT ON v_monitor.user_sessions TO public;
ALTER USER "dbadmin" DEFAULT ROLE dbduser, dbadmin, pseudosuperuser;
ALTER SCHEMA aetna DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA cyclist DEFAULT EXCLUDE PRIVILEGES;
ALTER TABLE aetna.provider_specialty_db2_src EXCLUDE PRIVILEGES;
ALTER TABLE atlas.cust_dim_src EXCLUDE PRIVILEGES;
ALTER TABLE atlas.date_dim EXCLUDE PRIVILEGES;
ALTER TABLE beer.beer_hours EXCLUDE PRIVILEGES;
ALTER TABLE ehr.icd_nine_lkp_src EXCLUDE PRIVILEGES;
ALTER TABLE logistics.test EXCLUDE PRIVILEGES;
ALTER TABLE public.iris EXCLUDE PRIVILEGES;
ALTER TABLE atlas.date_dim OWNER TO dbadmin;
ALTER TABLE atlas.port_dim OWNER TO dbadmin;
ALTER TABLE beer.zipcode OWNER TO dbadmin;
ALTER TABLE brdbeer.page_dimension OWNER TO dbadmin;
ALTER TABLE ehr.departments_src OWNER TO dbadmin;
ALTER TABLE masterdata.alphabet_lkp OWNER TO dbadmin;
GRANT EXECUTE ON AGGREGATE FUNCTION public.ST_Union(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapLookup(Long Varbinary, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_AsText(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Distance(Long Varchar, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeometryN(geography, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeometryType(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_IsSimple(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Y(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.aws_get_config(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_svm_regressor() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_func.Soundex(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_txtindex.SET_SESSION_PARAMETER(Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_txtindex.StemmerCaseSensitive(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON SOURCE public.STV_ShpSource() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.DelimitedExportMulti() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Intersect(Integer, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Rename_Index() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_ShpCreateTable() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_naive_bayes_classes() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.s3export_partition() TO dbadmin WITH GRANT OPTION;
GRANT INSERT ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT USAGE ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapContainsKey(Long Varbinary, Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.PickBestType(Varchar, Integer, Varchar, Integer, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.STV_GetExportShapefileDirectory() TO public;
GRANT EXECUTE ON FUNCTION public.STV_MemSize(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Contains(geography, geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Crosses(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Disjoint(geography, geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_YMin(geography) TO public;
GRANT EXECUTE ON FUNCTION public.apply_bisecting_kmeans() TO public;
GRANT EXECUTE ON FUNCTION public.predict_xgb_classifier() TO public;
GRANT EXECUTE ON FUNCTION v_txtindex.SET_TOKENIZER_PARAMETER(Varchar, Varchar) TO public;
GRANT EXECUTE ON PARSER public.FRegexParser() TO public;
GRANT EXECUTE ON PARSER public.STV_ShpParser() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.FlexTokenizer() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapKeys(Long Varbinary) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapKeysInfo(Long Varbinary) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Intersect(Integer, geometry) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_LineStringPoint(geometry) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_NumCol() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_inverse_pca() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.rf_predictor_importance() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.rsquared(Float, Float) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.TwoGrams(Varchar) TO public;
GRANT SELECT ON v_catalog.all_tables TO public;
GRANT SELECT ON v_catalog.client_auth TO public;
GRANT SELECT ON v_catalog.databases TO public;
GRANT SELECT ON v_catalog.hcatalog_table_list TO public;
GRANT SELECT ON v_catalog.keywords TO public;
GRANT SELECT ON v_catalog.odbc_columns TO public;
GRANT SELECT ON v_catalog.shards TO public;
GRANT SELECT ON v_internal.dc_errors TO public;
GRANT SELECT ON v_internal.dc_lock_requests TO public;
GRANT SELECT ON v_internal.dc_plan_out_of_process_resources TO public;
GRANT SELECT ON v_internal.dc_plan_resource_activities TO public;
GRANT SELECT ON v_internal.dc_plan_step_properties TO public;
GRANT SELECT ON v_internal.dc_rebalanced_operations TO public;
GRANT SELECT ON v_internal.dc_requests_completed TO public;
GRANT SELECT ON v_internal.dc_resource_pool_move TO public;
GRANT SELECT ON v_internal.dc_transaction_ends TO public;
GRANT SELECT ON v_internal.dc_truncation_version_updates TO public;
GRANT SELECT ON v_internal.dc_user_audits TO public;
GRANT SELECT ON v_internal.vs_columns_helper TO public;
GRANT SELECT ON v_internal.vs_constraints TO public;
GRANT SELECT ON v_internal.vs_deploy_projections TO public;
GRANT SELECT ON v_internal.vs_design_output_projection_columns TO public;
GRANT SELECT ON v_internal.vs_dfs_file TO public;
GRANT SELECT ON v_internal.vs_fault_groups TO public;
GRANT SELECT ON v_internal.vs_hcatalog_table_list TO public;
GRANT SELECT ON v_internal.vs_network_interfaces TO public;
GRANT SELECT ON v_internal.vs_parameters_session TO public;
GRANT SELECT ON v_internal.vs_plan_step_output_schema TO public;
GRANT SELECT ON v_internal.vs_procedures TO public;
GRANT SELECT ON v_internal.vs_storage_columns TO public;
GRANT SELECT ON v_internal.vs_tombstones TO public;
GRANT SELECT ON v_monitor.data_collector TO public;
GRANT SELECT ON v_monitor.data_reads TO public;
GRANT SELECT ON v_monitor.dfs_storage TO public;
GRANT SELECT ON v_monitor.event_configurations TO public;
GRANT SELECT ON v_monitor.memory_events TO public;
GRANT SELECT ON v_monitor.projection_usage TO public;
GRANT SELECT ON v_monitor.session_parameters TO public;
GRANT SELECT ON v_monitor.spread_state TO public;
GRANT SELECT ON v_monitor.storage_policies TO public;
GRANT SELECT ON v_monitor.tls_configurations TO public;
ALTER SCHEMA cops DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA drug DEFAULT EXCLUDE PRIVILEGES;
ALTER TABLE aetna.provider_base EXCLUDE PRIVILEGES;
ALTER TABLE aetna.specialty EXCLUDE PRIVILEGES;
ALTER TABLE atlas.port_dim EXCLUDE PRIVILEGES;
ALTER TABLE beer.events EXCLUDE PRIVILEGES;
ALTER TABLE beer.zsharp EXCLUDE PRIVILEGES;
ALTER TABLE migration.data_exports EXCLUDE PRIVILEGES;
ALTER TABLE migration.source_schemas EXCLUDE PRIVILEGES;
ALTER TABLE migration.target_grants EXCLUDE PRIVILEGES;
ALTER TABLE survey.hcahps_src EXCLUDE PRIVILEGES;
ALTER VIEW public.cop_events_view EXCLUDE PRIVILEGES; 
ALTER TABLE aetna.provider_base_db2_src OWNER TO dbadmin;
ALTER TABLE aetna.provider_base_sql_src OWNER TO dbadmin;
ALTER TABLE aetna.provider_base_src OWNER TO dbadmin;
ALTER TABLE atlas.cust_dim OWNER TO dbadmin;
ALTER TABLE cyclist.trip_data_2021_src OWNER TO dbadmin;
ALTER TABLE masterdata.funcstat_lkp OWNER TO dbadmin;
ALTER TABLE migration.data_exports OWNER TO dbadmin;
ALTER TABLE migration.odd_parms_src OWNER TO dbadmin;
ALTER TABLE migration.target_grants_src OWNER TO dbadmin;
ALTER TABLE public.iris OWNER TO dbadmin;
ALTER VIEW atlas.main_report OWNER TO dbadmin;
ALTER VIEW migration.grants OWNER TO dbadmin;
ALTER VIEW public.cop_events_view OWNER TO dbadmin;
GRANT DROP ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(TimestampTz) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON ANALYTIC FUNCTION v_func.argmax() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapVersion(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_ConvexHull(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_IsValid(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_PointN(Long Varchar, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_SRID(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_X(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.apply_bisecting_kmeans() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_pmml() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_xgb_regressor() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON PARSER public.FDelimitedPairParser() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.ParquetExportMulti() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_NN(geometry, geometry, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_PolygonPoint(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_PolygonPoint(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_autoregressor() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(TimeTz) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(TimestampTz) TO public;
GRANT EXECUTE ON ANALYTIC FUNCTION v_func.argmax() TO public;
GRANT EXECUTE ON FUNCTION public.MapJSONExtractor(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_AsBinary(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Buffer(geometry, Float) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Distance(Long Varchar, Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Equals(geography, geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Equals(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromWKB(Long Varbinary) TO public;
GRANT EXECUTE ON FUNCTION public.ST_XMax(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_XMin(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Y(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_intersects(Long Varchar, Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.SetMapKeys() TO public;
GRANT EXECUTE ON FUNCTION public.predict_linear_reg() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.DelimitedExportMulti() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.ParquetExport() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Create_Index(Integer, geometry) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Refresh_Index(Integer, geometry) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.approximate_quantiles() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.error_rate() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_autoregressor() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_naive_bayes_classes() TO public;
GRANT SELECT ON v_catalog.models TO public;
GRANT SELECT ON v_catalog.primary_keys TO public;
GRANT SELECT ON v_catalog.subcluster_resource_pool_overrides TO public;
GRANT SELECT ON v_catalog.text_indices TO public;
GRANT SELECT ON v_catalog.user_audits TO public;
GRANT SELECT ON v_catalog.users TO public;
GRANT SELECT ON v_catalog.view_columns TO public;
GRANT SELECT ON v_internal.dc_design_projection_statements TO public;
GRANT SELECT ON v_internal.dc_design_query_ideal_plan_features TO public;
GRANT SELECT ON v_internal.dc_execution_engine_resources TO public;
GRANT SELECT ON v_internal.dc_hive_custom_partitions TO public;
GRANT SELECT ON v_internal.dc_ldap_link_events TO public;
GRANT SELECT ON v_internal.dc_machine_learning_algorithms TO public;
GRANT SELECT ON v_internal.dc_projection_checkpoint_epochs TO public;
GRANT SELECT ON v_internal.dc_projections_used TO public;
GRANT SELECT ON v_internal.dc_runtime_predicate_info TO public;
GRANT SELECT ON v_internal.dc_tuple_mover_events TO public;
GRANT SELECT ON v_internal.design_output_query_ideal_plan_features_report TO public;
GRANT SELECT ON v_internal.odbc_procedure_columns TO public;
GRANT SELECT ON v_internal.vs_blobs TO public;
GRANT SELECT ON v_internal.vs_catalog_event_alter_partition TO public;
GRANT SELECT ON v_internal.vs_catalog_truncation_status TO public;
GRANT SELECT ON v_internal.vs_configuration_parameters TO public;
GRANT SELECT ON v_internal.vs_data_channels TO public;
GRANT SELECT ON v_internal.vs_databases TO public;
GRANT SELECT ON v_internal.vs_depot_reservations TO public;
GRANT SELECT ON v_internal.vs_hcatalog_table_details TO public;
GRANT SELECT ON v_internal.vs_new_storage_containers TO public;
GRANT SELECT ON v_internal.vs_node_states TO public;
GRANT SELECT ON v_internal.vs_plan_activity_details TO public;
GRANT SELECT ON v_internal.vs_projection_inputs TO public;
GRANT SELECT ON v_internal.vs_projection_recoveries_incremental TO public;
GRANT SELECT ON v_internal.vs_projection_recoveries_replay_delete TO public;
GRANT SELECT ON v_internal.vs_sequences TO public;
GRANT SELECT ON v_internal.vs_storage_locations TO public;
GRANT SELECT ON v_internal.vs_strata TO public;
GRANT SELECT ON v_internal.vs_ud_parameters_session TO public;
GRANT SELECT ON v_monitor.communal_truncation_status TO public;
GRANT SELECT ON v_monitor.design_status TO public;
GRANT SELECT ON v_monitor.disk_storage TO public;
GRANT SELECT ON v_monitor.error_messages TO public;
GRANT SELECT ON v_monitor.load_streams TO public;
GRANT SELECT ON v_monitor.merge_streams TO public;
GRANT SELECT ON v_monitor.node_states TO public;
GRANT SELECT ON v_monitor.query_metrics TO public;
GRANT SELECT ON v_monitor.remote_replication_status TO public;
GRANT SELECT ON v_monitor.resource_pool_move TO public;
GRANT dbadmin TO dbadmin WITH ADMIN OPTION;
GRANT pseudosuperuser TO dbadmin WITH ADMIN OPTION;
ALTER SCHEMA ehr DEFAULT EXCLUDE PRIVILEGES;
ALTER TABLE aetna.specialty_int EXCLUDE PRIVILEGES;
ALTER TABLE atlas.sales EXCLUDE PRIVILEGES;
ALTER TABLE atlas.vehicle_config EXCLUDE PRIVILEGES;
ALTER TABLE commodity.daily_futures_src EXCLUDE PRIVILEGES;
ALTER TABLE cortex.og_flight EXCLUDE PRIVILEGES;
ALTER VIEW cortex.short_vw EXCLUDE PRIVILEGES; 
ALTER TABLE atlas.dealer_dim_src OWNER TO dbadmin;
ALTER TABLE beer.drinkers OWNER TO dbadmin;
ALTER TABLE brdbeer.session_dim OWNER TO dbadmin;
ALTER TABLE migration.target_grants OWNER TO dbadmin;
ALTER VIEW cops.event_flx_view OWNER TO dbadmin;
GRANT ALTER ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.APPROXIMATE_MEDIAN(Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdSynToSyn(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.PickBestType(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Date) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Numeric) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(TimeTz) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapContainsKey(Long Varbinary, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapJSONExtractor(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_AsGeoJSON(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_Geometry(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_AsBinary(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Disjoint(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Envelope(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeographyFromWKB(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_IsSimple(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_NumGeometries(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_PointN(geometry, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Simplify(geometry, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Touches(Long Varchar, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_X(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_XMax(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_YMax(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_logistic_reg() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_func.Edit_Distance(Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_txtindex.Stemmer(v Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Explode() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapItems(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Create_Index(Integer, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Describe_Index() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Extent(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Extent(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_NN(Long Varchar, Long Varchar, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Refresh_Index(Integer, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Refresh_Index(Integer, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_one_hot_encoder() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.lift_table() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.mode_finder() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.ThreeGrams(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.WhitespaceLogTokenizer() TO dbadmin WITH GRANT OPTION;
GRANT UPDATE ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdDataToSyn(Integer) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Interval Year to Month) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Timestamp) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.MapLookup(Long Varbinary, Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.MapSize(Long Varbinary) TO public;
GRANT EXECUTE ON FUNCTION public.STV_GeometryPoint(Float, Float) TO public;
GRANT EXECUTE ON FUNCTION public.STV_IsValidReason(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Area(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_AsText(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_AsText(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Contains(Long Varchar, Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeometryN(Long Varchar, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeometryN(geometry, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_IsEmpty(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Touches(Long Varchar, Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_XMax(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_YMax(geography) TO public;
GRANT EXECUTE ON FUNCTION public.aws_get_config(Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.predict_logistic_reg() TO public;
GRANT EXECUTE ON FUNCTION public.predict_svm_classifier() TO public;
GRANT EXECUTE ON PARSER public.FCsvParser() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapItems(Long Varbinary) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Create_Index(Integer, Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_LineStringPoint(geography) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Char) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_xgb_classifier_classes() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.BasicLogTokenizer() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.FiveGrams(Varchar) TO public;
GRANT SELECT ON v_catalog.foreign_keys TO public;
GRANT SELECT ON v_catalog.projection_columns TO public;
GRANT SELECT ON v_catalog.standard_keywords TO public;
GRANT SELECT ON v_catalog.user_transforms TO public;
GRANT SELECT ON v_catalog.view_tables TO public;
GRANT SELECT ON v_internal.dc_deployment_status TO public;
GRANT SELECT ON v_internal.dc_depot_fetches TO public;
GRANT SELECT ON v_internal.dc_design_projections TO public;
GRANT SELECT ON v_internal.dc_execution_summaries TO public;
GRANT SELECT ON v_internal.dc_explain_plans TO public;
GRANT SELECT ON v_internal.dc_glob_paths_opened TO public;
GRANT SELECT ON v_internal.dc_library_fetches TO public;
GRANT SELECT ON v_internal.dc_plan_parents TO public;
GRANT SELECT ON v_internal.dc_roses_destroyed TO public;
GRANT SELECT ON v_internal.dc_table_recoveries TO public;
GRANT SELECT ON v_internal.session_sequences TO public;
GRANT SELECT ON v_internal.vs_catalog_event_copy_table TO public;
GRANT SELECT ON v_internal.vs_column_storage TO public;
GRANT SELECT ON v_internal.vs_columns TO public;
GRANT SELECT ON v_internal.vs_comments TO public;
GRANT SELECT ON v_internal.vs_data_collector TO public;
GRANT SELECT ON v_internal.vs_depot_lru TO public;
GRANT SELECT ON v_internal.vs_dfs_file_block TO public;
GRANT SELECT ON v_internal.vs_plan_out_of_process_resources TO public;
GRANT SELECT ON v_internal.vs_plan_parents TO public;
GRANT SELECT ON v_internal.vs_plan_resources TO public;
GRANT SELECT ON v_internal.vs_projection_column_aggregate_partition TO public;
GRANT SELECT ON v_internal.vs_projection_recoveries TO public;
GRANT SELECT ON v_internal.vs_projection_segment_information TO public;
GRANT SELECT ON v_internal.vs_rebalance_operations TO public;
GRANT SELECT ON v_internal.vs_resource_pools TO public;
GRANT SELECT ON v_internal.vs_sessions TO public;
GRANT SELECT ON v_internal.vs_sub_comments TO public;
GRANT SELECT ON v_monitor.delete_vectors TO public;
GRANT SELECT ON v_monitor.execution_engine_profiles TO public;
GRANT SELECT ON v_monitor.external_table_details TO public;
GRANT SELECT ON v_monitor.host_resources TO public;
GRANT SELECT ON v_monitor.machine_learning_algorithms TO public;
GRANT SELECT ON v_monitor.projection_recoveries TO public;
GRANT SELECT ON v_monitor.query_consumption TO public;
GRANT SELECT ON v_monitor.query_profiles TO public;
GRANT SELECT ON v_monitor.query_requests TO public;
GRANT SELECT ON v_monitor.storage_bundle_info_statistics TO public;
GRANT SELECT ON v_monitor.system TO public;
GRANT SELECT ON v_monitor.table_recoveries TO public;
GRANT SELECT ON v_monitor.wos_container_storage TO public;
GRANT dbduser TO dbadmin WITH ADMIN OPTION;
ALTER SCHEMA beer DEFAULT EXCLUDE PRIVILEGES;
ALTER TABLE atlas.sales_fact EXCLUDE PRIVILEGES;
ALTER TABLE beer.adj_drinkers EXCLUDE PRIVILEGES;
ALTER TABLE ehr.patients_src EXCLUDE PRIVILEGES;
ALTER TABLE logistics.timetable EXCLUDE PRIVILEGES;
ALTER TABLE masterdata.names_01_src EXCLUDE PRIVILEGES;
ALTER TABLE public.online_retail EXCLUDE PRIVILEGES;
ALTER TABLE segment.retail EXCLUDE PRIVILEGES;
ALTER VIEW migration.odd_parms_vw EXCLUDE PRIVILEGES; 
ALTER TABLE atlas.arrivals_src OWNER TO dbadmin;
ALTER TABLE atlas.sales_fact OWNER TO dbadmin;
ALTER TABLE atlas.vehicle_config OWNER TO dbadmin;
ALTER TABLE commodity.daily_futures_src OWNER TO dbadmin;
ALTER TABLE cortex.for_mike OWNER TO dbadmin;
ALTER TABLE logistics.timetable OWNER TO dbadmin;
ALTER TABLE masterdata.places_src OWNER TO dbadmin;
ALTER TABLE migration.grants_rejects OWNER TO dbadmin;
ALTER TABLE segment.online_sales OWNER TO dbadmin;
ALTER TABLE survey.hcahps_src OWNER TO dbadmin;
GRANT DELETE ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapVersion(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Equals(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Intersects(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_IsEmpty(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Overlaps(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_SRID(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Union(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_X(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_YMin(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_YMin(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_intersects(Long Varchar, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_rf_regressor() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON PARSER public.FDelimitedParser() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON PARSER public.FRegexParser() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapValues(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.ParquetExport() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_rf_classifier_classes() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.StringTokenizerDelim(Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT TRUNCATE ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Numeric) TO public;
GRANT EXECUTE ON FUNCTION public.MapContainsValue(Long Varchar, Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.MapLookup() TO public;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.STV_MemSize(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Area(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_AsText(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_ConvexHull(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeoHash(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromGeoHash(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeometryN(geography, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Intersects(geography, geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_IsValid(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_IsValid(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Length(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_SRID(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Touches(geography, geography) TO public;
GRANT EXECUTE ON FUNCTION public.predict_rf_classifier() TO public;
GRANT EXECUTE ON FUNCTION v_func.Edit_Distance(Varchar, Varchar) TO public;
GRANT EXECUTE ON FUNCTION v_txtindex.SET_SESSION_PARAMETER(Varchar, Varchar) TO public;
GRANT EXECUTE ON PARSER public.FIDXParser() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapAggregate(Varchar, Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapItems() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapKeysInfo(Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.OrcExport() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Describe_Index() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Integer) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_one_hot_encoder() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.confusion_matrix() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.READ_CONFIG_FILE() TO public;
GRANT SELECT ON v_catalog.cluster_layout TO public;
GRANT SELECT ON v_catalog.large_cluster_configuration_status TO public;
GRANT SELECT ON v_catalog.licenses TO public;
GRANT SELECT ON v_catalog.log_queries TO public;
GRANT SELECT ON v_catalog.materialize_flextable_columns_results TO public;
GRANT SELECT ON v_catalog.subclusters TO public;
GRANT SELECT ON v_catalog.system_tables TO public;
GRANT SELECT ON v_catalog.vs_node_subscriptions TO public;
GRANT SELECT ON v_internal.dc_client_server_messages TO public;
GRANT SELECT ON v_internal.dc_deployments TO public;
GRANT SELECT ON v_internal.dc_depot_uploads TO public;
GRANT SELECT ON v_internal.dc_design_queries TO public;
GRANT SELECT ON v_internal.dc_design_query_plan_costs TO public;
GRANT SELECT ON v_internal.dc_design_query_projection_candidates TO public;
GRANT SELECT ON v_internal.dc_design_tables TO public;
GRANT SELECT ON v_internal.dc_plan_activity_phases TO public;
GRANT SELECT ON v_internal.dc_plan_resource_audit_records TO public;
GRANT SELECT ON v_internal.dc_plan_step_output_schema TO public;
GRANT SELECT ON v_internal.dc_resource_releases TO public;
GRANT SELECT ON v_internal.dc_roses_created TO public;
GRANT SELECT ON v_internal.dc_session_parameters TO public;
GRANT SELECT ON v_internal.dc_sips_statistics TO public;
GRANT SELECT ON v_internal.dc_woses_destroyed TO public;
GRANT SELECT ON v_internal.execution_step_timings TO public;
GRANT SELECT ON v_internal.vs_allocator_usage TO public;
GRANT SELECT ON v_internal.vs_bundled_ros TO public;
GRANT SELECT ON v_internal.vs_design_configs TO public;
GRANT SELECT ON v_internal.vs_design_output_projections TO public;
GRANT SELECT ON v_internal.vs_design_output_query_projections TO public;
GRANT SELECT ON v_internal.vs_design_projection_columns_encoding_storage TO public;
GRANT SELECT ON v_internal.vs_execution_engine_profiles TO public;
GRANT SELECT ON v_internal.vs_license_audits TO public;
GRANT SELECT ON v_internal.vs_nodes TO public;
GRANT SELECT ON v_internal.vs_plan_activity_resources TO public;
GRANT SELECT ON v_internal.vs_plans TO public;
GRANT SELECT ON v_internal.vs_storage_bundle_info_statistics TO public;
GRANT SELECT ON v_internal.vs_subclusters TO public;
GRANT SELECT ON v_monitor.output_event_history TO public;
GRANT SELECT ON v_monitor.scan_status TO public;
GRANT SELECT ON v_monitor.user_libraries TO public;
GRANT USAGE ON SCHEMA public TO public;
ALTER SCHEMA segment DEFAULT EXCLUDE PRIVILEGES;
ALTER TABLE atlas.big_report EXCLUDE PRIVILEGES;
ALTER TABLE atlas.cust_dim EXCLUDE PRIVILEGES;
ALTER TABLE brdbeer.session_dim EXCLUDE PRIVILEGES;
ALTER TABLE cortex.iata_xref EXCLUDE PRIVILEGES;
ALTER TABLE drug.blah EXCLUDE PRIVILEGES;
ALTER TABLE migration.grants_src EXCLUDE PRIVILEGES;
ALTER TABLE survey.general_info_src EXCLUDE PRIVILEGES;
ALTER VIEW atlas.main_report EXCLUDE PRIVILEGES; 
ALTER VIEW cops.event_flx_view EXCLUDE PRIVILEGES; 
ALTER TABLE aetna.address OWNER TO dbadmin;
ALTER TABLE aetna.provider_loc_sql_src OWNER TO dbadmin;
ALTER TABLE aetna.provider_specialty_db2_src OWNER TO dbadmin;
ALTER TABLE atlas.cust_sales_src OWNER TO dbadmin;
ALTER TABLE atlas.zip_code_lkp OWNER TO dbadmin;
ALTER TABLE beer.beer_type OWNER TO dbadmin;
ALTER TABLE commodity.daily_futures OWNER TO dbadmin;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdDataToCount(Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapPut() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapRegexExtractor(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapSize(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapSize(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.PickBestType(Varchar, Integer, Varchar, Integer, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_ForceLHR(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_GeographyPoint(Float, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_Geometry(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_MemSize(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Contains(Long Varchar, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Equals(geography, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeoHash(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeographyFromText(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromWKB(Long Varbinary, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Intersection(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_NumGeometries(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_NumPoints(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Within(Long Varchar, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_XMin(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.apply_kmeans() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION v_txtindex.caseInsensitiveNoStemming(x Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapAggregate(Varchar, Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.PickBestType(Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Drop_Index() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_xgb_classifier_classes() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.read_tree() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.FourGrams(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.READ_CONFIG_FILE() TO dbadmin WITH GRANT OPTION;
GRANT UPDATE ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdDataToCount(Integer) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdDataToLongSyn(Integer) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Integer) TO public;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Uuid) TO public;
GRANT EXECUTE ON FUNCTION public.STV_DWithin(geography, geography, Float) TO public;
GRANT EXECUTE ON FUNCTION public.STV_GeographyPoint(Float, Float) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Area(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeometryType(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_PointN(geometry, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_XMax(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_XMin(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Y(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_YMin(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.predict_rf_regressor() TO public;
GRANT EXECUTE ON PARSER public.FDelimitedParser() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapValues(Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_NN(Long Varchar, Long Varchar, Integer) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_ShpCreateTable() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_pca() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.s3export_partition() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.ThreeGrams(Varchar) TO public;
GRANT SELECT ON v_catalog.inheriting_objects TO public;
GRANT SELECT ON v_catalog.jdbc_columns TO public;
GRANT SELECT ON v_catalog.license_audits TO public;
GRANT SELECT ON v_catalog.node_subscriptions TO public;
GRANT SELECT ON v_catalog.vs_subcluster_resource_pool_overrides TO public;
GRANT SELECT ON v_internal.dc_cancel_events TO public;
GRANT SELECT ON v_internal.dc_design_projection_candidates TO public;
GRANT SELECT ON v_internal.dc_glob_paths_pruned TO public;
GRANT SELECT ON v_internal.dc_plan_activities TO public;
GRANT SELECT ON v_internal.dc_requests_issued TO public;
GRANT SELECT ON v_internal.dc_session_ends TO public;
GRANT SELECT ON v_internal.dc_woses_committed TO public;
GRANT SELECT ON v_internal.vs_design_output_query_plan_costs TO public;
GRANT SELECT ON v_internal.vs_design_queries TO public;
GRANT SELECT ON v_internal.vs_execution_engine_resources TO public;
GRANT SELECT ON v_internal.vs_mergeoutcache_proj TO public;
GRANT SELECT ON v_internal.vs_mmap_pool TO public;
GRANT SELECT ON v_internal.vs_projection_attributes TO public;
GRANT SELECT ON v_internal.vs_projection_recoveries_by_container TO public;
GRANT SELECT ON v_internal.vs_segments TO public;
GRANT SELECT ON v_internal.vs_table_recoveries TO public;
GRANT SELECT ON v_monitor.configuration_parameters TO public;
GRANT SELECT ON v_monitor.database_connections TO public;
GRANT SELECT ON v_monitor.import_export_requests TO public;
GRANT SELECT ON v_monitor.load_sources TO public;
GRANT SELECT ON v_monitor.resource_rejections TO public;
GRANT SELECT ON v_monitor.truncated_schemata TO public;
GRANT USAGE ON SCHEMA v_monitor TO public;
ALTER SCHEMA click DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA raw DEFAULT EXCLUDE PRIVILEGES;
ALTER SCHEMA v_func DEFAULT EXCLUDE PRIVILEGES;
ALTER TABLE atlas.cust_dim_vpy_src EXCLUDE PRIVILEGES;
ALTER TABLE atlas.date_dim_src EXCLUDE PRIVILEGES;
ALTER TABLE atlas.region_dim EXCLUDE PRIVILEGES;
ALTER TABLE beer.beer_type EXCLUDE PRIVILEGES;
ALTER TABLE cops.event_flx EXCLUDE PRIVILEGES;
ALTER TABLE cortex.for_mike EXCLUDE PRIVILEGES;
ALTER TABLE ehr.encounters_src EXCLUDE PRIVILEGES;
ALTER TABLE public.cop_events EXCLUDE PRIVILEGES;
ALTER VIEW survey.opioid_vw EXCLUDE PRIVILEGES; 
ALTER TABLE atlas.cust_dim_vpy_src OWNER TO dbadmin;
ALTER TABLE ehr.accounts_src OWNER TO dbadmin;
ALTER TABLE ehr.encounters_src OWNER TO dbadmin;
ALTER TABLE ehr.hospitals_src OWNER TO dbadmin;
ALTER TABLE public.cop_events OWNER TO dbadmin;
ALTER TABLE survey.general_info_src OWNER TO dbadmin;
GRANT EXECUTE ON AGGREGATE FUNCTION public.APPROXIMATE_PERCENTILE(Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Boolean) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapToString(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapToString(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_IsValidReason(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_MemSize(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_Reverse(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_AsBinary(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Buffer(geometry, Float) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Contains(geography, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Contains(geometry, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Disjoint(geography, geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_IsEmpty(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Length(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_NumPoints(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_YMax(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.get_model_summary() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_linear_reg() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.predict_rf_classifier() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON PARSER public.FCefParser() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON PARSER public.FIDXParser() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapAggregate(Long Varchar, Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapKeys(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapValues(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.OrcExportMulti() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.PRC() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_LineStringPoint(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_NN(geography, geography, Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Boolean) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_NumCol() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_pca() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_svd() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.confusion_matrix() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.StringTokenizer() TO dbadmin WITH GRANT OPTION;
GRANT SELECT ON SCHEMA v_txtindex TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.MapSize(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.MapToString(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.STV_Geometry(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.STV_GeometryPoint(Float, Float, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Difference(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Equals(Long Varchar, Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromText(Long Varchar, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_IsSimple(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_IsSimple(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_NumPoints(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_PointN(Long Varchar, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_SymDifference(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.predict_xgb_regressor() TO public;
GRANT EXECUTE ON FUNCTION v_txtindex.StemmerCaseSensitive(Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MSE(Float, Float) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.OrcExportMulti() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.PRC() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Create_Index(Integer, geography) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Extent(Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Intersect(Integer, Float, Float) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_NN(geometry, geometry, Integer) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_PolygonPoint(Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Refresh_Index(Integer, Long Varchar) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.s3export() TO public;
GRANT SELECT ON v_catalog.complex_types TO public;
GRANT SELECT ON v_catalog.projection_checkpoint_epochs TO public;
GRANT SELECT ON v_catalog.schemata TO public;
GRANT SELECT ON v_catalog.user_functions TO public;
GRANT SELECT ON v_catalog.user_procedures TO public;
GRANT SELECT ON v_internal.dc_design_projection_columns_encoding TO public;
GRANT SELECT ON v_internal.dc_design_query_projections TO public;
GRANT SELECT ON v_internal.dc_design_status TO public;
GRANT SELECT ON v_internal.dc_disk_resource_rejections TO public;
GRANT SELECT ON v_internal.dc_lock_releases TO public;
GRANT SELECT ON v_internal.dc_optimizer_stats TO public;
GRANT SELECT ON v_internal.dc_plan_activity_resources TO public;
GRANT SELECT ON v_internal.dc_query_executions TO public;
GRANT SELECT ON v_internal.dc_runtime_predicate_order TO public;
GRANT SELECT ON v_internal.dc_session_starts TO public;
GRANT SELECT ON v_internal.dc_test TO public;
GRANT SELECT ON v_internal.dc_transaction_starts TO public;
GRANT SELECT ON v_internal.vs_branches TO public;
GRANT SELECT ON v_internal.vs_catalog_event_rollback TO public;
GRANT SELECT ON v_internal.vs_cluster_layout TO public;
GRANT SELECT ON v_internal.vs_constraint_columns TO public;
GRANT SELECT ON v_internal.vs_depot_fetch_queue TO public;
GRANT SELECT ON v_internal.vs_grants TO public;
GRANT SELECT ON v_internal.vs_machine_learning_algorithms TO public;
GRANT SELECT ON v_internal.vs_new_storage_container_columns TO public;
GRANT SELECT ON v_internal.vs_plan_parallel_zones TO public;
GRANT SELECT ON v_internal.vs_plan_resource_activities TO public;
GRANT SELECT ON v_internal.vs_procedure_columns TO public;
GRANT SELECT ON v_internal.vs_projection_column_histogram TO public;
GRANT SELECT ON v_internal.vs_tuple_mover_operations TO public;
GRANT SELECT ON v_internal.vs_udfs_statistics TO public;
GRANT SELECT ON v_monitor.designs TO public;
GRANT SELECT ON v_monitor.node_evictions TO public;
GRANT SELECT ON v_monitor.notifier_errors TO public;
GRANT SELECT ON v_monitor.projection_storage TO public;
GRANT SELECT ON v_monitor.query_events TO public;
GRANT SELECT ON v_monitor.resource_pool_status TO public;
GRANT SELECT ON v_monitor.resource_rejection_details TO public;
GRANT SELECT ON v_monitor.storage_tiers TO public;
GRANT SELECT ON v_monitor.strata TO public;
GRANT SELECT ON v_monitor.transactions TO public;
ALTER TABLE aetna.provider_base_db2_src EXCLUDE PRIVILEGES;
ALTER TABLE aetna.provider_base_dup EXCLUDE PRIVILEGES;
ALTER TABLE aetna.provider_loc_sql_src EXCLUDE PRIVILEGES;
ALTER TABLE aetna.provider_specialty_sql_src EXCLUDE PRIVILEGES;
ALTER TABLE drug.ctrx2_src EXCLUDE PRIVILEGES;
ALTER TABLE masterdata.alphabet_lkp EXCLUDE PRIVILEGES;
ALTER TABLE masterdata.alteryx_input EXCLUDE PRIVILEGES;
ALTER TABLE migration.grants_rejects EXCLUDE PRIVILEGES;
ALTER TABLE public.cop_events_keys EXCLUDE PRIVILEGES;
ALTER TABLE ehr.patients_src OWNER TO dbadmin;
ALTER TABLE masterdata.alteryx_input OWNER TO dbadmin;
ALTER TABLE public.online_retail OWNER TO dbadmin;
ALTER VIEW cortex.short_vw OWNER TO dbadmin;
ALTER VIEW survey.opioid_vw OWNER TO dbadmin;
GRANT DROP ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.APPROXIMATE_COUNT_DISTINCT_SYNOPSIS_INFO(Long Varbinary) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_Geography(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.STV_MemSize(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Area(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromGeoHash(Long Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_IsSimple(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_IsValid(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_Y(geography) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.ST_YMax(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION public.isOrContains(map Long Varchar, val Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Export2Shapefile() TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Intersect(Integer, geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_PolygonPoint(geometry) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Integer) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.FiveGrams(Varchar) TO dbadmin WITH GRANT OPTION;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Boolean) TO public;
GRANT EXECUTE ON FUNCTION public.MapDelimitedExtractor(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.STV_AsGeoJSON(geography) TO public;
GRANT EXECUTE ON FUNCTION public.STV_DWithin(Long Varchar, Long Varchar, Float) TO public;
GRANT EXECUTE ON FUNCTION public.STV_DWithin(geometry, geometry, Float) TO public;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(Float, Float) TO public;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Envelope(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeographyFromText(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_GeomFromText(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Intersects(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_IsEmpty(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_IsValid(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Length(Long Varchar) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Length(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_PointN(geography, Integer) TO public;
GRANT EXECUTE ON FUNCTION public.ST_SRID(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Touches(geometry, geometry) TO public;
GRANT EXECUTE ON FUNCTION public.ST_Within(geography, geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_X(geography) TO public;
GRANT EXECUTE ON FUNCTION public.ST_YMax(geometry) TO public;
GRANT EXECUTE ON FUNCTION public.predict_svm_regressor() TO public;
GRANT EXECUTE ON PARSER public.FJSONParser() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.PickBestType(Varbinary) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Extent(geometry) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Refresh_Index(Integer, geography) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Rename_Index() TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Boolean) TO public;
GRANT EXECUTE ON TRANSFORM FUNCTION public.lift_table() TO public;
GRANT SELECT ON v_catalog.columns TO public;
GRANT SELECT ON v_catalog.epochs TO public;
GRANT SELECT ON v_catalog.grants TO public;
GRANT SELECT ON v_catalog.passwords TO public;
GRANT SELECT ON v_internal.dc_audit_details TO public;
GRANT SELECT ON v_internal.dc_blob_events TO public;
GRANT SELECT ON v_internal.dc_execution_engine_profiles TO public;
GRANT SELECT ON v_internal.dc_notifications TO public;
GRANT SELECT ON v_internal.dc_plan_steps TO public;
GRANT SELECT ON v_internal.dc_resource_acquisitions TO public;
GRANT SELECT ON v_internal.dc_tombstone_events TO public;
GRANT SELECT ON v_internal.dc_udx_events TO public;
GRANT SELECT ON v_internal.design_segmented_projection_data_distribution_report TO public;
GRANT SELECT ON v_internal.vs_deployment_configs TO public;
GRANT SELECT ON v_internal.vs_design_output_event_history TO public;
GRANT SELECT ON v_internal.vs_design_output_projection_statements TO public;
GRANT SELECT ON v_internal.vs_design_output_query_ideal_plan_features TO public;
GRANT SELECT ON v_internal.vs_design_tables TO public;
GRANT SELECT ON v_internal.vs_inherited_privileges TO public;
GRANT SELECT ON v_internal.vs_logical_colstats TO public;
GRANT SELECT ON v_internal.vs_mergeout_request_tracker_status TO public;
GRANT SELECT ON v_internal.vs_plan_activity_phases TO public;
GRANT SELECT ON v_internal.vs_plan_resource_phases TO public;
GRANT SELECT ON v_internal.vs_projection_outputs TO public;
GRANT SELECT ON v_internal.vs_storage_policies TO public;
GRANT SELECT ON v_internal.vs_system_tables TO public;
GRANT SELECT ON v_monitor.allocator_usage TO public;
GRANT SELECT ON v_monitor.current_session TO public;
GRANT SELECT ON v_monitor.deploy_status TO public;
GRANT SELECT ON v_monitor.depot_fetches TO public;
GRANT SELECT ON v_monitor.depot_pin_policies TO public;
GRANT SELECT ON v_monitor.depot_sizes TO public;
GRANT SELECT ON v_monitor.hive_custom_partitions_accessed TO public;
GRANT SELECT ON v_monitor.locks TO public;
GRANT SELECT ON v_monitor.partitions TO public;
GRANT SELECT ON v_monitor.projection_refreshes TO public;
GRANT SELECT ON v_monitor.table_recovery_status TO public;
GRANT SELECT ON v_monitor.tuple_mover_operations TO public;
GRANT SELECT ON v_monitor.user_library_manifest TO public;
ALTER SCHEMA v_txtindex DEFAULT EXCLUDE PRIVILEGES;
ALTER TABLE atlas.control EXCLUDE PRIVILEGES;
ALTER TABLE atlas.cust_sales_src EXCLUDE PRIVILEGES;
ALTER TABLE atlas.dealer_dim_src EXCLUDE PRIVILEGES;
ALTER TABLE atlas.zip_code_lkp EXCLUDE PRIVILEGES;
ALTER TABLE beer.drinkers EXCLUDE PRIVILEGES;
ALTER TABLE cyclist.trip_data_2021_src EXCLUDE PRIVILEGES;
ALTER TABLE ehr.drugs EXCLUDE PRIVILEGES;
ALTER VIEW migration.grants EXCLUDE PRIVILEGES; 
ALTER TABLE aetna.specialty OWNER TO dbadmin;
ALTER TABLE atlas.cust_dim_src OWNER TO dbadmin;
ALTER TABLE atlas.mock_dealer OWNER TO dbadmin;
ALTER TABLE atlas.sales OWNER TO dbadmin;
ALTER TABLE beer.events_by_user OWNER TO dbadmin;
ALTER TABLE beer.zsharp OWNER TO dbadmin;
ALTER TABLE brdbeer.user_agent OWNER TO dbadmin;
ALTER TABLE cops.event_flx OWNER TO dbadmin;
ALTER TABLE cops.event_flx_keys OWNER TO dbadmin;
ALTER TABLE cortex.og_flight OWNER TO dbadmin;
ALTER TABLE drug.blah OWNER TO dbadmin;
ALTER TABLE drug.ctrx2_src OWNER TO dbadmin;
ALTER TABLE migration.grants_src OWNER TO dbadmin;
ALTER TABLE public.cop_events_keys OWNER TO dbadmin;
ALTER VIEW migration.odd_parms_vw OWNER TO dbadmin;
