grant all on sandbox.qc_table_stats to Databurst_Updt;
grant all on metadata.id_lookup to Databurst_Updt;
grant all on veeva.dsa_slide to Databurst_Updt;
grant all on sequence metadata.job_id_sequence to Databurst_Updt;
grant usage on schema mdm to Databurst_Updt;
grant all on mdm.address to Databurst_Updt;
grant all on metadata.log_job_events to Databurst_Updt;
grant all on integration.copay_detail_weekly to Databurst_Updt;
grant all on metadata.workflow_command to Databurst_Updt;
grant all on product.source_product to Databurst_Updt;
grant all on integration.prescriber_rx to Databurst_Updt;
grant all on datamart.prescriber_rx to Databurst_Updt;
grant all on product.basket to Databurst_Updt;
grant all on veeva.ids_call_detail to Databurst_Updt;

grant all on sandbox.qc_table_stats to Databurst_Updt;
grant all on metadata.id_lookup to Databurst_Updt;
grant all on veeva.dsa_slide to Databurst_Updt;
grant all on sequence metadata.job_id_sequence to Databurst_Updt;
select sql from migration.user_ddl where principal_name ilike '%Databurst%';
grant usage on schema mdm to Databurst_Updt;
grant all on mdm.address to Databurst_Updt;
grant all on metadata.log_job_events to Databurst_Updt;
grant all on integration.copay_detail_weekly to Databurst_Updt;
grant all on metadata.workflow_command to Databurst_Updt;
grant all on metadata.workflow_process  to Databurst_Updt;
grant all on cleansed.ims_mhj_qty_w to Databurst_Updt;
grant all on teva_ingestion.ims_mhj_qty_w to Databurst_Updt;
grant all on product.source_product to Databurst_Updt;
grant all on datamart.prescriber_rx to Databurst_Updt;
grant all on product.basket to Databurst_Updt;
grant all on veeva.ids_call_detail to Databurst_Updt;
grant all on integration.prescriber_rx to Databurst_Updt;
grant all on datamart.tvcmid_xref to Databurst_Updt;
grant all on customer_master.tvcmid_xref to Databurst_Updt;
grant all on sequence product.basket_id_seq to Databurst_Updt;
grant all on datamart.oncology_invoice_adjustments to Databurst_Updt;
grant all on veeva.v_product to Databurst_Updt;
grant all on datamart.specialty_pharmacy_shipment  to Databurst_Updt;
