GRANT USAGE ON SCHEMA v_internal TO public;;
GRANT USAGE ON SCHEMA v_func TO dbadmin WITH GRANT OPTION;;
GRANT SELECT ON v_monitor.tuple_mover_operations TO public;;
GRANT SELECT ON v_monitor.table_statistics TO public;;
GRANT SELECT ON v_monitor.resource_usage TO public;;
GRANT SELECT ON v_monitor.resource_rejections TO public;;
GRANT SELECT ON v_monitor.projection_usage TO public;;
GRANT SELECT ON v_monitor.projection_recoveries TO public;;
GRANT SELECT ON v_monitor.partition_status TO public;;
GRANT SELECT ON v_monitor.notifier_errors TO public;;
GRANT SELECT ON v_monitor.machine_learning_algorithms TO public;;
GRANT SELECT ON v_monitor.lock_usage TO public;;
GRANT SELECT ON v_monitor.import_export_requests TO public;;
GRANT SELECT ON v_monitor.execution_engine_profiles TO public;;
GRANT SELECT ON v_monitor.dfs_storage TO public;;
GRANT SELECT ON v_monitor.design_tables TO public;;
GRANT SELECT ON v_monitor.depot_sizes TO public;;
GRANT SELECT ON v_monitor.depot_fetches TO public;;
GRANT SELECT ON v_monitor.deployment_projections TO public;;
GRANT SELECT ON v_monitor.deployment_projection_statements TO public;;
GRANT SELECT ON v_monitor.data_reads TO public;;
GRANT SELECT ON v_monitor.critical_nodes TO public;;
GRANT SELECT ON v_monitor.critical_hosts TO public;;
GRANT SELECT ON v_monitor.column_storage TO public;;
GRANT SELECT ON v_monitor.allocator_usage TO public;;
GRANT SELECT ON v_internal.vs_projection_recoveries_replay_delete TO public;;
GRANT SELECT ON v_internal.vs_projection_recoveries_incremental TO public;;
GRANT SELECT ON v_internal.vs_projection_recoveries_by_container TO public;;
GRANT SELECT ON v_internal.design_output_query_plan_costs TO public;;
GRANT SELECT ON v_internal.design_output_query_ideal_plan_features_report TO public;;
GRANT SELECT ON v_internal.design_configs TO public;;
GRANT SELECT ON v_catalog.view_tables TO public;;
GRANT SELECT ON v_catalog.users TO public;;
GRANT SELECT ON v_catalog.user_transforms TO public;;
GRANT SELECT ON v_catalog.user_procedures TO public;;
GRANT SELECT ON v_catalog.user_audits TO public;;
GRANT SELECT ON v_catalog.text_indices TO public;;
GRANT SELECT ON v_catalog.system_tables TO public;;
GRANT SELECT ON v_catalog.storage_locations TO public;;
GRANT SELECT ON v_catalog.odbc_columns TO public;;
GRANT SELECT ON v_catalog.node_subscription_change_phases TO public;;
GRANT SELECT ON v_catalog.models TO public;;
GRANT SELECT ON v_catalog.log_tables TO public;;
GRANT SELECT ON v_catalog.inherited_privileges TO public;;
GRANT SELECT ON v_catalog.comments TO public;;
GRANT SELECT ON v_catalog.all_tables TO public;;
GRANT SELECT ON v_monitor.user_library_manifest TO public;;
GRANT SELECT ON v_monitor.udx_fenced_processes TO public;;
GRANT SELECT ON v_monitor.table_recovery_status TO public;;
GRANT SELECT ON v_monitor.storage_containers TO public;;
GRANT SELECT ON v_monitor.sessions TO public;;
GRANT SELECT ON v_monitor.session_profiles TO public;;
GRANT SELECT ON v_monitor.recovery_status TO public;;
GRANT SELECT ON v_monitor.event_configurations TO public;;
GRANT SELECT ON v_monitor.delete_vectors TO public;;
GRANT SELECT ON v_monitor.current_session TO public;;
GRANT SELECT ON v_monitor.communal_truncation_status TO public;;
GRANT SELECT ON v_internal.vs_views TO public;;
GRANT SELECT ON v_internal.vs_user_function_parameters TO public;;
GRANT SELECT ON v_internal.vs_uploader_tasks TO public;;
GRANT SELECT ON v_internal.vs_system_tables TO public;;
GRANT SELECT ON v_internal.vs_storage_policies TO public;;
GRANT SELECT ON v_internal.vs_storage_bundle_info_statistics TO public;;
GRANT SELECT ON v_internal.vs_shards TO public;;
GRANT SELECT ON v_internal.vs_sessions TO public;;
GRANT SELECT ON v_internal.vs_sequences TO public;;
GRANT SELECT ON v_internal.vs_segments_helper TO public;;
GRANT SELECT ON v_internal.vs_ros_containers TO public;;
GRANT SELECT ON v_internal.vs_resource_pool_defaults TO public;;
GRANT SELECT ON v_internal.vs_resource_acquisitions TO public;;
GRANT SELECT ON v_internal.vs_projections TO public;;
GRANT SELECT ON v_internal.vs_projection_user_defined_transforms TO public;;
GRANT SELECT ON v_internal.vs_projection_refreshes TO public;;
GRANT SELECT ON v_internal.vs_projection_queries TO public;;
GRANT SELECT ON v_internal.vs_projection_outputs TO public;;
GRANT SELECT ON v_internal.vs_projection_inputs TO public;;
GRANT SELECT ON v_internal.vs_projection_column_expressions TO public;;
GRANT SELECT ON v_internal.vs_projection_column_aggregate_order TO public;;
GRANT SELECT ON v_internal.vs_plan_steps TO public;;
GRANT SELECT ON v_internal.vs_plan_resource_phases TO public;;
GRANT SELECT ON v_internal.vs_plan_resource_activities TO public;;
GRANT SELECT ON v_internal.vs_plan_phases TO public;;
GRANT SELECT ON v_internal.vs_plan_parents TO public;;
GRANT SELECT ON v_internal.vs_plan_activity_phases TO public;;
GRANT SELECT ON v_internal.vs_plan_activities TO public;;
GRANT SELECT ON v_internal.vs_parameters_session TO public;;
GRANT SELECT ON v_internal.vs_node_dependencies TO public;;
GRANT SELECT ON v_internal.vs_new_storage_containers TO public;;
GRANT SELECT ON v_internal.vs_new_storage_container_columns TO public;;
GRANT SELECT ON v_internal.vs_mmap_pool TO public;;
GRANT SELECT ON v_internal.vs_mergeoutcache_ros TO public;;
GRANT SELECT ON v_internal.vs_mergeout_request_tracker_status TO public;;
GRANT SELECT ON v_internal.vs_mergeout_request_tracker_queue TO public;;
GRANT SELECT ON v_internal.vs_logicalstats_datapages TO public;;
GRANT SELECT ON v_internal.vs_logical_colstats TO public;;
GRANT SELECT ON v_internal.vs_license_audits TO public;;
GRANT SELECT ON v_internal.vs_hcatalog_table_details TO public;;
GRANT SELECT ON v_internal.vs_hcatalog_configurations TO public;;
GRANT SELECT ON v_internal.vs_execution_engine_resources TO public;;
GRANT SELECT ON v_internal.vs_dfs_file TO public;;
GRANT SELECT ON v_internal.vs_design_segmented_projection_data_distribution TO public;;
GRANT SELECT ON v_internal.vs_design_projection_columns_encoding_storage TO public;;
GRANT SELECT ON v_internal.vs_design_output_query_ideal_plan_features TO public;;
GRANT SELECT ON v_internal.vs_design_output_projection_columns TO public;;
GRANT SELECT ON v_internal.vs_depot_size TO public;;
GRANT SELECT ON v_internal.vs_deploy_projections TO public;;
GRANT SELECT ON v_internal.vs_databases TO public;;
GRANT SELECT ON v_internal.vs_data_channels_closed TO public;;
GRANT SELECT ON v_internal.vs_columns_helper TO public;;
GRANT SELECT ON v_internal.vs_catalog_event_move_partition TO public;;
GRANT SELECT ON v_internal.vs_catalog_event_copy_table TO public;;
GRANT SELECT ON v_internal.vs_catalog_event_add_derived_column TO public;;
GRANT SELECT ON v_internal.vs_allocator_usage TO public;;
GRANT SELECT ON v_internal.system TO public;;
GRANT SELECT ON v_internal.send_protocol TO public;;
GRANT SELECT ON v_internal.recv_protocol TO public;;
GRANT SELECT ON v_internal.dc_test TO public;;
GRANT SELECT ON v_internal.dc_session_temprel_events TO public;;
GRANT SELECT ON v_internal.dc_session_starts TO public;;
GRANT SELECT ON v_internal.dc_session_parameters TO public;;
GRANT SELECT ON v_internal.dc_runtime_priority_changes TO public;;
GRANT SELECT ON v_internal.dc_runtime_predicate_order TO public;;
GRANT SELECT ON v_internal.dc_runtime_predicate_info TO public;;
GRANT SELECT ON v_internal.dc_roses_destroyed TO public;;
GRANT SELECT ON v_internal.dc_resource_releases TO public;;
GRANT SELECT ON v_internal.dc_resource_pool_move TO public;;
GRANT SELECT ON v_internal.dc_requests_retried TO public;;
GRANT SELECT ON v_internal.dc_requests_issued TO public;;
GRANT SELECT ON v_internal.dc_query_executions TO public;;
GRANT SELECT ON v_internal.dc_projections_used TO public;;
GRANT SELECT ON v_internal.dc_projection_refreshes_completed TO public;;
GRANT SELECT ON v_internal.dc_projection_recoveries TO public;;
GRANT SELECT ON v_internal.dc_plan_steps TO public;;
GRANT SELECT ON v_internal.dc_plan_resource_audit_records TO public;;
GRANT SELECT ON v_internal.dc_hive_custom_partitions TO public;;
GRANT SELECT ON v_internal.dc_file_reads TO public;;
GRANT SELECT ON v_internal.dc_explain_plans TO public;;
GRANT SELECT ON v_internal.dc_execution_engine_resources TO public;;
GRANT SELECT ON v_internal.dc_disk_resource_rejections TO public;;
GRANT SELECT ON v_internal.dc_designs TO public;;
GRANT SELECT ON v_internal.dc_design_tables TO public;;
GRANT SELECT ON v_internal.dc_design_query_ideal_plan_features TO public;;
GRANT SELECT ON v_internal.dc_design_projections TO public;;
GRANT SELECT ON v_internal.dc_design_projection_candidates TO public;;
GRANT SELECT ON v_internal.dc_depot_fetches TO public;;
GRANT SELECT ON v_internal.dc_deployments TO public;;
GRANT SELECT ON v_internal.dc_deployment_status TO public;;
GRANT SELECT ON v_internal.dc_deployment_projections TO public;;
GRANT SELECT ON v_internal.dc_cpu_affinity_changes TO public;;
GRANT SELECT ON v_internal.dc_client_server_messages TO public;;
GRANT SELECT ON v_internal.dc_blob_events TO public;;
GRANT SELECT ON v_internal.dc_analyze_statistics TO public;;
GRANT SELECT ON v_catalog.shards TO public;;
GRANT SELECT ON v_catalog.session_subscriptions TO public;;
GRANT SELECT ON v_catalog.node_subscriptions TO public;;
GRANT SELECT ON v_catalog.complex_types TO public;;
GRANT SELECT ON v_catalog.client_auth TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.TwoGrams(Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.StringTokenizerDelim(Varchar, Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.StringTokenizer() TO public;;
GRANT EXECUTE ON FUNCTION v_txtindex.StemmerCaseInsensitive(v Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION v_txtindex.Stemmer(v Long Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.READ_CONFIG_FILE() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION v_txtindex.FourGrams(Varchar) TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(TimestampTz) TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Date) TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Uuid) TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Integer) TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Boolean) TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Long Varbinary) TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION v_func.listagg(Varchar) TO public;;
GRANT EXECUTE ON ANALYTIC FUNCTION v_func.argmin() TO public;;
GRANT EXECUTE ON FUNCTION v_func.Soundex_matches(Varchar, Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.s3export() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.rf_predictor_importance() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.reverse_normalize() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_xgb_classifier_classes() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_rf_classifier_classes() TO public;;
GRANT EXECUTE ON FUNCTION public.predict_pmml() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_naive_bayes_classes() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.predict_moving_average() TO public;;
GRANT EXECUTE ON FUNCTION public.isOrContains(map Long Varchar, val Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.get_model_attribute() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_svd() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.apply_pca() TO public;;
GRANT EXECUTE ON FUNCTION public.apply_bisecting_kmeans() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Char) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Date) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.Summarize_CatCol(Integer) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_YMax(geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Y(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_XMin(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_X(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_X(geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Within(geometry, geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Transform(geometry, Integer) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Touches(Long Varchar, Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Touches(geography, geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_SymDifference(geometry, geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_SimplifyPreserveTopology(geometry, Float) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Simplify(geometry, Float) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_SRID(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_SRID(Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_PointN(Long Varchar, Integer) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Length(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_IsValid(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_IsSimple(Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_IsEmpty(geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Intersects(geography, geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Intersection(geometry, geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_GeometryType(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_GeometryN(Long Varchar, Integer) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_GeographyFromWKB(Long Varbinary) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_GeoHash(Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_GeoHash(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Envelope(geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Distance(geography, geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Disjoint(geometry, geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_ConvexHull(geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Contains(geometry, geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Boundary(geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_AsBinary(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Area(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Area(Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION public.ST_Area(geometry) TO public;;
GRANT EXECUTE ON SOURCE public.STV_ShpSource() TO public;;
GRANT EXECUTE ON PARSER public.STV_ShpParser() TO public;;
GRANT EXECUTE ON FUNCTION public.STV_Reverse(geography) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Refresh_Index(Integer, geometry) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_PolygonPoint(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.STV_MemSize(geography) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Intersect(Integer, Float, Float) TO public;;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.STV_Intersect(geometry) TO public;;
GRANT EXECUTE ON FUNCTION public.STV_GeometryPoint(Float, Float, Integer) TO public;;
GRANT EXECUTE ON FUNCTION public.STV_Geometry(Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION public.STV_Geometry(geography) TO public;;
GRANT EXECUTE ON FUNCTION public.STV_Geography(Long Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Extent(Long Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Drop_Index() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.STV_Describe_Index() TO public;;
GRANT EXECUTE ON FUNCTION public.STV_DWithin(Long Varchar, Long Varchar, Float) TO public;;
GRANT EXECUTE ON FUNCTION public.STV_AsGeoJSON(Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION public.MapSize(Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION public.MapRegexExtractor(Long Varchar) TO public;;
GRANT EXECUTE ON FUNCTION public.MapLookup(Long Varbinary, Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapKeys(Long Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapItems(Long Varbinary) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapAggregate(Long Varchar, Long Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.MapAggregate(Varchar, Varchar) TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.FlexTokenizer() TO public;;
GRANT EXECUTE ON PARSER public.FCefParser() TO public;;
GRANT EXECUTE ON PARSER public.FAvroParser() TO public;;
GRANT EXECUTE ON FUNCTION public.EmptyMap() TO public;;
GRANT EXECUTE ON TRANSFORM FUNCTION public.DelimitedExportMulti() TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdSynToSyn(Long Varbinary) TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdSynToCount(Long Varbinary) TO public;;
GRANT EXECUTE ON AGGREGATE FUNCTION public.AcdDataToLongSyn(Integer) TO public;;
